# Reusable vars
x-var:
  - &POSTGRES_USER postgres
  - &POSTGRES_PASSWORD default
  - &POSTGRES_DATABASE postgres
  - &node-image node:22

# Reusable envars for postgres
x-postgres-vars: &postgres-vars
  POSTGRES_HOST: database
  POSTGRES_USER: *POSTGRES_USER
  POSTGRES_PASSWORD: *POSTGRES_PASSWORD
  POSTGRES_DATABASE: *POSTGRES_DATABASE

services:
  # Oracle Legacy Database Service
  # We use by default the docker image we build locally, but you can
  # uncomment the image line to use the official image from Docker Hub,
  # and comment out the build section.
  legacydb:
    container_name: oracle
    #build:
    #  context: legacydb
    #  dockerfile: Dockerfile
    environment:
      # Use an environment variable for the Oracle password. Set APP_USER_PASSWORD in your .env file or environment.
      APP_USER_PASSWORD: ${APP_USER_PASSWORD}
      APP_USER: THE
      ORACLE_RANDOM_PASSWORD: yes
    platform: "linux/amd64"
    # This image is basically the same used in the Dockerfile, but prebuilt and
    # available in Docker Hub for convenience.
    image: gvenzl/oracle-free:23.9-slim-faststart
    ports: [1521:1521]
    volumes: [/opt/oracle/oradata]
    healthcheck:
      test: [ "CMD-SHELL", "healthcheck.sh" ]
      interval: 5s
      timeout: 10s
      retries: 10
    <<: *defaults

  # Flyway service to initialize/migrate the legacy Oracle DB
  # It depends on the legacydb service to ensure the DB is up before running migrations
  legacyflyway:
    container_name: flyway
    image: flyway/flyway
    command: -url=jdbc:oracle:thin:@legacydb:1521/FREEPDB1 -user=THE -password=${APP_USER_PASSWORD} -connectRetries=60 migrate
    volumes: [./backend/src/test/resources/db/migration:/flyway/sql]
    depends_on:
      legacydb:
        condition: service_healthy
    <<: *defaults

  # Backend Service
  # We use by default the docker image we build locally, but you can
  # uncomment the image line to use the official image from GitHub Container Registry,
  # and comment out the build section.
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    # When using the image from the registry, replace XXX with the desired tag
    #image: ghcr.io/bcgov/nr-waste-plus/backend:XXX
    ports: [8080:8080]
    # We map the volume to override the default configuration with our local config
    # It is easier than passing everything as environment variables
    volumes: [./backend/config:/app/config]
    depends_on:
      database:
        condition: service_healthy
    <<: *defaults

  frontend:
    container_name: frontend
    entrypoint: sh -c "npm ci --ignore-scripts && npm run dev"
    environment:
      BACKEND_URL: http://backend:3000
      PORT: 3000
      NODE_ENV: development
    image: *node-image
    ports: ["3000:3000"]
    volumes: ["./frontend:/app", "/app/node_modules"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
    working_dir: "/app"
    depends_on:
      backend:
        condition: service_healthy

  caddy:
    container_name: caddy
    profiles: ["caddy"]
    build: ./frontend
    environment:
      NODE_ENV: development
      PORT: 3000
      BACKEND_URL: http://backend:3000
      LOG_LEVEL: info
    ports: ["3005:3000"]
    volumes: ["./frontend/Caddyfile:/etc/caddy/Caddyfile"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
    depends_on:
      backend:
        condition: service_healthy
