-- #335 -- Schedule 4: clearing a category's last value must persist (the row goes), and the fix is
-- server-side reconciliation of the PUT's category list against what is stored. That is a
-- DESTRUCTIVE edit (rows are deleted), so it gets a mill of its own rather than mill 546, whose
-- "Existing Dump" every other Schedule4WriteIT edit case reads back and whose distance child 8002
-- put_edit_updatesInPlace expects to still exist.
--
-- REPEATABLE (R__), data band, prefix 45: below R__70 so the canonical submitter's set-based mill
-- association covers mill 547 (Schedule4WriteIT runs security OFF, but the fixture stays reachable
-- under either setting the same way 540-546 are).
--
-- Mill 547 / 2021 -- ACT, Draft, one location "Clearable Dump":
--   primary 8070 (DISTANCE null)  fixed 40 Lakeside Dry Dump  VOLUME 400 / COST 800   detail 8170
--                                 fixed 41 Water Dump         VOLUME 7   / COST 70    detail 8171
--   distance child 8071 (code 47 Truck Barge/Ferry, DISTANCE 20)  VOLUME 100 / COST 500  detail 8172
-- Owned SOLELY by Schedule4WriteIT.put_edit_omittedCategories_areCleared, which first empties 40's
-- Cost (partial clear: the row stays with COST null) and then sends only 41 (40's detail and 47's
-- child must be gone, 41 untouched). Two PUTs, revision read at runtime.
--
-- PK ranges, verified unused across every migration here and in db-e2e: mill 547 (Schedule 4's
-- 540-552 neighbourhood; 547-549 were free), TRANSPORTATION_REPORT 8070-8071 (in use: 8001-8090
-- sparse), ILCR_COST_REPORT_DETAIL 8170-8172 (below 9000, clear of ILCR_COST_REPORT_DETAIL_SEQ).
-- The 8070/8071 ids sit below ILCR_REPORT_COMMON_SEQ's 9000 start, so a created row never collides.
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID)
  SELECT 547, 'Sch4 Clear Category Milling', 547, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.MILL WHERE MILL_ID = 547);
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID)
  SELECT 547, 'ACT', 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_STATUS_XREF WHERE ILCR_MILL_STATUS_XREF_ID = 547);
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID)
  SELECT 2021, 547, 'D', 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_REPORT_STATUS WHERE REPORT_YEAR = 2021 AND ILCR_MILL_ID = 547);

-- "Clearable Dump" primary: fixed 40 (400 / 800) and fixed 41 (7 / 70).
INSERT INTO THE.TRANSPORTATION_REPORT (TRANSPORTATION_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION_DESCRIPTION, DISTANCE, TRANSPORTATION_CYCLE_TIME, REVISION_COUNT, ENTRY_USERID)
  SELECT 8070, 2021, 547, '4', 'Clearable Dump', NULL, NULL, 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.TRANSPORTATION_REPORT WHERE TRANSPORTATION_REPORT_ID = 8070);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, TRANSPORTATION_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 8170, 8070, 40, 400, 800, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 8170);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, TRANSPORTATION_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 8171, 8070, 41, 7, 70, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 8171);
-- "Clearable Dump" distance child: code 47, DISTANCE 20, 100 / 500.
INSERT INTO THE.TRANSPORTATION_REPORT (TRANSPORTATION_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION_DESCRIPTION, DISTANCE, TRANSPORTATION_CYCLE_TIME, REVISION_COUNT, ENTRY_USERID)
  SELECT 8071, 2021, 547, '4', 'Clearable Dump', 20, NULL, 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.TRANSPORTATION_REPORT WHERE TRANSPORTATION_REPORT_ID = 8071);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, TRANSPORTATION_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 8172, 8071, 47, 100, 500, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 8172);
