-- #335 review (PR #510) -- a Schedule 4 location family shaped the way LEGACY data can be, which the
-- 540-547 fixtures never are:
--
--   * NO distance-null primary report. The document then serves the family's lowest report id as
--     the location's id (Schedule4Service §Decision 2 fallback), so the id an edit is addressed to
--     is itself a distance child -- and here it also carries the family's fixed detail row.
--   * TWO children for one distance code (47). A first-row-only lookup deleted one and left the
--     other to bring its figures back on the next read.
--
-- Mill 548 / 2021 -- ACT, Draft, one location "Legacy Dump":
--   8072  code 47 child, DISTANCE 10   detail 8173 (47: VOLUME 50 / COST 100)
--                                      detail 8174 (40: VOLUME 400 / COST 800)  <- fixed row on it
--   8073  code 47 child, DISTANCE 35   detail 8175 (47: VOLUME 60 / COST 120)   <- the duplicate
--   8074  code 48 child, DISTANCE 20   detail 8176 (48: VOLUME 100 / COST 500)
-- The served location id is 8072 (lowest). Owned SOLELY by
-- Schedule4WriteIT.put_edit_legacyFamilyWithoutPrimary_clearingItsCodeKeepsTheIdentityReport,
-- which sends 40 and 48 and omits 47: 8072 must SURVIVE with its fixed row and lose only its 47
-- detail, 8073 must go whole, 8074 must be untouched. Destructive, hence its own mill.
--
-- REPEATABLE (R__), data band, prefix 46: beside R__45 (mill 547, the same story's other fixture)
-- and below R__70 so the canonical submitter's set-based mill association covers mill 548.
--
-- PK ranges, verified unused across every migration here and in db-e2e: mill 548 (Schedule 4's
-- 540-552 neighbourhood; 547 is R__45), TRANSPORTATION_REPORT 8072-8074 (8070-8071 are R__45,
-- 8080+ V15/R__51), ILCR_COST_REPORT_DETAIL 8173-8176 (8170-8172 are R__45; below 9000, clear of
-- ILCR_COST_REPORT_DETAIL_SEQ). All below ILCR_REPORT_COMMON_SEQ's 9000 start.
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID)
  SELECT 548, 'Sch4 Legacy Family Milling', 548, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.MILL WHERE MILL_ID = 548);
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID)
  SELECT 548, 'ACT', 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_STATUS_XREF WHERE ILCR_MILL_STATUS_XREF_ID = 548);
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID)
  SELECT 2021, 548, 'D', 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_REPORT_STATUS WHERE REPORT_YEAR = 2021 AND ILCR_MILL_ID = 548);

-- 8072: the identity child (lowest id) -- code 47 plus the family's fixed 40 row.
INSERT INTO THE.TRANSPORTATION_REPORT (TRANSPORTATION_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION_DESCRIPTION, DISTANCE, TRANSPORTATION_CYCLE_TIME, REVISION_COUNT, ENTRY_USERID)
  SELECT 8072, 2021, 548, '4', 'Legacy Dump', 10, NULL, 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.TRANSPORTATION_REPORT WHERE TRANSPORTATION_REPORT_ID = 8072);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, TRANSPORTATION_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 8173, 8072, 47, 50, 100, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 8173);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, TRANSPORTATION_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 8174, 8072, 40, 400, 800, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 8174);
-- 8073: the duplicate code-47 child.
INSERT INTO THE.TRANSPORTATION_REPORT (TRANSPORTATION_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION_DESCRIPTION, DISTANCE, TRANSPORTATION_CYCLE_TIME, REVISION_COUNT, ENTRY_USERID)
  SELECT 8073, 2021, 548, '4', 'Legacy Dump', 35, NULL, 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.TRANSPORTATION_REPORT WHERE TRANSPORTATION_REPORT_ID = 8073);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, TRANSPORTATION_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 8175, 8073, 47, 60, 120, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 8175);
-- 8074: the code-48 child, kept by the test.
INSERT INTO THE.TRANSPORTATION_REPORT (TRANSPORTATION_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION_DESCRIPTION, DISTANCE, TRANSPORTATION_CYCLE_TIME, REVISION_COUNT, ENTRY_USERID)
  SELECT 8074, 2021, 548, '4', 'Legacy Dump', 20, NULL, 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.TRANSPORTATION_REPORT WHERE TRANSPORTATION_REPORT_ID = 8074);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, TRANSPORTATION_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 8176, 8074, 48, 100, 500, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 8176);
