-- Story 15.3 (UC-CHK-002) submit-gate fixtures: three Draft + all-ten-MET mills and one status-only
-- mill, all reporting year 2021, all ACT, Draft on BOTH tracks, REPORT_COMPLETED_IND 'N', and the eleven
-- ILCR_REPORT_CATEGORY rows at 'D' that the open-year path (ReportingYearService.CATEGORY_IDS) would have
-- written -- no other test migration seeds a single category row, and legacy NPEs without one.
--
-- Every Schedules 1-10 check is MET on 760/761/762 with the smallest document that passes:
--   Sch 1 = mill 528's complete document (V7:11-24): the thirteen checked items with VOLUME and/or COST
--           plus one item-19 Other-Costs row at VOLUME 0 (a zero-other-costs schedule passes);
--   Sch 2 = mill 621's item-25 cost (V10:50);
--   Sch 3 = mill 572's complete document (V18:38-59): harvest 1000 >= PO&P 500 per pair, volumes on 118/119;
--   Schedules 4-10 are vacuously MET with zero rows (their checks start met = true).
-- One mill per mutating test, because a submit moves the row D -> S:
--   760  CheckStatusSubmitIT            -- AC 1 happy path (submitted once, asserted per column)
--   761  CheckStatusSubmitConcurrencyIT -- AC 6 two racing submits, exactly one commits
--   762  CheckStatusSubmitIT            -- AC 7 rollback: the test deletes its category row '7' first
--   763  DraftGateLockIT                -- D8 (a'): status row + two EMPTY summaries, every converted gate blocks behind its lock
--
-- Prefix 55 is BELOW 70 so R__70's set-based insert associates the canonical submitter to all four mills.
-- This file also seeds the e2e database (same db/ chain + db-e2e/R__80), so these mills appear in the e2e
-- Home dropdown as "1760 Submit All Met Milling 2021" etc. MILL_NUMBER is 1760-1763, NOT 760-763: e2e mill
-- 9050 'WESTEROS' already carries MILL_NUMBER 760 (db-e2e/R__80:109) and the dropdown shows number + name.
--
-- Claims (verified free by grep over db/*.sql and db-e2e/*.sql on 2026-09-15): MILL / ILCR_MILL_STATUS_XREF
-- 760-763 (MILL_NUMBER 1760-1763), ILCR_REPORT_SUMMARY 1300-1310, ILCR_COST_REPORT_DETAIL 5600-5707 (block
-- 5600-5729 reserved). Every INSERT is guarded by WHERE NOT EXISTS on its key (the R__51 idiom) so a
-- checksum change re-applies cleanly; see README convention 1b for what that guard does and does not do.
-- ================================================================================================
-- Mill 760 -- Submit All Met Milling (MILL_NUMBER 1760). Summaries 1300-1302, details 5600-5635.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID)
  SELECT 760, 'Submit All Met Milling', 1760, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.MILL WHERE MILL_ID = 760);
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID)
  SELECT 760, 'ACT', 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_STATUS_XREF WHERE ILCR_MILL_STATUS_XREF_ID = 760);
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE,
                                         MILL_SILVICULTUR_STATUS_CODE, REPORT_COMPLETED_IND, REVISION_COUNT,
                                         ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 760, 'D', 'D', 'N', 0, 'SEED', SYSTIMESTAMP, 'SEED', SYSTIMESTAMP FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_REPORT_STATUS WHERE REPORT_YEAR = 2021 AND ILCR_MILL_ID = 760);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 760, c.ID, 'D', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE
    FROM (SELECT '1' ID FROM DUAL UNION ALL SELECT '2' FROM DUAL UNION ALL SELECT '3' FROM DUAL
          UNION ALL SELECT '4' FROM DUAL UNION ALL SELECT '5' FROM DUAL UNION ALL SELECT '6' FROM DUAL
          UNION ALL SELECT '7' FROM DUAL UNION ALL SELECT '8' FROM DUAL UNION ALL SELECT '9' FROM DUAL
          UNION ALL SELECT '10' FROM DUAL UNION ALL SELECT '11' FROM DUAL) c
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 760 AND r.ILCR_CATEGORY_ID = c.ID);
-- Schedule 1 (category '1'): the thirteen checked items plus the item-19 Other-Costs row at VOLUME 0.
INSERT INTO THE.ILCR_REPORT_SUMMARY (ILCR_REPORT_SUMMARY_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, REVISION_COUNT, ENTRY_USERID)
  SELECT 1300, 2021, 760, '1', 0, 'SEED' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_SUMMARY WHERE ILCR_REPORT_SUMMARY_ID = 1300);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT * FROM (
    SELECT 5600 DETAIL_ID, 1300 SUMMARY_ID, 12 ITEM_ID, 100 VOLUME, 500 COST, NULL ITEM_DESCRIPTION, 'SEED' ENTRY_USERID FROM DUAL UNION ALL
    SELECT 5601, 1300, 13, 100, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5602, 1300, 14, 100, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5603, 1300, 15, 100, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5604, 1300, 16, 100, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5605, 1300, 17, 100, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5606, 1300, 18, 100, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5607, 1300, 1, 100, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5608, 1300, 2, 100, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5609, 1300, 143, 100, NULL, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5610, 1300, 144, 100, NULL, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5611, 1300, 139, 100, NULL, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5612, 1300, 140, 100, NULL, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5613, 1300, 19, 0, NULL, NULL, 'SEED' FROM DUAL) d
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_REPORT_SUMMARY_ID = 1300);
-- Schedule 2 (category '2'): the one checked field, item-25 cost.
INSERT INTO THE.ILCR_REPORT_SUMMARY (ILCR_REPORT_SUMMARY_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, REVISION_COUNT, ENTRY_USERID)
  SELECT 1301, 2021, 760, '2', 0, 'SEED' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_SUMMARY WHERE ILCR_REPORT_SUMMARY_ID = 1301);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT * FROM (
    SELECT 5614 DETAIL_ID, 1301 SUMMARY_ID, 25 ITEM_ID, NULL VOLUME, 500000 COST, NULL ITEM_DESCRIPTION, 'SEED' ENTRY_USERID FROM DUAL) d
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_REPORT_SUMMARY_ID = 1301);
-- Schedule 3 (category '3'): eleven Harvest and eight PO&P costs (harvest 1000 >= PO&P 500), PO&P and Crown Timber volumes.
INSERT INTO THE.ILCR_REPORT_SUMMARY (ILCR_REPORT_SUMMARY_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, REVISION_COUNT, ENTRY_USERID)
  SELECT 1302, 2021, 760, '3', 0, 'SEED' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_SUMMARY WHERE ILCR_REPORT_SUMMARY_ID = 1302);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT * FROM (
    SELECT 5615 DETAIL_ID, 1302 SUMMARY_ID, 27 ITEM_ID, NULL VOLUME, 1000 COST, NULL ITEM_DESCRIPTION, 'SEED' ENTRY_USERID FROM DUAL UNION ALL
    SELECT 5616, 1302, 125, NULL, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5617, 1302, 28, NULL, 1000, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5618, 1302, 126, NULL, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5619, 1302, 29, NULL, 1000, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5620, 1302, 30, NULL, 1000, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5621, 1302, 128, NULL, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5622, 1302, 31, NULL, 1000, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5623, 1302, 129, NULL, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5624, 1302, 32, NULL, 1000, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5625, 1302, 130, NULL, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5626, 1302, 33, NULL, 1000, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5627, 1302, 34, NULL, 1000, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5628, 1302, 132, NULL, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5629, 1302, 35, NULL, 1000, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5630, 1302, 133, NULL, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5631, 1302, 36, NULL, 1000, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5632, 1302, 134, NULL, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5633, 1302, 37, NULL, 1000, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5634, 1302, 118, 1000, NULL, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5635, 1302, 119, 1000, NULL, NULL, 'SEED' FROM DUAL) d
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_REPORT_SUMMARY_ID = 1302);
-- ================================================================================================
-- Mill 761 -- Submit Racing Milling (MILL_NUMBER 1761). Summaries 1303-1305, details 5636-5671.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID)
  SELECT 761, 'Submit Racing Milling', 1761, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.MILL WHERE MILL_ID = 761);
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID)
  SELECT 761, 'ACT', 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_STATUS_XREF WHERE ILCR_MILL_STATUS_XREF_ID = 761);
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE,
                                         MILL_SILVICULTUR_STATUS_CODE, REPORT_COMPLETED_IND, REVISION_COUNT,
                                         ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 761, 'D', 'D', 'N', 0, 'SEED', SYSTIMESTAMP, 'SEED', SYSTIMESTAMP FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_REPORT_STATUS WHERE REPORT_YEAR = 2021 AND ILCR_MILL_ID = 761);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 761, c.ID, 'D', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE
    FROM (SELECT '1' ID FROM DUAL UNION ALL SELECT '2' FROM DUAL UNION ALL SELECT '3' FROM DUAL
          UNION ALL SELECT '4' FROM DUAL UNION ALL SELECT '5' FROM DUAL UNION ALL SELECT '6' FROM DUAL
          UNION ALL SELECT '7' FROM DUAL UNION ALL SELECT '8' FROM DUAL UNION ALL SELECT '9' FROM DUAL
          UNION ALL SELECT '10' FROM DUAL UNION ALL SELECT '11' FROM DUAL) c
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 761 AND r.ILCR_CATEGORY_ID = c.ID);
-- Schedule 1 (category '1'): the thirteen checked items plus the item-19 Other-Costs row at VOLUME 0.
INSERT INTO THE.ILCR_REPORT_SUMMARY (ILCR_REPORT_SUMMARY_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, REVISION_COUNT, ENTRY_USERID)
  SELECT 1303, 2021, 761, '1', 0, 'SEED' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_SUMMARY WHERE ILCR_REPORT_SUMMARY_ID = 1303);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT * FROM (
    SELECT 5636 DETAIL_ID, 1303 SUMMARY_ID, 12 ITEM_ID, 100 VOLUME, 500 COST, NULL ITEM_DESCRIPTION, 'SEED' ENTRY_USERID FROM DUAL UNION ALL
    SELECT 5637, 1303, 13, 100, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5638, 1303, 14, 100, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5639, 1303, 15, 100, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5640, 1303, 16, 100, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5641, 1303, 17, 100, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5642, 1303, 18, 100, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5643, 1303, 1, 100, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5644, 1303, 2, 100, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5645, 1303, 143, 100, NULL, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5646, 1303, 144, 100, NULL, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5647, 1303, 139, 100, NULL, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5648, 1303, 140, 100, NULL, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5649, 1303, 19, 0, NULL, NULL, 'SEED' FROM DUAL) d
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_REPORT_SUMMARY_ID = 1303);
-- Schedule 2 (category '2'): the one checked field, item-25 cost.
INSERT INTO THE.ILCR_REPORT_SUMMARY (ILCR_REPORT_SUMMARY_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, REVISION_COUNT, ENTRY_USERID)
  SELECT 1304, 2021, 761, '2', 0, 'SEED' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_SUMMARY WHERE ILCR_REPORT_SUMMARY_ID = 1304);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT * FROM (
    SELECT 5650 DETAIL_ID, 1304 SUMMARY_ID, 25 ITEM_ID, NULL VOLUME, 500000 COST, NULL ITEM_DESCRIPTION, 'SEED' ENTRY_USERID FROM DUAL) d
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_REPORT_SUMMARY_ID = 1304);
-- Schedule 3 (category '3'): eleven Harvest and eight PO&P costs (harvest 1000 >= PO&P 500), PO&P and Crown Timber volumes.
INSERT INTO THE.ILCR_REPORT_SUMMARY (ILCR_REPORT_SUMMARY_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, REVISION_COUNT, ENTRY_USERID)
  SELECT 1305, 2021, 761, '3', 0, 'SEED' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_SUMMARY WHERE ILCR_REPORT_SUMMARY_ID = 1305);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT * FROM (
    SELECT 5651 DETAIL_ID, 1305 SUMMARY_ID, 27 ITEM_ID, NULL VOLUME, 1000 COST, NULL ITEM_DESCRIPTION, 'SEED' ENTRY_USERID FROM DUAL UNION ALL
    SELECT 5652, 1305, 125, NULL, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5653, 1305, 28, NULL, 1000, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5654, 1305, 126, NULL, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5655, 1305, 29, NULL, 1000, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5656, 1305, 30, NULL, 1000, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5657, 1305, 128, NULL, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5658, 1305, 31, NULL, 1000, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5659, 1305, 129, NULL, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5660, 1305, 32, NULL, 1000, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5661, 1305, 130, NULL, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5662, 1305, 33, NULL, 1000, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5663, 1305, 34, NULL, 1000, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5664, 1305, 132, NULL, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5665, 1305, 35, NULL, 1000, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5666, 1305, 133, NULL, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5667, 1305, 36, NULL, 1000, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5668, 1305, 134, NULL, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5669, 1305, 37, NULL, 1000, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5670, 1305, 118, 1000, NULL, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5671, 1305, 119, 1000, NULL, NULL, 'SEED' FROM DUAL) d
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_REPORT_SUMMARY_ID = 1305);
-- ================================================================================================
-- Mill 762 -- Submit Rollback Milling (MILL_NUMBER 1762). Summaries 1306-1308, details 5672-5707.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID)
  SELECT 762, 'Submit Rollback Milling', 1762, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.MILL WHERE MILL_ID = 762);
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID)
  SELECT 762, 'ACT', 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_STATUS_XREF WHERE ILCR_MILL_STATUS_XREF_ID = 762);
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE,
                                         MILL_SILVICULTUR_STATUS_CODE, REPORT_COMPLETED_IND, REVISION_COUNT,
                                         ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 762, 'D', 'D', 'N', 0, 'SEED', SYSTIMESTAMP, 'SEED', SYSTIMESTAMP FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_REPORT_STATUS WHERE REPORT_YEAR = 2021 AND ILCR_MILL_ID = 762);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 762, c.ID, 'D', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE
    FROM (SELECT '1' ID FROM DUAL UNION ALL SELECT '2' FROM DUAL UNION ALL SELECT '3' FROM DUAL
          UNION ALL SELECT '4' FROM DUAL UNION ALL SELECT '5' FROM DUAL UNION ALL SELECT '6' FROM DUAL
          UNION ALL SELECT '7' FROM DUAL UNION ALL SELECT '8' FROM DUAL UNION ALL SELECT '9' FROM DUAL
          UNION ALL SELECT '10' FROM DUAL UNION ALL SELECT '11' FROM DUAL) c
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 762 AND r.ILCR_CATEGORY_ID = c.ID);
-- Schedule 1 (category '1'): the thirteen checked items plus the item-19 Other-Costs row at VOLUME 0.
INSERT INTO THE.ILCR_REPORT_SUMMARY (ILCR_REPORT_SUMMARY_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, REVISION_COUNT, ENTRY_USERID)
  SELECT 1306, 2021, 762, '1', 0, 'SEED' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_SUMMARY WHERE ILCR_REPORT_SUMMARY_ID = 1306);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT * FROM (
    SELECT 5672 DETAIL_ID, 1306 SUMMARY_ID, 12 ITEM_ID, 100 VOLUME, 500 COST, NULL ITEM_DESCRIPTION, 'SEED' ENTRY_USERID FROM DUAL UNION ALL
    SELECT 5673, 1306, 13, 100, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5674, 1306, 14, 100, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5675, 1306, 15, 100, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5676, 1306, 16, 100, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5677, 1306, 17, 100, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5678, 1306, 18, 100, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5679, 1306, 1, 100, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5680, 1306, 2, 100, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5681, 1306, 143, 100, NULL, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5682, 1306, 144, 100, NULL, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5683, 1306, 139, 100, NULL, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5684, 1306, 140, 100, NULL, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5685, 1306, 19, 0, NULL, NULL, 'SEED' FROM DUAL) d
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_REPORT_SUMMARY_ID = 1306);
-- Schedule 2 (category '2'): the one checked field, item-25 cost.
INSERT INTO THE.ILCR_REPORT_SUMMARY (ILCR_REPORT_SUMMARY_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, REVISION_COUNT, ENTRY_USERID)
  SELECT 1307, 2021, 762, '2', 0, 'SEED' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_SUMMARY WHERE ILCR_REPORT_SUMMARY_ID = 1307);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT * FROM (
    SELECT 5686 DETAIL_ID, 1307 SUMMARY_ID, 25 ITEM_ID, NULL VOLUME, 500000 COST, NULL ITEM_DESCRIPTION, 'SEED' ENTRY_USERID FROM DUAL) d
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_REPORT_SUMMARY_ID = 1307);
-- Schedule 3 (category '3'): eleven Harvest and eight PO&P costs (harvest 1000 >= PO&P 500), PO&P and Crown Timber volumes.
INSERT INTO THE.ILCR_REPORT_SUMMARY (ILCR_REPORT_SUMMARY_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, REVISION_COUNT, ENTRY_USERID)
  SELECT 1308, 2021, 762, '3', 0, 'SEED' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_SUMMARY WHERE ILCR_REPORT_SUMMARY_ID = 1308);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT * FROM (
    SELECT 5687 DETAIL_ID, 1308 SUMMARY_ID, 27 ITEM_ID, NULL VOLUME, 1000 COST, NULL ITEM_DESCRIPTION, 'SEED' ENTRY_USERID FROM DUAL UNION ALL
    SELECT 5688, 1308, 125, NULL, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5689, 1308, 28, NULL, 1000, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5690, 1308, 126, NULL, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5691, 1308, 29, NULL, 1000, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5692, 1308, 30, NULL, 1000, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5693, 1308, 128, NULL, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5694, 1308, 31, NULL, 1000, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5695, 1308, 129, NULL, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5696, 1308, 32, NULL, 1000, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5697, 1308, 130, NULL, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5698, 1308, 33, NULL, 1000, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5699, 1308, 34, NULL, 1000, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5700, 1308, 132, NULL, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5701, 1308, 35, NULL, 1000, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5702, 1308, 133, NULL, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5703, 1308, 36, NULL, 1000, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5704, 1308, 134, NULL, 500, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5705, 1308, 37, NULL, 1000, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5706, 1308, 118, 1000, NULL, NULL, 'SEED' FROM DUAL UNION ALL
    SELECT 5707, 1308, 119, 1000, NULL, NULL, 'SEED' FROM DUAL) d
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_REPORT_SUMMARY_ID = 1308);
-- ================================================================================================
-- Mill 763 -- Draft Gate Lock Milling (MILL_NUMBER 1763). Status row, category rows and two EMPTY summaries: the Draft-gate
-- lock IT needs a Draft mill whose status it can flip to 'S' behind a held row lock and restore, and no
-- cost details at all (every converted gate is exercised through a DELETE of an id that does not exist). The
-- category '1' and '3' summaries exist because the Schedule 1/3 sub-resource controllers guard on a summary
-- (validateScheduleViewable) BEFORE the service's gate runs; without them those routes 404 ahead of the lock.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID)
  SELECT 763, 'Draft Gate Lock Milling', 1763, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.MILL WHERE MILL_ID = 763);
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID)
  SELECT 763, 'ACT', 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_STATUS_XREF WHERE ILCR_MILL_STATUS_XREF_ID = 763);
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE,
                                         MILL_SILVICULTUR_STATUS_CODE, REPORT_COMPLETED_IND, REVISION_COUNT,
                                         ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 763, 'D', 'D', 'N', 0, 'SEED', SYSTIMESTAMP, 'SEED', SYSTIMESTAMP FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_REPORT_STATUS WHERE REPORT_YEAR = 2021 AND ILCR_MILL_ID = 763);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 763, c.ID, 'D', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE
    FROM (SELECT '1' ID FROM DUAL UNION ALL SELECT '2' FROM DUAL UNION ALL SELECT '3' FROM DUAL
          UNION ALL SELECT '4' FROM DUAL UNION ALL SELECT '5' FROM DUAL UNION ALL SELECT '6' FROM DUAL
          UNION ALL SELECT '7' FROM DUAL UNION ALL SELECT '8' FROM DUAL UNION ALL SELECT '9' FROM DUAL
          UNION ALL SELECT '10' FROM DUAL UNION ALL SELECT '11' FROM DUAL) c
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 763 AND r.ILCR_CATEGORY_ID = c.ID);
INSERT INTO THE.ILCR_REPORT_SUMMARY (ILCR_REPORT_SUMMARY_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, REVISION_COUNT, ENTRY_USERID)
  SELECT 1309, 2021, 763, '1', 0, 'SEED' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_SUMMARY WHERE ILCR_REPORT_SUMMARY_ID = 1309);
INSERT INTO THE.ILCR_REPORT_SUMMARY (ILCR_REPORT_SUMMARY_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, REVISION_COUNT, ENTRY_USERID)
  SELECT 1310, 2021, 763, '3', 0, 'SEED' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_SUMMARY WHERE ILCR_REPORT_SUMMARY_ID = 1310);
