-- Story 26.1 (UC-CHK-003) Schedule 11 submit fixtures: six mill/years, all reporting year 2021, all ACT,
-- REPORT_COMPLETED_IND 'N'. Each carries the ILCR_REPORT_CATEGORY rows the open-year path writes (every
-- mill but 787 has all eleven), with each category's state consistent with its track's status (1-10 at S
-- -> categories '1'..'10' at 'A'; silviculture at S -> '11' at 'A').
--
-- THE TWO TRACK CODES DIFFER on 784 and 786 on purpose (Story 18.1 AC 11 pattern): a fixture whose two
-- codes are equal cannot tell a Schedule 11 statement from a Schedules 1-10 one.
--
-- Schedule 11 is MET when every location has BOTH an Actual (item 24) and a Planned (item 23) cost
-- (Schedule11Service.checkStatus; legacy Schedule11CheckStatus.java:8-31); zero locations is vacuously MET
-- (:19). Schedules 1-10 carry data on 784 only (one Schedule 2 summary): nothing here submits that track, and
-- the row exists to catch a Schedule 11 submit that stamps it.
--   784  Schedule11SubmitIT             -- AC 1 happy path: silviculture D, 1-10 S; two met locations
--   785  Schedule11SubmitIT             -- AC 2 gate fails: one location whose Planned Cost is NULL (never written)
--   786  Schedule11SubmitIT             -- AC 5 not Draft: silviculture S, 1-10 D (never written)
--   787  Schedule11SubmitIT             -- AC 5 rollback: silviculture D, met, NO category '11' row
--   788  Schedule11SubmitConcurrencyIT  -- AC 5 two racing submits, exactly one commits
--   789  Schedule11SubmitIT             -- AC 2/8 vacuous MET: silviculture D + 1-10 D, zero locations
--
-- Prefix 57 is BELOW 70 so R__70's set-based insert associates the canonical submitter to all six mills.
-- This file also seeds the e2e database (same db/ chain + db-e2e/R__80), so these mills appear in the e2e
-- Home dropdown as "1784 Sch11 Submit Happy Milling" etc.
--
-- Claims (verified free by grep over db/*.sql and db-e2e/*.sql on 2026-09-24): MILL / ILCR_MILL_STATUS_XREF
-- 784-789 (MILL_NUMBER 1784-1789), BASIC_SILVICULTURE_REPORT 9411-9416 (below ILCR_REPORT_COMMON_SEQ's 9500
-- start, clear of R__50's 9401-9402 and the db-e2e seed's 9351-9399), ILCR_REPORT_SUMMARY 1680, ILCR_COST_REPORT_DETAIL 5800-5812 (block 5800-5829 reserved; below the 9000 floor the
-- README keeps clear of ILCR_COST_REPORT_DETAIL_SEQ). Every INSERT is the single-row
-- `(cols) SELECT ... FROM DUAL WHERE NOT EXISTS` form guarded on its key (README convention 1b).
-- ================================================================================================
-- Mill 784 -- Sch11 Submit Happy Milling (MILL_NUMBER 1784). 1-10 at S, silviculture at D.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID)
  SELECT 784, 'Sch11 Submit Happy Milling', 1784, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.MILL WHERE MILL_ID = 784);
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID)
  SELECT 784, 'ACT', 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_STATUS_XREF WHERE ILCR_MILL_STATUS_XREF_ID = 784);
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE,
                                         MILL_SILVICULTUR_STATUS_CODE, REPORT_COMPLETED_IND, REVISION_COUNT,
                                         ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 784, 'S', 'D', 'N', 0, 'SEED', SYSTIMESTAMP, 'SEED', SYSTIMESTAMP FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_REPORT_STATUS WHERE REPORT_YEAR = 2021 AND ILCR_MILL_ID = 784);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 784, c.ID, 'A', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE
    FROM (SELECT '1' ID FROM DUAL UNION ALL SELECT '2' FROM DUAL UNION ALL SELECT '3' FROM DUAL
          UNION ALL SELECT '4' FROM DUAL UNION ALL SELECT '5' FROM DUAL UNION ALL SELECT '6' FROM DUAL
          UNION ALL SELECT '7' FROM DUAL UNION ALL SELECT '8' FROM DUAL UNION ALL SELECT '9' FROM DUAL
          UNION ALL SELECT '10' FROM DUAL) c
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 784 AND r.ILCR_CATEGORY_ID = c.ID);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 784, '11', 'D', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 784 AND r.ILCR_CATEGORY_ID = '11');
INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID)
  SELECT 9411, 2021, 784, '11', 'Happy Block North', 8801, 12.5, 'N', NULL, 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.BASIC_SILVICULTURE_REPORT WHERE BASIC_SILVICULTURE_REPORT_ID = 9411);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5800, NULL, 9411, 24, NULL, 25000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5800);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5801, NULL, 9411, 23, NULL, 20000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5801);
INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID)
  SELECT 9412, 2021, 784, '11', 'Happy Block South', 8802, 7.25, 'N', NULL, 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.BASIC_SILVICULTURE_REPORT WHERE BASIC_SILVICULTURE_REPORT_ID = 9412);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5802, NULL, 9412, 24, NULL, 14000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5802);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5803, NULL, 9412, 23, NULL, 15000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5803);
-- ONE Schedules 1-10 row family on 784 — a Schedule 2 summary and its item-25 cost — seeded only so a
-- Schedule 11 submit that also ran the ten 1-10 audit touches has a row to stamp, and the IT can see it.
INSERT INTO THE.ILCR_REPORT_SUMMARY (ILCR_REPORT_SUMMARY_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, REVISION_COUNT, ENTRY_USERID)
  SELECT 1680, 2021, 784, '2', 0, 'SEED' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_SUMMARY WHERE ILCR_REPORT_SUMMARY_ID = 1680);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5811, 1680, 25, NULL, 500000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5811);
-- ================================================================================================
-- Mill 785 -- Sch11 Submit Failing Milling (MILL_NUMBER 1785). 1-10 at D, silviculture at D.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID)
  SELECT 785, 'Sch11 Submit Failing Milling', 1785, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.MILL WHERE MILL_ID = 785);
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID)
  SELECT 785, 'ACT', 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_STATUS_XREF WHERE ILCR_MILL_STATUS_XREF_ID = 785);
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE,
                                         MILL_SILVICULTUR_STATUS_CODE, REPORT_COMPLETED_IND, REVISION_COUNT,
                                         ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 785, 'D', 'D', 'N', 0, 'SEED', SYSTIMESTAMP, 'SEED', SYSTIMESTAMP FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_REPORT_STATUS WHERE REPORT_YEAR = 2021 AND ILCR_MILL_ID = 785);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 785, c.ID, 'D', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE
    FROM (SELECT '1' ID FROM DUAL UNION ALL SELECT '2' FROM DUAL UNION ALL SELECT '3' FROM DUAL
          UNION ALL SELECT '4' FROM DUAL UNION ALL SELECT '5' FROM DUAL UNION ALL SELECT '6' FROM DUAL
          UNION ALL SELECT '7' FROM DUAL UNION ALL SELECT '8' FROM DUAL UNION ALL SELECT '9' FROM DUAL
          UNION ALL SELECT '10' FROM DUAL) c
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 785 AND r.ILCR_CATEGORY_ID = c.ID);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 785, '11', 'D', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 785 AND r.ILCR_CATEGORY_ID = '11');
INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID)
  SELECT 9413, 2021, 785, '11', 'Unplanned Block', 8801, 9, 'N', NULL, 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.BASIC_SILVICULTURE_REPORT WHERE BASIC_SILVICULTURE_REPORT_ID = 9413);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5804, NULL, 9413, 24, NULL, 18000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5804);
-- The Planned Cost (item 23) row EXISTS with COST NULL — the "value blanked" shape, distinct from a missing
-- row; the check reads both as missing: 'location  : Unplanned Block - Planned cost: Value Required'.
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5812, NULL, 9413, 23, NULL, NULL, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5812);
-- ================================================================================================
-- Mill 786 -- Sch11 Already Submitted Milling (MILL_NUMBER 1786). 1-10 at D, silviculture at S.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID)
  SELECT 786, 'Sch11 Already Submitted Milling', 1786, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.MILL WHERE MILL_ID = 786);
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID)
  SELECT 786, 'ACT', 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_STATUS_XREF WHERE ILCR_MILL_STATUS_XREF_ID = 786);
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE,
                                         MILL_SILVICULTUR_STATUS_CODE, REPORT_COMPLETED_IND, REVISION_COUNT,
                                         ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 786, 'D', 'S', 'N', 0, 'SEED', SYSTIMESTAMP, 'SEED', SYSTIMESTAMP FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_REPORT_STATUS WHERE REPORT_YEAR = 2021 AND ILCR_MILL_ID = 786);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 786, c.ID, 'D', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE
    FROM (SELECT '1' ID FROM DUAL UNION ALL SELECT '2' FROM DUAL UNION ALL SELECT '3' FROM DUAL
          UNION ALL SELECT '4' FROM DUAL UNION ALL SELECT '5' FROM DUAL UNION ALL SELECT '6' FROM DUAL
          UNION ALL SELECT '7' FROM DUAL UNION ALL SELECT '8' FROM DUAL UNION ALL SELECT '9' FROM DUAL
          UNION ALL SELECT '10' FROM DUAL) c
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 786 AND r.ILCR_CATEGORY_ID = c.ID);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 786, '11', 'A', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 786 AND r.ILCR_CATEGORY_ID = '11');
INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID)
  SELECT 9414, 2021, 786, '11', 'Already Sent Block', 8801, 4, 'N', NULL, 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.BASIC_SILVICULTURE_REPORT WHERE BASIC_SILVICULTURE_REPORT_ID = 9414);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5805, NULL, 9414, 24, NULL, 5000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5805);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5806, NULL, 9414, 23, NULL, 5000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5806);
-- ================================================================================================
-- Mill 787 -- Sch11 Submit Rollback Milling (MILL_NUMBER 1787). 1-10 at D, silviculture at D.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID)
  SELECT 787, 'Sch11 Submit Rollback Milling', 1787, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.MILL WHERE MILL_ID = 787);
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID)
  SELECT 787, 'ACT', 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_STATUS_XREF WHERE ILCR_MILL_STATUS_XREF_ID = 787);
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE,
                                         MILL_SILVICULTUR_STATUS_CODE, REPORT_COMPLETED_IND, REVISION_COUNT,
                                         ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 787, 'D', 'D', 'N', 0, 'SEED', SYSTIMESTAMP, 'SEED', SYSTIMESTAMP FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_REPORT_STATUS WHERE REPORT_YEAR = 2021 AND ILCR_MILL_ID = 787);
-- NO category '11' row: the Schedule 11 category advance affects 0 rows and the submit must roll back.
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 787, c.ID, 'D', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE
    FROM (SELECT '1' ID FROM DUAL UNION ALL SELECT '2' FROM DUAL UNION ALL SELECT '3' FROM DUAL
          UNION ALL SELECT '4' FROM DUAL UNION ALL SELECT '5' FROM DUAL UNION ALL SELECT '6' FROM DUAL
          UNION ALL SELECT '7' FROM DUAL UNION ALL SELECT '8' FROM DUAL UNION ALL SELECT '9' FROM DUAL
          UNION ALL SELECT '10' FROM DUAL) c
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 787 AND r.ILCR_CATEGORY_ID = c.ID);
INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID)
  SELECT 9415, 2021, 787, '11', 'Rollback Block', 8801, 6, 'N', NULL, 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.BASIC_SILVICULTURE_REPORT WHERE BASIC_SILVICULTURE_REPORT_ID = 9415);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5807, NULL, 9415, 24, NULL, 6000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5807);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5808, NULL, 9415, 23, NULL, 6000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5808);
-- ================================================================================================
-- Mill 788 -- Sch11 Submit Racing Milling (MILL_NUMBER 1788). 1-10 at D, silviculture at D.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID)
  SELECT 788, 'Sch11 Submit Racing Milling', 1788, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.MILL WHERE MILL_ID = 788);
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID)
  SELECT 788, 'ACT', 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_STATUS_XREF WHERE ILCR_MILL_STATUS_XREF_ID = 788);
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE,
                                         MILL_SILVICULTUR_STATUS_CODE, REPORT_COMPLETED_IND, REVISION_COUNT,
                                         ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 788, 'D', 'D', 'N', 0, 'SEED', SYSTIMESTAMP, 'SEED', SYSTIMESTAMP FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_REPORT_STATUS WHERE REPORT_YEAR = 2021 AND ILCR_MILL_ID = 788);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 788, c.ID, 'D', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE
    FROM (SELECT '1' ID FROM DUAL UNION ALL SELECT '2' FROM DUAL UNION ALL SELECT '3' FROM DUAL
          UNION ALL SELECT '4' FROM DUAL UNION ALL SELECT '5' FROM DUAL UNION ALL SELECT '6' FROM DUAL
          UNION ALL SELECT '7' FROM DUAL UNION ALL SELECT '8' FROM DUAL UNION ALL SELECT '9' FROM DUAL
          UNION ALL SELECT '10' FROM DUAL) c
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 788 AND r.ILCR_CATEGORY_ID = c.ID);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 788, '11', 'D', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 788 AND r.ILCR_CATEGORY_ID = '11');
INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID)
  SELECT 9416, 2021, 788, '11', 'Racing Block', 8801, 3, 'N', NULL, 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.BASIC_SILVICULTURE_REPORT WHERE BASIC_SILVICULTURE_REPORT_ID = 9416);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5809, NULL, 9416, 24, NULL, 3000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5809);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5810, NULL, 9416, 23, NULL, 3000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5810);
-- ================================================================================================
-- Mill 789 -- Sch11 No Locations Milling (MILL_NUMBER 1789). 1-10 at D, silviculture at D.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID)
  SELECT 789, 'Sch11 No Locations Milling', 1789, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.MILL WHERE MILL_ID = 789);
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID)
  SELECT 789, 'ACT', 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_STATUS_XREF WHERE ILCR_MILL_STATUS_XREF_ID = 789);
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE,
                                         MILL_SILVICULTUR_STATUS_CODE, REPORT_COMPLETED_IND, REVISION_COUNT,
                                         ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 789, 'D', 'D', 'N', 0, 'SEED', SYSTIMESTAMP, 'SEED', SYSTIMESTAMP FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_REPORT_STATUS WHERE REPORT_YEAR = 2021 AND ILCR_MILL_ID = 789);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 789, c.ID, 'D', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE
    FROM (SELECT '1' ID FROM DUAL UNION ALL SELECT '2' FROM DUAL UNION ALL SELECT '3' FROM DUAL
          UNION ALL SELECT '4' FROM DUAL UNION ALL SELECT '5' FROM DUAL UNION ALL SELECT '6' FROM DUAL
          UNION ALL SELECT '7' FROM DUAL UNION ALL SELECT '8' FROM DUAL UNION ALL SELECT '9' FROM DUAL
          UNION ALL SELECT '10' FROM DUAL) c
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 789 AND r.ILCR_CATEGORY_ID = c.ID);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 789, '11', 'D', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 789 AND r.ILCR_CATEGORY_ID = '11');
-- Zero Schedule 11 locations: vacuously MET, legacy parity (Schedule11CheckStatus.java:19).
