-- Story 26.3 (UC-CHK-008/013) Schedule 11 verify fixtures: nine mill/years, all reporting year 2021, all ACT,
-- REPORT_COMPLETED_IND 'N'. Each carries the ILCR_REPORT_CATEGORY rows its tracks' statuses imply (1-10 at D ->
-- categories '1'..'10' at 'D', at S -> 'A'; silviculture at S -> '11' at 'A', at V -> 'V', at D -> 'D').
--
-- THE TWO TRACK CODES DIFFER wherever a Schedule 11 verify succeeds (807: 1-10 D / silviculture S), so a statement
-- naming the wrong status column fails a test rather than passing by coincidence. 813 and 815 are S/S on purpose:
-- delivery has real S/S rows (15-3 population note), and they are the shape on which BOTH verifies are offered.
--
-- Schedule 11 is MET when every location has BOTH an Actual (item 24) and a Planned (item 23) cost; zero locations
-- is vacuously MET (legacy Schedule11CheckStatus.java:19).
--   807  Schedule11VerifyIT             -- AC 1 happy path: silviculture S, 1-10 D; two met locations; the new admin
--                                           is xref'd here; a PRE-EXISTING AUDITOR pair differing in BOTH halves,
--                                           (813, OLDAUDITOR), set by an UPDATE after 813's xref (overwritten, D1)
--                                           and a LICENSEE pair (never touched); one 1-10 summary + cost detail
--   808  Schedule11VerifyIT             -- AC 2 gate fails: the Planned Cost row exists with COST NULL (never written)
--   809  Schedule11VerifyIT             -- AC 5 D->V jump refused (never written)
--   810  Schedule11VerifyIT             -- AC 5 V->V no-op refused (never written)
--   811  Schedule11VerifyIT             -- AC 5 rollback: silviculture S, met, NO category '11' row
--   812  Schedule11VerifyConcurrencyIT  -- AC 5 two racing verifies, exactly one commits
--   813  Schedule11VerifyIT             -- AC 1/D1 NULL auditor: S/S, the admin has NO xref here, and a PRE-EXISTING
--                                           AUDITOR pair is erased to NULL (legacy's erase path)
--   814  Schedule11VerifyIT             -- AC 2 vacuous MET: silviculture S, zero locations
--   815  Schedule11VerifyIT             -- AC 7(b): S/S with an all-met Schedules 1-10 gate; a 1-10 VERIFY here must
--                                           leave silviculture at S, category '11' at 'A' and its location unstamped
--
-- Prefix 59 is BELOW 70 so R__70's set-based insert associates the canonical submitter to all nine mills (the
-- SUBMITTER 403 arm then fails for lacking the action, not for being out of scope).
--
-- Claims (verified free by grep over db/, db-e2e/ and the test sources on 2026-09-25, bare ids): MILL /
-- ILCR_MILL_STATUS_XREF 807-815 (MILL_NUMBER 1807-1815), BASIC_SILVICULTURE_REPORT 9431-9440 (below
-- ILCR_REPORT_COMMON_SEQ's 9500), ILCR_REPORT_SUMMARY 1681-1684, ILCR_COST_REPORT_DETAIL 5846-5869 (the Schedule 11
-- rows and 807's 1-10 row) and 5750-5785 (815's Schedule 1-3 all-met set, copied from R__55's mill 764; 5730-5799
-- is otherwise empty), all below the 9000 floor the README keeps clear of ILCR_COST_REPORT_DETAIL_SEQ. ILCR_USER
-- VERIFY11ADMIN000111122223333AAA1 (the acting admin), VERIFY11OLDAUDITOR00011112222AA1 (the pre-existing auditor) and
-- VERIFY11LICENSEE000111122223AA11 (the pre-existing licensee). Every INSERT is the single-row
-- `(cols) SELECT ... FROM DUAL WHERE NOT EXISTS` form guarded on its key (README convention 1b).
-- ================================================================================================
-- The three directory users. ADMIN is the acting administrator (xref'd to 807 only, so 813 exercises the
-- no-xref NULL branch); the other two exist only to give the status rows a recorded pair to overwrite or keep.
-- ================================================================================================
INSERT INTO THE.ILCR_USER (USER_GUID, ILCR_ROLE_NAME, ACTIVE_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                           UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 'VERIFY11ADMIN000111122223333AAA1', 'ADMIN', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_USER WHERE USER_GUID = 'VERIFY11ADMIN000111122223333AAA1');
INSERT INTO THE.ILCR_USER (USER_GUID, ILCR_ROLE_NAME, ACTIVE_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                           UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 'VERIFY11OLDAUDITOR00011112222AA1', 'ADMIN', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_USER WHERE USER_GUID = 'VERIFY11OLDAUDITOR00011112222AA1');
INSERT INTO THE.ILCR_USER (USER_GUID, ILCR_ROLE_NAME, ACTIVE_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                           UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 'VERIFY11LICENSEE000111122223AA11', 'LICENSEE', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_USER WHERE USER_GUID = 'VERIFY11LICENSEE000111122223AA11');
-- ================================================================================================
-- Mill 807 -- Sch11 Verify Happy Milling (MILL_NUMBER 1807). 1-10 at D, silviculture at S.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID)
  SELECT 807, 'Sch11 Verify Happy Milling', 1807, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.MILL WHERE MILL_ID = 807);
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID)
  SELECT 807, 'ACT', 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_STATUS_XREF WHERE ILCR_MILL_STATUS_XREF_ID = 807);
INSERT INTO THE.ILCR_MILL_USER_XREF (ILCR_MILL_ID, USER_GUID, ACTIVE_DATE, INACTIVE_DATE, REVISION_COUNT,
                                     ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 807, 'VERIFY11LICENSEE000111122223AA11', SYSDATE, NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_USER_XREF WHERE ILCR_MILL_ID = 807 AND USER_GUID = 'VERIFY11LICENSEE000111122223AA11');
INSERT INTO THE.ILCR_MILL_USER_XREF (ILCR_MILL_ID, USER_GUID, ACTIVE_DATE, INACTIVE_DATE, REVISION_COUNT,
                                     ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 807, 'VERIFY11OLDAUDITOR00011112222AA1', SYSDATE, NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_USER_XREF WHERE ILCR_MILL_ID = 807 AND USER_GUID = 'VERIFY11OLDAUDITOR00011112222AA1');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE,
                                         MILL_SILVICULTUR_STATUS_CODE, REPORT_COMPLETED_IND, REVISION_COUNT,
                                         AUDITOR_MILL_ID, AUDITOR_USER_GUID, LICENSEE_MILL_ID,
                                         LICENSEE_USER_GUID, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID,
                                         UPDATE_TIMESTAMP)
  SELECT 2021, 807, 'D', 'S', 'N', 0, 807, 'VERIFY11OLDAUDITOR00011112222AA1', 807, 'VERIFY11LICENSEE000111122223AA11',
         'SEED', SYSTIMESTAMP, 'SEED', SYSTIMESTAMP FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_REPORT_STATUS WHERE REPORT_YEAR = 2021 AND ILCR_MILL_ID = 807);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 807, c.ID, 'D', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE
    FROM (SELECT '1' ID FROM DUAL UNION ALL SELECT '2' FROM DUAL UNION ALL SELECT '3' FROM DUAL
          UNION ALL SELECT '4' FROM DUAL UNION ALL SELECT '5' FROM DUAL UNION ALL SELECT '6' FROM DUAL
          UNION ALL SELECT '7' FROM DUAL UNION ALL SELECT '8' FROM DUAL UNION ALL SELECT '9' FROM DUAL
          UNION ALL SELECT '10' FROM DUAL) c
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 807 AND r.ILCR_CATEGORY_ID = c.ID);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 807, '11', 'A', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 807 AND r.ILCR_CATEGORY_ID = '11');
-- The acting admin's assignment for 807: without it the positive arm would silently re-test the NULL branch.
INSERT INTO THE.ILCR_MILL_USER_XREF (ILCR_MILL_ID, USER_GUID, ACTIVE_DATE, INACTIVE_DATE, REVISION_COUNT,
                                     ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 807, 'VERIFY11ADMIN000111122223333AAA1', SYSDATE, NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_USER_XREF WHERE ILCR_MILL_ID = 807 AND USER_GUID = 'VERIFY11ADMIN000111122223333AAA1');
INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID)
  SELECT 9431, 2021, 807, '11', 'Verify Block North', 8801, 5, 'N', NULL, 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.BASIC_SILVICULTURE_REPORT WHERE BASIC_SILVICULTURE_REPORT_ID = 9431);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5846, NULL, 9431, 24, NULL, 25000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5846);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5847, NULL, 9431, 23, NULL, 20000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5847);
INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID)
  SELECT 9432, 2021, 807, '11', 'Verify Block South', 8801, 5, 'N', NULL, 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.BASIC_SILVICULTURE_REPORT WHERE BASIC_SILVICULTURE_REPORT_ID = 9432);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5848, NULL, 9432, 24, NULL, 14000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5848);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5849, NULL, 9432, 23, NULL, 15000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5849);
-- ONE Schedules 1-10 row family on 807 -- a Schedule 2 summary and its item-25 cost -- seeded only so a
-- Schedule 11 verify that also ran the twenty 1-10 audit touches has a row to stamp, and the IT can see it.
INSERT INTO THE.ILCR_REPORT_SUMMARY (ILCR_REPORT_SUMMARY_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, REVISION_COUNT, ENTRY_USERID)
  SELECT 1684, 2021, 807, '2', 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_SUMMARY WHERE ILCR_REPORT_SUMMARY_ID = 1684);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5864, 1684, 25, NULL, 500000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5864);
-- ================================================================================================
-- Mill 808 -- Sch11 Verify Failing Milling (MILL_NUMBER 1808). 1-10 at D, silviculture at S.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID)
  SELECT 808, 'Sch11 Verify Failing Milling', 1808, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.MILL WHERE MILL_ID = 808);
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID)
  SELECT 808, 'ACT', 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_STATUS_XREF WHERE ILCR_MILL_STATUS_XREF_ID = 808);
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE,
                                         MILL_SILVICULTUR_STATUS_CODE, REPORT_COMPLETED_IND, REVISION_COUNT,
                                         AUDITOR_MILL_ID, AUDITOR_USER_GUID, LICENSEE_MILL_ID,
                                         LICENSEE_USER_GUID, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID,
                                         UPDATE_TIMESTAMP)
  SELECT 2021, 808, 'D', 'S', 'N', 0, NULL, NULL, NULL, NULL,
         'SEED', SYSTIMESTAMP, 'SEED', SYSTIMESTAMP FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_REPORT_STATUS WHERE REPORT_YEAR = 2021 AND ILCR_MILL_ID = 808);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 808, c.ID, 'D', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE
    FROM (SELECT '1' ID FROM DUAL UNION ALL SELECT '2' FROM DUAL UNION ALL SELECT '3' FROM DUAL
          UNION ALL SELECT '4' FROM DUAL UNION ALL SELECT '5' FROM DUAL UNION ALL SELECT '6' FROM DUAL
          UNION ALL SELECT '7' FROM DUAL UNION ALL SELECT '8' FROM DUAL UNION ALL SELECT '9' FROM DUAL
          UNION ALL SELECT '10' FROM DUAL) c
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 808 AND r.ILCR_CATEGORY_ID = c.ID);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 808, '11', 'A', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 808 AND r.ILCR_CATEGORY_ID = '11');
-- The Planned Cost (item 23) row EXISTS with COST NULL -- the real 'value blanked' shape; the check reads it as
-- missing: 'location  : Unfinished Block - Planned cost: Value Required' (the double space is legacy's).
INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID)
  SELECT 9433, 2021, 808, '11', 'Unfinished Block', 8801, 5, 'N', NULL, 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.BASIC_SILVICULTURE_REPORT WHERE BASIC_SILVICULTURE_REPORT_ID = 9433);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5850, NULL, 9433, 24, NULL, 18000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5850);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5851, NULL, 9433, 23, NULL, NULL, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5851);
-- ================================================================================================
-- Mill 809 -- Sch11 Verify Draft Milling (MILL_NUMBER 1809). 1-10 at D, silviculture at D.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID)
  SELECT 809, 'Sch11 Verify Draft Milling', 1809, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.MILL WHERE MILL_ID = 809);
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID)
  SELECT 809, 'ACT', 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_STATUS_XREF WHERE ILCR_MILL_STATUS_XREF_ID = 809);
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE,
                                         MILL_SILVICULTUR_STATUS_CODE, REPORT_COMPLETED_IND, REVISION_COUNT,
                                         AUDITOR_MILL_ID, AUDITOR_USER_GUID, LICENSEE_MILL_ID,
                                         LICENSEE_USER_GUID, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID,
                                         UPDATE_TIMESTAMP)
  SELECT 2021, 809, 'D', 'D', 'N', 0, NULL, NULL, NULL, NULL,
         'SEED', SYSTIMESTAMP, 'SEED', SYSTIMESTAMP FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_REPORT_STATUS WHERE REPORT_YEAR = 2021 AND ILCR_MILL_ID = 809);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 809, c.ID, 'D', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE
    FROM (SELECT '1' ID FROM DUAL UNION ALL SELECT '2' FROM DUAL UNION ALL SELECT '3' FROM DUAL
          UNION ALL SELECT '4' FROM DUAL UNION ALL SELECT '5' FROM DUAL UNION ALL SELECT '6' FROM DUAL
          UNION ALL SELECT '7' FROM DUAL UNION ALL SELECT '8' FROM DUAL UNION ALL SELECT '9' FROM DUAL
          UNION ALL SELECT '10' FROM DUAL) c
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 809 AND r.ILCR_CATEGORY_ID = c.ID);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 809, '11', 'D', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 809 AND r.ILCR_CATEGORY_ID = '11');
INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID)
  SELECT 9434, 2021, 809, '11', 'Draft Block', 8801, 5, 'N', NULL, 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.BASIC_SILVICULTURE_REPORT WHERE BASIC_SILVICULTURE_REPORT_ID = 9434);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5852, NULL, 9434, 24, NULL, 4000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5852);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5853, NULL, 9434, 23, NULL, 4000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5853);
-- ================================================================================================
-- Mill 810 -- Sch11 Verify Verified Milling (MILL_NUMBER 1810). 1-10 at D, silviculture at V.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID)
  SELECT 810, 'Sch11 Verify Verified Milling', 1810, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.MILL WHERE MILL_ID = 810);
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID)
  SELECT 810, 'ACT', 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_STATUS_XREF WHERE ILCR_MILL_STATUS_XREF_ID = 810);
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE,
                                         MILL_SILVICULTUR_STATUS_CODE, REPORT_COMPLETED_IND, REVISION_COUNT,
                                         AUDITOR_MILL_ID, AUDITOR_USER_GUID, LICENSEE_MILL_ID,
                                         LICENSEE_USER_GUID, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID,
                                         UPDATE_TIMESTAMP)
  SELECT 2021, 810, 'D', 'V', 'N', 0, NULL, NULL, NULL, NULL,
         'SEED', SYSTIMESTAMP, 'SEED', SYSTIMESTAMP FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_REPORT_STATUS WHERE REPORT_YEAR = 2021 AND ILCR_MILL_ID = 810);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 810, c.ID, 'D', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE
    FROM (SELECT '1' ID FROM DUAL UNION ALL SELECT '2' FROM DUAL UNION ALL SELECT '3' FROM DUAL
          UNION ALL SELECT '4' FROM DUAL UNION ALL SELECT '5' FROM DUAL UNION ALL SELECT '6' FROM DUAL
          UNION ALL SELECT '7' FROM DUAL UNION ALL SELECT '8' FROM DUAL UNION ALL SELECT '9' FROM DUAL
          UNION ALL SELECT '10' FROM DUAL) c
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 810 AND r.ILCR_CATEGORY_ID = c.ID);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 810, '11', 'V', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 810 AND r.ILCR_CATEGORY_ID = '11');
INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID)
  SELECT 9435, 2021, 810, '11', 'Verified Block', 8801, 5, 'N', NULL, 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.BASIC_SILVICULTURE_REPORT WHERE BASIC_SILVICULTURE_REPORT_ID = 9435);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5854, NULL, 9435, 24, NULL, 4000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5854);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5855, NULL, 9435, 23, NULL, 4000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5855);
-- ================================================================================================
-- Mill 811 -- Sch11 Verify Rollback Milling (MILL_NUMBER 1811). 1-10 at D, silviculture at S.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID)
  SELECT 811, 'Sch11 Verify Rollback Milling', 1811, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.MILL WHERE MILL_ID = 811);
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID)
  SELECT 811, 'ACT', 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_STATUS_XREF WHERE ILCR_MILL_STATUS_XREF_ID = 811);
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE,
                                         MILL_SILVICULTUR_STATUS_CODE, REPORT_COMPLETED_IND, REVISION_COUNT,
                                         AUDITOR_MILL_ID, AUDITOR_USER_GUID, LICENSEE_MILL_ID,
                                         LICENSEE_USER_GUID, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID,
                                         UPDATE_TIMESTAMP)
  SELECT 2021, 811, 'D', 'S', 'N', 0, NULL, NULL, NULL, NULL,
         'SEED', SYSTIMESTAMP, 'SEED', SYSTIMESTAMP FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_REPORT_STATUS WHERE REPORT_YEAR = 2021 AND ILCR_MILL_ID = 811);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 811, c.ID, 'D', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE
    FROM (SELECT '1' ID FROM DUAL UNION ALL SELECT '2' FROM DUAL UNION ALL SELECT '3' FROM DUAL
          UNION ALL SELECT '4' FROM DUAL UNION ALL SELECT '5' FROM DUAL UNION ALL SELECT '6' FROM DUAL
          UNION ALL SELECT '7' FROM DUAL UNION ALL SELECT '8' FROM DUAL UNION ALL SELECT '9' FROM DUAL
          UNION ALL SELECT '10' FROM DUAL) c
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 811 AND r.ILCR_CATEGORY_ID = c.ID);
-- NO category '11' row: the Schedule 11 category advance affects 0 rows and the verify must roll back.
INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID)
  SELECT 9436, 2021, 811, '11', 'Rollback Block', 8801, 5, 'N', NULL, 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.BASIC_SILVICULTURE_REPORT WHERE BASIC_SILVICULTURE_REPORT_ID = 9436);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5856, NULL, 9436, 24, NULL, 6000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5856);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5857, NULL, 9436, 23, NULL, 6000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5857);
-- ================================================================================================
-- Mill 812 -- Sch11 Verify Racing Milling (MILL_NUMBER 1812). 1-10 at D, silviculture at S.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID)
  SELECT 812, 'Sch11 Verify Racing Milling', 1812, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.MILL WHERE MILL_ID = 812);
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID)
  SELECT 812, 'ACT', 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_STATUS_XREF WHERE ILCR_MILL_STATUS_XREF_ID = 812);
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE,
                                         MILL_SILVICULTUR_STATUS_CODE, REPORT_COMPLETED_IND, REVISION_COUNT,
                                         AUDITOR_MILL_ID, AUDITOR_USER_GUID, LICENSEE_MILL_ID,
                                         LICENSEE_USER_GUID, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID,
                                         UPDATE_TIMESTAMP)
  SELECT 2021, 812, 'D', 'S', 'N', 0, NULL, NULL, NULL, NULL,
         'SEED', SYSTIMESTAMP, 'SEED', SYSTIMESTAMP FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_REPORT_STATUS WHERE REPORT_YEAR = 2021 AND ILCR_MILL_ID = 812);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 812, c.ID, 'D', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE
    FROM (SELECT '1' ID FROM DUAL UNION ALL SELECT '2' FROM DUAL UNION ALL SELECT '3' FROM DUAL
          UNION ALL SELECT '4' FROM DUAL UNION ALL SELECT '5' FROM DUAL UNION ALL SELECT '6' FROM DUAL
          UNION ALL SELECT '7' FROM DUAL UNION ALL SELECT '8' FROM DUAL UNION ALL SELECT '9' FROM DUAL
          UNION ALL SELECT '10' FROM DUAL) c
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 812 AND r.ILCR_CATEGORY_ID = c.ID);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 812, '11', 'A', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 812 AND r.ILCR_CATEGORY_ID = '11');
INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID)
  SELECT 9437, 2021, 812, '11', 'Racing Block', 8801, 5, 'N', NULL, 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.BASIC_SILVICULTURE_REPORT WHERE BASIC_SILVICULTURE_REPORT_ID = 9437);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5858, NULL, 9437, 24, NULL, 3000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5858);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5859, NULL, 9437, 23, NULL, 3000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5859);
-- ================================================================================================
-- Mill 813 -- Sch11 Verify Unassigned Milling (MILL_NUMBER 1813). 1-10 at S, silviculture at S.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID)
  SELECT 813, 'Sch11 Verify Unassigned Milling', 1813, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.MILL WHERE MILL_ID = 813);
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID)
  SELECT 813, 'ACT', 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_STATUS_XREF WHERE ILCR_MILL_STATUS_XREF_ID = 813);
INSERT INTO THE.ILCR_MILL_USER_XREF (ILCR_MILL_ID, USER_GUID, ACTIVE_DATE, INACTIVE_DATE, REVISION_COUNT,
                                     ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 813, 'VERIFY11OLDAUDITOR00011112222AA1', SYSDATE, NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_USER_XREF WHERE ILCR_MILL_ID = 813 AND USER_GUID = 'VERIFY11OLDAUDITOR00011112222AA1');
-- 807's pre-existing AUDITOR pair must differ from the acting admin's in BOTH halves, or the MILL_ID column's overwrite
-- (D1) is proven by no arm: re-point it at the (813, OLDAUDITOR) xref just created. An UPDATE here rather than in 807's
-- INSERT because the pair's FK needs this xref row first. Guarded on the exact seed values, so a re-run is a no-op.
UPDATE THE.ILCR_MILL_REPORT_STATUS
   SET AUDITOR_MILL_ID = 813
 WHERE REPORT_YEAR = 2021 AND ILCR_MILL_ID = 807 AND MILL_SILVICULTUR_STATUS_CODE = 'S'
   AND AUDITOR_MILL_ID = 807 AND AUDITOR_USER_GUID = 'VERIFY11OLDAUDITOR00011112222AA1';
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE,
                                         MILL_SILVICULTUR_STATUS_CODE, REPORT_COMPLETED_IND, REVISION_COUNT,
                                         AUDITOR_MILL_ID, AUDITOR_USER_GUID, LICENSEE_MILL_ID,
                                         LICENSEE_USER_GUID, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID,
                                         UPDATE_TIMESTAMP)
  SELECT 2021, 813, 'S', 'S', 'N', 0, 813, 'VERIFY11OLDAUDITOR00011112222AA1', NULL, NULL,
         'SEED', SYSTIMESTAMP, 'SEED', SYSTIMESTAMP FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_REPORT_STATUS WHERE REPORT_YEAR = 2021 AND ILCR_MILL_ID = 813);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 813, c.ID, 'A', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE
    FROM (SELECT '1' ID FROM DUAL UNION ALL SELECT '2' FROM DUAL UNION ALL SELECT '3' FROM DUAL
          UNION ALL SELECT '4' FROM DUAL UNION ALL SELECT '5' FROM DUAL UNION ALL SELECT '6' FROM DUAL
          UNION ALL SELECT '7' FROM DUAL UNION ALL SELECT '8' FROM DUAL UNION ALL SELECT '9' FROM DUAL
          UNION ALL SELECT '10' FROM DUAL) c
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 813 AND r.ILCR_CATEGORY_ID = c.ID);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 813, '11', 'A', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 813 AND r.ILCR_CATEGORY_ID = '11');
INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID)
  SELECT 9438, 2021, 813, '11', 'Unassigned Block', 8801, 5, 'N', NULL, 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.BASIC_SILVICULTURE_REPORT WHERE BASIC_SILVICULTURE_REPORT_ID = 9438);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5860, NULL, 9438, 24, NULL, 2000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5860);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5861, NULL, 9438, 23, NULL, 2000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5861);
-- ================================================================================================
-- Mill 814 -- Sch11 Verify No Locations Milling (MILL_NUMBER 1814). 1-10 at D, silviculture at S.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID)
  SELECT 814, 'Sch11 Verify No Locations Milling', 1814, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.MILL WHERE MILL_ID = 814);
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID)
  SELECT 814, 'ACT', 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_STATUS_XREF WHERE ILCR_MILL_STATUS_XREF_ID = 814);
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE,
                                         MILL_SILVICULTUR_STATUS_CODE, REPORT_COMPLETED_IND, REVISION_COUNT,
                                         AUDITOR_MILL_ID, AUDITOR_USER_GUID, LICENSEE_MILL_ID,
                                         LICENSEE_USER_GUID, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID,
                                         UPDATE_TIMESTAMP)
  SELECT 2021, 814, 'D', 'S', 'N', 0, NULL, NULL, NULL, NULL,
         'SEED', SYSTIMESTAMP, 'SEED', SYSTIMESTAMP FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_REPORT_STATUS WHERE REPORT_YEAR = 2021 AND ILCR_MILL_ID = 814);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 814, c.ID, 'D', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE
    FROM (SELECT '1' ID FROM DUAL UNION ALL SELECT '2' FROM DUAL UNION ALL SELECT '3' FROM DUAL
          UNION ALL SELECT '4' FROM DUAL UNION ALL SELECT '5' FROM DUAL UNION ALL SELECT '6' FROM DUAL
          UNION ALL SELECT '7' FROM DUAL UNION ALL SELECT '8' FROM DUAL UNION ALL SELECT '9' FROM DUAL
          UNION ALL SELECT '10' FROM DUAL) c
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 814 AND r.ILCR_CATEGORY_ID = c.ID);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 814, '11', 'A', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 814 AND r.ILCR_CATEGORY_ID = '11');
-- Zero Schedule 11 locations: vacuously MET, legacy parity (Schedule11CheckStatus.java:19).
-- ================================================================================================
-- Mill 815 -- Sch11 Verify Both Tracks Milling (MILL_NUMBER 1815). 1-10 at S, silviculture at S.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID)
  SELECT 815, 'Sch11 Verify Both Tracks Milling', 1815, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.MILL WHERE MILL_ID = 815);
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID)
  SELECT 815, 'ACT', 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_STATUS_XREF WHERE ILCR_MILL_STATUS_XREF_ID = 815);
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE,
                                         MILL_SILVICULTUR_STATUS_CODE, REPORT_COMPLETED_IND, REVISION_COUNT,
                                         AUDITOR_MILL_ID, AUDITOR_USER_GUID, LICENSEE_MILL_ID,
                                         LICENSEE_USER_GUID, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID,
                                         UPDATE_TIMESTAMP)
  SELECT 2021, 815, 'S', 'S', 'N', 0, NULL, NULL, NULL, NULL,
         'SEED', SYSTIMESTAMP, 'SEED', SYSTIMESTAMP FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_REPORT_STATUS WHERE REPORT_YEAR = 2021 AND ILCR_MILL_ID = 815);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 815, c.ID, 'A', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE
    FROM (SELECT '1' ID FROM DUAL UNION ALL SELECT '2' FROM DUAL UNION ALL SELECT '3' FROM DUAL
          UNION ALL SELECT '4' FROM DUAL UNION ALL SELECT '5' FROM DUAL UNION ALL SELECT '6' FROM DUAL
          UNION ALL SELECT '7' FROM DUAL UNION ALL SELECT '8' FROM DUAL UNION ALL SELECT '9' FROM DUAL
          UNION ALL SELECT '10' FROM DUAL) c
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 815 AND r.ILCR_CATEGORY_ID = c.ID);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 815, '11', 'A', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 815 AND r.ILCR_CATEGORY_ID = '11');
INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID)
  SELECT 9439, 2021, 815, '11', 'Both Tracks Block', 8801, 5, 'N', NULL, 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.BASIC_SILVICULTURE_REPORT WHERE BASIC_SILVICULTURE_REPORT_ID = 9439);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5862, NULL, 9439, 24, NULL, 1000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5862);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5863, NULL, 9439, 23, NULL, 1000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5863);
-- Schedules 1, 2 and 3 all-met, copied row for row from R__55's mill 764 (summaries 1060-1062, details
-- 2711-2746) with the ids remapped; the other eight 1-10 schedules report zero rows as a vacuous MET.
INSERT INTO THE.ILCR_REPORT_SUMMARY (ILCR_REPORT_SUMMARY_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, REVISION_COUNT, ENTRY_USERID)
  SELECT 1681, 2021, 815, '1', 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_SUMMARY WHERE ILCR_REPORT_SUMMARY_ID = 1681);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5750, 1681, 12, 100, 500, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5750);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5751, 1681, 13, 100, 500, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5751);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5752, 1681, 14, 100, 500, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5752);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5753, 1681, 15, 100, 500, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5753);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5754, 1681, 16, 100, 500, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5754);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5755, 1681, 17, 100, 500, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5755);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5756, 1681, 18, 100, 500, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5756);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5757, 1681, 1, 100, 500, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5757);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5758, 1681, 2, 100, 500, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5758);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5759, 1681, 143, 100, NULL, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5759);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5760, 1681, 144, 100, NULL, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5760);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5761, 1681, 139, 100, NULL, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5761);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5762, 1681, 140, 100, NULL, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5762);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5763, 1681, 19, 0, NULL, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5763);
INSERT INTO THE.ILCR_REPORT_SUMMARY (ILCR_REPORT_SUMMARY_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, REVISION_COUNT, ENTRY_USERID)
  SELECT 1682, 2021, 815, '2', 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_SUMMARY WHERE ILCR_REPORT_SUMMARY_ID = 1682);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5764, 1682, 25, NULL, 500000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5764);
INSERT INTO THE.ILCR_REPORT_SUMMARY (ILCR_REPORT_SUMMARY_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, REVISION_COUNT, ENTRY_USERID)
  SELECT 1683, 2021, 815, '3', 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_SUMMARY WHERE ILCR_REPORT_SUMMARY_ID = 1683);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5765, 1683, 27, NULL, 1000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5765);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5766, 1683, 28, NULL, 1000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5766);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5767, 1683, 29, NULL, 1000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5767);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5768, 1683, 30, NULL, 1000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5768);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5769, 1683, 31, NULL, 1000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5769);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5770, 1683, 32, NULL, 1000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5770);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5771, 1683, 33, NULL, 1000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5771);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5772, 1683, 34, NULL, 1000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5772);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5773, 1683, 35, NULL, 1000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5773);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5774, 1683, 36, NULL, 1000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5774);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5775, 1683, 37, NULL, 1000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5775);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5776, 1683, 125, NULL, 500, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5776);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5777, 1683, 126, NULL, 500, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5777);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5778, 1683, 128, NULL, 500, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5778);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5779, 1683, 129, NULL, 500, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5779);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5780, 1683, 130, NULL, 500, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5780);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5781, 1683, 132, NULL, 500, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5781);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5782, 1683, 133, NULL, 500, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5782);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5783, 1683, 134, NULL, 500, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5783);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5784, 1683, 118, 1000, NULL, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5784);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5785, 1683, 119, 1000, NULL, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5785);
