-- Schedule 11 reversal fixtures (UC-CHK-017 Set to Draft S->D, UC-CHK-019 Set to Submit V->S): twelve mill/years,
-- all reporting year 2021, all ACT, REPORT_COMPLETED_IND 'N'. Each carries the ILCR_REPORT_CATEGORY rows its tracks'
-- statuses imply (1-10 at D -> categories '1'..'10' at 'D', at S -> 'A', at V -> 'V'; silviculture at S -> '11' at
-- 'A', at V -> 'V', at D or NULL -> 'D').
--
-- THE TWO TRACK CODES DIFFER on every mill, so a statement naming the wrong status column, or a read of the wrong
-- code, fails a test rather than passing by coincidence.
--
-- Schedule 11 is MET when every location has BOTH an Actual (item 24) and a Planned (item 23) cost; zero locations
-- is vacuously MET (legacy Schedule11CheckStatus.java:19).
--   823  Schedule11SetToDraftIT        -- Set to Draft happy path: silviculture S, 1-10 V; two met locations; a LICENSEE
--                                          and an AUDITOR pair both seeded (proved unchanged); one 1-10 summary + cost
--   824  Schedule11SetToSubmitIT       -- Set to Submit happy path: silviculture V, 1-10 D; same seeding; the acting
--                                          admin IS xref'd here, so a legacy-style LICENSEE write would be visible
--   825  Schedule11SetToDraftIT        -- gate fails: the Planned Cost row exists with COST NULL (never written)
--   826  Schedule11SetToSubmitIT       -- gate fails, the same NULL shape at V (never written)
--   827  both reversal ITs             -- silviculture D: Set to Draft D->D and Set to Submit D->S refused (never written)
--   828  both reversal ITs             -- silviculture S, met, NO category '11': Set to Draft 500 rollback, Set to
--                                          Submit S->S refused
--   829  both reversal ITs             -- silviculture V, met, NO category '11': Set to Submit 500 rollback, Set to
--                                          Draft V->D refused
--   830  Schedule11ReversalConcurrencyIT -- two racing Set to Drafts
--   831  Schedule11ReversalConcurrencyIT -- two racing Set to Submits
--   832  Schedule11ReversalConcurrencyIT -- Set to Draft racing the Schedule 11 Verify: the two exits of S
--   833  both reversal ITs             -- silviculture NULL: both reversals refused (never written)
--   834  Schedule11SetToDraftIT        -- silviculture S, zero locations: vacuously MET
--
-- Prefix 62 is BELOW 70 so R__70's set-based insert associates the canonical submitter to all twelve mills (the
-- SUBMITTER 403 arm then fails for lacking the action, not for being out of scope, and the editable:true arm after
-- Set to Draft has an assigned Licensee to ask as).
--
-- Claims (verified free by bare-id grep over db/, db-e2e/, the test sources and frontend/e2e on 2026-09-28): MILL /
-- ILCR_MILL_STATUS_XREF 823-834 (MILL_NUMBER 1823-1834), BASIC_SILVICULTURE_REPORT 9456-9479 (below
-- ILCR_REPORT_COMMON_SEQ's 9500), ILCR_REPORT_SUMMARY 1700-1709, ILCR_COST_REPORT_DETAIL 5900-5959, all below the
-- 9000 floor the README keeps clear of ILCR_COST_REPORT_DETAIL_SEQ. ILCR_USER REVERSE11ADMIN00011112222333AAA1 (the acting
-- admin), REVERSE11LICENSEE0001111222AAA11 and REVERSE11AUDITOR000111122223AAA1 (the recorded pairs). Every INSERT is the
-- single-row `(cols) SELECT ... FROM DUAL WHERE NOT EXISTS` form guarded on its key (README convention 1b).
-- ================================================================================================
-- The three directory users. ADMIN acts; the other two exist only to give 823 and 824 recorded pairs to keep.
-- ================================================================================================
INSERT INTO THE.ILCR_USER (USER_GUID, ILCR_ROLE_NAME, ACTIVE_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                           UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 'REVERSE11ADMIN00011112222333AAA1', 'ADMIN', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_USER WHERE USER_GUID = 'REVERSE11ADMIN00011112222333AAA1');
INSERT INTO THE.ILCR_USER (USER_GUID, ILCR_ROLE_NAME, ACTIVE_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                           UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 'REVERSE11LICENSEE0001111222AAA11', 'LICENSEE', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_USER WHERE USER_GUID = 'REVERSE11LICENSEE0001111222AAA11');
INSERT INTO THE.ILCR_USER (USER_GUID, ILCR_ROLE_NAME, ACTIVE_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                           UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 'REVERSE11AUDITOR000111122223AAA1', 'ADMIN', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_USER WHERE USER_GUID = 'REVERSE11AUDITOR000111122223AAA1');
-- ================================================================================================
-- Mill 823 -- Sch11 Set To Draft Happy Milling (MILL_NUMBER 1823). 1-10 at V, silviculture at S.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID)
  SELECT 823, 'Sch11 Set To Draft Happy Milling', 1823, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.MILL WHERE MILL_ID = 823);
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID)
  SELECT 823, 'ACT', 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_STATUS_XREF WHERE ILCR_MILL_STATUS_XREF_ID = 823);
-- The recorded pairs point at xref rows this file creates (R__70 sorts after it, and the composite FKs need them).
INSERT INTO THE.ILCR_MILL_USER_XREF (ILCR_MILL_ID, USER_GUID, ACTIVE_DATE, INACTIVE_DATE, REVISION_COUNT,
                                     ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 823, 'REVERSE11LICENSEE0001111222AAA11', SYSDATE, NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_USER_XREF WHERE ILCR_MILL_ID = 823 AND USER_GUID = 'REVERSE11LICENSEE0001111222AAA11');
INSERT INTO THE.ILCR_MILL_USER_XREF (ILCR_MILL_ID, USER_GUID, ACTIVE_DATE, INACTIVE_DATE, REVISION_COUNT,
                                     ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 823, 'REVERSE11AUDITOR000111122223AAA1', SYSDATE, NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_USER_XREF WHERE ILCR_MILL_ID = 823 AND USER_GUID = 'REVERSE11AUDITOR000111122223AAA1');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE,
                                         MILL_SILVICULTUR_STATUS_CODE, REPORT_COMPLETED_IND, REVISION_COUNT,
                                         AUDITOR_MILL_ID, AUDITOR_USER_GUID, LICENSEE_MILL_ID,
                                         LICENSEE_USER_GUID, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID,
                                         UPDATE_TIMESTAMP)
  SELECT 2021, 823, 'V', 'S', 'N', 0, 823, 'REVERSE11AUDITOR000111122223AAA1', 823, 'REVERSE11LICENSEE0001111222AAA11',
         'SEED', SYSTIMESTAMP, 'SEED', SYSTIMESTAMP FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_REPORT_STATUS WHERE REPORT_YEAR = 2021 AND ILCR_MILL_ID = 823);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 823, c.ID, 'V', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE
    FROM (SELECT '1' ID FROM DUAL UNION ALL SELECT '2' FROM DUAL UNION ALL SELECT '3' FROM DUAL
          UNION ALL SELECT '4' FROM DUAL UNION ALL SELECT '5' FROM DUAL UNION ALL SELECT '6' FROM DUAL
          UNION ALL SELECT '7' FROM DUAL UNION ALL SELECT '8' FROM DUAL UNION ALL SELECT '9' FROM DUAL
          UNION ALL SELECT '10' FROM DUAL) c
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 823 AND r.ILCR_CATEGORY_ID = c.ID);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 823, '11', 'A', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 823 AND r.ILCR_CATEGORY_ID = '11');
INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID)
  SELECT 9456, 2021, 823, '11', 'Reversal Block North', 8801, 5, 'N', NULL, 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.BASIC_SILVICULTURE_REPORT WHERE BASIC_SILVICULTURE_REPORT_ID = 9456);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5900, NULL, 9456, 24, NULL, 25000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5900);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5901, NULL, 9456, 23, NULL, 20000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5901);
INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID)
  SELECT 9457, 2021, 823, '11', 'Reversal Block South', 8801, 5, 'N', NULL, 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.BASIC_SILVICULTURE_REPORT WHERE BASIC_SILVICULTURE_REPORT_ID = 9457);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5902, NULL, 9457, 24, NULL, 14000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5902);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5903, NULL, 9457, 23, NULL, 15000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5903);
-- ONE Schedules 1-10 row family on 823 -- a Schedule 2 summary and its item-25 cost -- seeded only so a
-- Schedule 11 reversal that also ran the twenty 1-10 audit touches has a row to stamp, and the IT can see it.
INSERT INTO THE.ILCR_REPORT_SUMMARY (ILCR_REPORT_SUMMARY_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, REVISION_COUNT, ENTRY_USERID)
  SELECT 1700, 2021, 823, '2', 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_SUMMARY WHERE ILCR_REPORT_SUMMARY_ID = 1700);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5950, 1700, 25, NULL, 500000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5950);
-- ================================================================================================
-- Mill 824 -- Sch11 Set To Submit Happy Milling (MILL_NUMBER 1824). 1-10 at D, silviculture at V.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID)
  SELECT 824, 'Sch11 Set To Submit Happy Milling', 1824, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.MILL WHERE MILL_ID = 824);
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID)
  SELECT 824, 'ACT', 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_STATUS_XREF WHERE ILCR_MILL_STATUS_XREF_ID = 824);
-- The recorded pairs point at xref rows this file creates (R__70 sorts after it, and the composite FKs need them).
INSERT INTO THE.ILCR_MILL_USER_XREF (ILCR_MILL_ID, USER_GUID, ACTIVE_DATE, INACTIVE_DATE, REVISION_COUNT,
                                     ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 824, 'REVERSE11LICENSEE0001111222AAA11', SYSDATE, NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_USER_XREF WHERE ILCR_MILL_ID = 824 AND USER_GUID = 'REVERSE11LICENSEE0001111222AAA11');
INSERT INTO THE.ILCR_MILL_USER_XREF (ILCR_MILL_ID, USER_GUID, ACTIVE_DATE, INACTIVE_DATE, REVISION_COUNT,
                                     ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 824, 'REVERSE11AUDITOR000111122223AAA1', SYSDATE, NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_USER_XREF WHERE ILCR_MILL_ID = 824 AND USER_GUID = 'REVERSE11AUDITOR000111122223AAA1');
-- The acting admin's assignment. Legacy's Set to Submit would have written it into the LICENSEE pair
-- (SubmitReportDAO:405-409); with it absent that write would store NULL and be indistinguishable from a
-- different defect. Deviation (S) says the pair keeps the Licensee.
INSERT INTO THE.ILCR_MILL_USER_XREF (ILCR_MILL_ID, USER_GUID, ACTIVE_DATE, INACTIVE_DATE, REVISION_COUNT,
                                     ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 824, 'REVERSE11ADMIN00011112222333AAA1', SYSDATE, NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_USER_XREF WHERE ILCR_MILL_ID = 824 AND USER_GUID = 'REVERSE11ADMIN00011112222333AAA1');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE,
                                         MILL_SILVICULTUR_STATUS_CODE, REPORT_COMPLETED_IND, REVISION_COUNT,
                                         AUDITOR_MILL_ID, AUDITOR_USER_GUID, LICENSEE_MILL_ID,
                                         LICENSEE_USER_GUID, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID,
                                         UPDATE_TIMESTAMP)
  SELECT 2021, 824, 'D', 'V', 'N', 0, 824, 'REVERSE11AUDITOR000111122223AAA1', 824, 'REVERSE11LICENSEE0001111222AAA11',
         'SEED', SYSTIMESTAMP, 'SEED', SYSTIMESTAMP FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_REPORT_STATUS WHERE REPORT_YEAR = 2021 AND ILCR_MILL_ID = 824);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 824, c.ID, 'D', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE
    FROM (SELECT '1' ID FROM DUAL UNION ALL SELECT '2' FROM DUAL UNION ALL SELECT '3' FROM DUAL
          UNION ALL SELECT '4' FROM DUAL UNION ALL SELECT '5' FROM DUAL UNION ALL SELECT '6' FROM DUAL
          UNION ALL SELECT '7' FROM DUAL UNION ALL SELECT '8' FROM DUAL UNION ALL SELECT '9' FROM DUAL
          UNION ALL SELECT '10' FROM DUAL) c
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 824 AND r.ILCR_CATEGORY_ID = c.ID);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 824, '11', 'V', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 824 AND r.ILCR_CATEGORY_ID = '11');
INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID)
  SELECT 9458, 2021, 824, '11', 'Withdrawn Block North', 8801, 5, 'N', NULL, 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.BASIC_SILVICULTURE_REPORT WHERE BASIC_SILVICULTURE_REPORT_ID = 9458);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5904, NULL, 9458, 24, NULL, 26000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5904);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5905, NULL, 9458, 23, NULL, 21000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5905);
INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID)
  SELECT 9459, 2021, 824, '11', 'Withdrawn Block South', 8801, 5, 'N', NULL, 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.BASIC_SILVICULTURE_REPORT WHERE BASIC_SILVICULTURE_REPORT_ID = 9459);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5906, NULL, 9459, 24, NULL, 13000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5906);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5907, NULL, 9459, 23, NULL, 16000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5907);
-- ONE Schedules 1-10 row family on 824 -- a Schedule 2 summary and its item-25 cost -- seeded only so a
-- Schedule 11 reversal that also ran the twenty 1-10 audit touches has a row to stamp, and the IT can see it.
INSERT INTO THE.ILCR_REPORT_SUMMARY (ILCR_REPORT_SUMMARY_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, REVISION_COUNT, ENTRY_USERID)
  SELECT 1701, 2021, 824, '2', 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_SUMMARY WHERE ILCR_REPORT_SUMMARY_ID = 1701);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5951, 1701, 25, NULL, 500000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5951);
-- ================================================================================================
-- Mill 825 -- Sch11 Set To Draft Failing Milling (MILL_NUMBER 1825). 1-10 at D, silviculture at S.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID)
  SELECT 825, 'Sch11 Set To Draft Failing Milling', 1825, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.MILL WHERE MILL_ID = 825);
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID)
  SELECT 825, 'ACT', 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_STATUS_XREF WHERE ILCR_MILL_STATUS_XREF_ID = 825);
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE,
                                         MILL_SILVICULTUR_STATUS_CODE, REPORT_COMPLETED_IND, REVISION_COUNT,
                                         AUDITOR_MILL_ID, AUDITOR_USER_GUID, LICENSEE_MILL_ID,
                                         LICENSEE_USER_GUID, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID,
                                         UPDATE_TIMESTAMP)
  SELECT 2021, 825, 'D', 'S', 'N', 0, NULL, NULL, NULL, NULL,
         'SEED', SYSTIMESTAMP, 'SEED', SYSTIMESTAMP FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_REPORT_STATUS WHERE REPORT_YEAR = 2021 AND ILCR_MILL_ID = 825);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 825, c.ID, 'D', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE
    FROM (SELECT '1' ID FROM DUAL UNION ALL SELECT '2' FROM DUAL UNION ALL SELECT '3' FROM DUAL
          UNION ALL SELECT '4' FROM DUAL UNION ALL SELECT '5' FROM DUAL UNION ALL SELECT '6' FROM DUAL
          UNION ALL SELECT '7' FROM DUAL UNION ALL SELECT '8' FROM DUAL UNION ALL SELECT '9' FROM DUAL
          UNION ALL SELECT '10' FROM DUAL) c
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 825 AND r.ILCR_CATEGORY_ID = c.ID);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 825, '11', 'A', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 825 AND r.ILCR_CATEGORY_ID = '11');
-- The Planned Cost (item 23) row EXISTS with COST NULL -- the real 'value blanked' shape; the check reads it
-- as missing.
INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID)
  SELECT 9460, 2021, 825, '11', 'Unfinished Draft Block', 8801, 5, 'N', NULL, 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.BASIC_SILVICULTURE_REPORT WHERE BASIC_SILVICULTURE_REPORT_ID = 9460);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5908, NULL, 9460, 24, NULL, 18000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5908);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5909, NULL, 9460, 23, NULL, NULL, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5909);
-- ================================================================================================
-- Mill 826 -- Sch11 Set To Submit Failing Milling (MILL_NUMBER 1826). 1-10 at D, silviculture at V.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID)
  SELECT 826, 'Sch11 Set To Submit Failing Milling', 1826, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.MILL WHERE MILL_ID = 826);
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID)
  SELECT 826, 'ACT', 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_STATUS_XREF WHERE ILCR_MILL_STATUS_XREF_ID = 826);
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE,
                                         MILL_SILVICULTUR_STATUS_CODE, REPORT_COMPLETED_IND, REVISION_COUNT,
                                         AUDITOR_MILL_ID, AUDITOR_USER_GUID, LICENSEE_MILL_ID,
                                         LICENSEE_USER_GUID, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID,
                                         UPDATE_TIMESTAMP)
  SELECT 2021, 826, 'D', 'V', 'N', 0, NULL, NULL, NULL, NULL,
         'SEED', SYSTIMESTAMP, 'SEED', SYSTIMESTAMP FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_REPORT_STATUS WHERE REPORT_YEAR = 2021 AND ILCR_MILL_ID = 826);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 826, c.ID, 'D', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE
    FROM (SELECT '1' ID FROM DUAL UNION ALL SELECT '2' FROM DUAL UNION ALL SELECT '3' FROM DUAL
          UNION ALL SELECT '4' FROM DUAL UNION ALL SELECT '5' FROM DUAL UNION ALL SELECT '6' FROM DUAL
          UNION ALL SELECT '7' FROM DUAL UNION ALL SELECT '8' FROM DUAL UNION ALL SELECT '9' FROM DUAL
          UNION ALL SELECT '10' FROM DUAL) c
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 826 AND r.ILCR_CATEGORY_ID = c.ID);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 826, '11', 'V', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 826 AND r.ILCR_CATEGORY_ID = '11');
-- The Planned Cost (item 23) row EXISTS with COST NULL -- the real 'value blanked' shape; the check reads it
-- as missing.
INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID)
  SELECT 9461, 2021, 826, '11', 'Unfinished Submit Block', 8801, 5, 'N', NULL, 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.BASIC_SILVICULTURE_REPORT WHERE BASIC_SILVICULTURE_REPORT_ID = 9461);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5910, NULL, 9461, 24, NULL, 17000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5910);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5911, NULL, 9461, 23, NULL, NULL, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5911);
-- ================================================================================================
-- Mill 827 -- Sch11 Reversal Draft Milling (MILL_NUMBER 1827). 1-10 at S, silviculture at D.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID)
  SELECT 827, 'Sch11 Reversal Draft Milling', 1827, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.MILL WHERE MILL_ID = 827);
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID)
  SELECT 827, 'ACT', 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_STATUS_XREF WHERE ILCR_MILL_STATUS_XREF_ID = 827);
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE,
                                         MILL_SILVICULTUR_STATUS_CODE, REPORT_COMPLETED_IND, REVISION_COUNT,
                                         AUDITOR_MILL_ID, AUDITOR_USER_GUID, LICENSEE_MILL_ID,
                                         LICENSEE_USER_GUID, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID,
                                         UPDATE_TIMESTAMP)
  SELECT 2021, 827, 'S', 'D', 'N', 0, NULL, NULL, NULL, NULL,
         'SEED', SYSTIMESTAMP, 'SEED', SYSTIMESTAMP FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_REPORT_STATUS WHERE REPORT_YEAR = 2021 AND ILCR_MILL_ID = 827);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 827, c.ID, 'A', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE
    FROM (SELECT '1' ID FROM DUAL UNION ALL SELECT '2' FROM DUAL UNION ALL SELECT '3' FROM DUAL
          UNION ALL SELECT '4' FROM DUAL UNION ALL SELECT '5' FROM DUAL UNION ALL SELECT '6' FROM DUAL
          UNION ALL SELECT '7' FROM DUAL UNION ALL SELECT '8' FROM DUAL UNION ALL SELECT '9' FROM DUAL
          UNION ALL SELECT '10' FROM DUAL) c
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 827 AND r.ILCR_CATEGORY_ID = c.ID);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 827, '11', 'D', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 827 AND r.ILCR_CATEGORY_ID = '11');
INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID)
  SELECT 9462, 2021, 827, '11', 'Draft Reversal Block', 8801, 5, 'N', NULL, 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.BASIC_SILVICULTURE_REPORT WHERE BASIC_SILVICULTURE_REPORT_ID = 9462);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5912, NULL, 9462, 24, NULL, 5000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5912);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5913, NULL, 9462, 23, NULL, 4000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5913);
-- ================================================================================================
-- Mill 828 -- Sch11 Set To Draft Rollback Milling (MILL_NUMBER 1828). 1-10 at D, silviculture at S.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID)
  SELECT 828, 'Sch11 Set To Draft Rollback Milling', 1828, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.MILL WHERE MILL_ID = 828);
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID)
  SELECT 828, 'ACT', 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_STATUS_XREF WHERE ILCR_MILL_STATUS_XREF_ID = 828);
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE,
                                         MILL_SILVICULTUR_STATUS_CODE, REPORT_COMPLETED_IND, REVISION_COUNT,
                                         AUDITOR_MILL_ID, AUDITOR_USER_GUID, LICENSEE_MILL_ID,
                                         LICENSEE_USER_GUID, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID,
                                         UPDATE_TIMESTAMP)
  SELECT 2021, 828, 'D', 'S', 'N', 0, NULL, NULL, NULL, NULL,
         'SEED', SYSTIMESTAMP, 'SEED', SYSTIMESTAMP FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_REPORT_STATUS WHERE REPORT_YEAR = 2021 AND ILCR_MILL_ID = 828);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 828, c.ID, 'D', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE
    FROM (SELECT '1' ID FROM DUAL UNION ALL SELECT '2' FROM DUAL UNION ALL SELECT '3' FROM DUAL
          UNION ALL SELECT '4' FROM DUAL UNION ALL SELECT '5' FROM DUAL UNION ALL SELECT '6' FROM DUAL
          UNION ALL SELECT '7' FROM DUAL UNION ALL SELECT '8' FROM DUAL UNION ALL SELECT '9' FROM DUAL
          UNION ALL SELECT '10' FROM DUAL) c
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 828 AND r.ILCR_CATEGORY_ID = c.ID);
-- NO category '11' row: the Schedule 11 category advance affects 0 rows and the reversal must roll back.
INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID)
  SELECT 9463, 2021, 828, '11', 'Draft Rollback Block', 8801, 5, 'N', NULL, 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.BASIC_SILVICULTURE_REPORT WHERE BASIC_SILVICULTURE_REPORT_ID = 9463);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5914, NULL, 9463, 24, NULL, 5000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5914);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5915, NULL, 9463, 23, NULL, 4000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5915);
-- ================================================================================================
-- Mill 829 -- Sch11 Set To Submit Rollback Milling (MILL_NUMBER 1829). 1-10 at D, silviculture at V.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID)
  SELECT 829, 'Sch11 Set To Submit Rollback Milling', 1829, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.MILL WHERE MILL_ID = 829);
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID)
  SELECT 829, 'ACT', 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_STATUS_XREF WHERE ILCR_MILL_STATUS_XREF_ID = 829);
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE,
                                         MILL_SILVICULTUR_STATUS_CODE, REPORT_COMPLETED_IND, REVISION_COUNT,
                                         AUDITOR_MILL_ID, AUDITOR_USER_GUID, LICENSEE_MILL_ID,
                                         LICENSEE_USER_GUID, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID,
                                         UPDATE_TIMESTAMP)
  SELECT 2021, 829, 'D', 'V', 'N', 0, NULL, NULL, NULL, NULL,
         'SEED', SYSTIMESTAMP, 'SEED', SYSTIMESTAMP FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_REPORT_STATUS WHERE REPORT_YEAR = 2021 AND ILCR_MILL_ID = 829);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 829, c.ID, 'D', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE
    FROM (SELECT '1' ID FROM DUAL UNION ALL SELECT '2' FROM DUAL UNION ALL SELECT '3' FROM DUAL
          UNION ALL SELECT '4' FROM DUAL UNION ALL SELECT '5' FROM DUAL UNION ALL SELECT '6' FROM DUAL
          UNION ALL SELECT '7' FROM DUAL UNION ALL SELECT '8' FROM DUAL UNION ALL SELECT '9' FROM DUAL
          UNION ALL SELECT '10' FROM DUAL) c
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 829 AND r.ILCR_CATEGORY_ID = c.ID);
-- NO category '11' row: the Schedule 11 category advance affects 0 rows and the reversal must roll back.
INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID)
  SELECT 9464, 2021, 829, '11', 'Submit Rollback Block', 8801, 5, 'N', NULL, 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.BASIC_SILVICULTURE_REPORT WHERE BASIC_SILVICULTURE_REPORT_ID = 9464);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5916, NULL, 9464, 24, NULL, 5000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5916);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5917, NULL, 9464, 23, NULL, 4000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5917);
-- ================================================================================================
-- Mill 830 -- Sch11 Set To Draft Racing Milling (MILL_NUMBER 1830). 1-10 at D, silviculture at S.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID)
  SELECT 830, 'Sch11 Set To Draft Racing Milling', 1830, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.MILL WHERE MILL_ID = 830);
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID)
  SELECT 830, 'ACT', 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_STATUS_XREF WHERE ILCR_MILL_STATUS_XREF_ID = 830);
-- A recorded LICENSEE and AUDITOR pair, so the race's "identity pairs unchanged" assert can fail: over
-- NULLs, a regression writing the (unassigned) acting admin's NULL xref would pass unseen.
INSERT INTO THE.ILCR_MILL_USER_XREF (ILCR_MILL_ID, USER_GUID, ACTIVE_DATE, INACTIVE_DATE, REVISION_COUNT,
                                     ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 830, 'REVERSE11LICENSEE0001111222AAA11', SYSDATE, NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_USER_XREF WHERE ILCR_MILL_ID = 830 AND USER_GUID = 'REVERSE11LICENSEE0001111222AAA11');
INSERT INTO THE.ILCR_MILL_USER_XREF (ILCR_MILL_ID, USER_GUID, ACTIVE_DATE, INACTIVE_DATE, REVISION_COUNT,
                                     ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 830, 'REVERSE11AUDITOR000111122223AAA1', SYSDATE, NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_USER_XREF WHERE ILCR_MILL_ID = 830 AND USER_GUID = 'REVERSE11AUDITOR000111122223AAA1');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE,
                                         MILL_SILVICULTUR_STATUS_CODE, REPORT_COMPLETED_IND, REVISION_COUNT,
                                         AUDITOR_MILL_ID, AUDITOR_USER_GUID, LICENSEE_MILL_ID,
                                         LICENSEE_USER_GUID, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID,
                                         UPDATE_TIMESTAMP)
  SELECT 2021, 830, 'D', 'S', 'N', 0, 830, 'REVERSE11AUDITOR000111122223AAA1', 830, 'REVERSE11LICENSEE0001111222AAA11',
         'SEED', SYSTIMESTAMP, 'SEED', SYSTIMESTAMP FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_REPORT_STATUS WHERE REPORT_YEAR = 2021 AND ILCR_MILL_ID = 830);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 830, c.ID, 'D', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE
    FROM (SELECT '1' ID FROM DUAL UNION ALL SELECT '2' FROM DUAL UNION ALL SELECT '3' FROM DUAL
          UNION ALL SELECT '4' FROM DUAL UNION ALL SELECT '5' FROM DUAL UNION ALL SELECT '6' FROM DUAL
          UNION ALL SELECT '7' FROM DUAL UNION ALL SELECT '8' FROM DUAL UNION ALL SELECT '9' FROM DUAL
          UNION ALL SELECT '10' FROM DUAL) c
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 830 AND r.ILCR_CATEGORY_ID = c.ID);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 830, '11', 'A', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 830 AND r.ILCR_CATEGORY_ID = '11');
INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID)
  SELECT 9465, 2021, 830, '11', 'Draft Racing Block', 8801, 5, 'N', NULL, 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.BASIC_SILVICULTURE_REPORT WHERE BASIC_SILVICULTURE_REPORT_ID = 9465);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5918, NULL, 9465, 24, NULL, 5000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5918);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5919, NULL, 9465, 23, NULL, 4000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5919);
-- ================================================================================================
-- Mill 831 -- Sch11 Set To Submit Racing Milling (MILL_NUMBER 1831). 1-10 at D, silviculture at V.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID)
  SELECT 831, 'Sch11 Set To Submit Racing Milling', 1831, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.MILL WHERE MILL_ID = 831);
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID)
  SELECT 831, 'ACT', 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_STATUS_XREF WHERE ILCR_MILL_STATUS_XREF_ID = 831);
-- A recorded LICENSEE and AUDITOR pair, so the race's "identity pairs unchanged" assert can fail: over
-- NULLs, a regression writing the (unassigned) acting admin's NULL xref would pass unseen.
INSERT INTO THE.ILCR_MILL_USER_XREF (ILCR_MILL_ID, USER_GUID, ACTIVE_DATE, INACTIVE_DATE, REVISION_COUNT,
                                     ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 831, 'REVERSE11LICENSEE0001111222AAA11', SYSDATE, NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_USER_XREF WHERE ILCR_MILL_ID = 831 AND USER_GUID = 'REVERSE11LICENSEE0001111222AAA11');
INSERT INTO THE.ILCR_MILL_USER_XREF (ILCR_MILL_ID, USER_GUID, ACTIVE_DATE, INACTIVE_DATE, REVISION_COUNT,
                                     ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 831, 'REVERSE11AUDITOR000111122223AAA1', SYSDATE, NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_USER_XREF WHERE ILCR_MILL_ID = 831 AND USER_GUID = 'REVERSE11AUDITOR000111122223AAA1');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE,
                                         MILL_SILVICULTUR_STATUS_CODE, REPORT_COMPLETED_IND, REVISION_COUNT,
                                         AUDITOR_MILL_ID, AUDITOR_USER_GUID, LICENSEE_MILL_ID,
                                         LICENSEE_USER_GUID, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID,
                                         UPDATE_TIMESTAMP)
  SELECT 2021, 831, 'D', 'V', 'N', 0, 831, 'REVERSE11AUDITOR000111122223AAA1', 831, 'REVERSE11LICENSEE0001111222AAA11',
         'SEED', SYSTIMESTAMP, 'SEED', SYSTIMESTAMP FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_REPORT_STATUS WHERE REPORT_YEAR = 2021 AND ILCR_MILL_ID = 831);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 831, c.ID, 'D', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE
    FROM (SELECT '1' ID FROM DUAL UNION ALL SELECT '2' FROM DUAL UNION ALL SELECT '3' FROM DUAL
          UNION ALL SELECT '4' FROM DUAL UNION ALL SELECT '5' FROM DUAL UNION ALL SELECT '6' FROM DUAL
          UNION ALL SELECT '7' FROM DUAL UNION ALL SELECT '8' FROM DUAL UNION ALL SELECT '9' FROM DUAL
          UNION ALL SELECT '10' FROM DUAL) c
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 831 AND r.ILCR_CATEGORY_ID = c.ID);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 831, '11', 'V', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 831 AND r.ILCR_CATEGORY_ID = '11');
INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID)
  SELECT 9466, 2021, 831, '11', 'Submit Racing Block', 8801, 5, 'N', NULL, 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.BASIC_SILVICULTURE_REPORT WHERE BASIC_SILVICULTURE_REPORT_ID = 9466);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5920, NULL, 9466, 24, NULL, 5000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5920);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5921, NULL, 9466, 23, NULL, 4000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5921);
-- ================================================================================================
-- Mill 832 -- Sch11 Draft Or Verify Racing Milling (MILL_NUMBER 1832). 1-10 at D, silviculture at S.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID)
  SELECT 832, 'Sch11 Draft Or Verify Racing Milling', 1832, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.MILL WHERE MILL_ID = 832);
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID)
  SELECT 832, 'ACT', 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_STATUS_XREF WHERE ILCR_MILL_STATUS_XREF_ID = 832);
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE,
                                         MILL_SILVICULTUR_STATUS_CODE, REPORT_COMPLETED_IND, REVISION_COUNT,
                                         AUDITOR_MILL_ID, AUDITOR_USER_GUID, LICENSEE_MILL_ID,
                                         LICENSEE_USER_GUID, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID,
                                         UPDATE_TIMESTAMP)
  SELECT 2021, 832, 'D', 'S', 'N', 0, NULL, NULL, NULL, NULL,
         'SEED', SYSTIMESTAMP, 'SEED', SYSTIMESTAMP FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_REPORT_STATUS WHERE REPORT_YEAR = 2021 AND ILCR_MILL_ID = 832);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 832, c.ID, 'D', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE
    FROM (SELECT '1' ID FROM DUAL UNION ALL SELECT '2' FROM DUAL UNION ALL SELECT '3' FROM DUAL
          UNION ALL SELECT '4' FROM DUAL UNION ALL SELECT '5' FROM DUAL UNION ALL SELECT '6' FROM DUAL
          UNION ALL SELECT '7' FROM DUAL UNION ALL SELECT '8' FROM DUAL UNION ALL SELECT '9' FROM DUAL
          UNION ALL SELECT '10' FROM DUAL) c
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 832 AND r.ILCR_CATEGORY_ID = c.ID);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 832, '11', 'A', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 832 AND r.ILCR_CATEGORY_ID = '11');
INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID)
  SELECT 9467, 2021, 832, '11', 'Two Exits Block', 8801, 5, 'N', NULL, 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.BASIC_SILVICULTURE_REPORT WHERE BASIC_SILVICULTURE_REPORT_ID = 9467);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5922, NULL, 9467, 24, NULL, 5000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5922);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5923, NULL, 9467, 23, NULL, 4000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5923);
-- ================================================================================================
-- Mill 833 -- Sch11 Reversal Null Milling (MILL_NUMBER 1833). 1-10 at D, silviculture at NULL.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID)
  SELECT 833, 'Sch11 Reversal Null Milling', 1833, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.MILL WHERE MILL_ID = 833);
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID)
  SELECT 833, 'ACT', 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_STATUS_XREF WHERE ILCR_MILL_STATUS_XREF_ID = 833);
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE,
                                         MILL_SILVICULTUR_STATUS_CODE, REPORT_COMPLETED_IND, REVISION_COUNT,
                                         AUDITOR_MILL_ID, AUDITOR_USER_GUID, LICENSEE_MILL_ID,
                                         LICENSEE_USER_GUID, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID,
                                         UPDATE_TIMESTAMP)
  SELECT 2021, 833, 'D', NULL, 'N', 0, NULL, NULL, NULL, NULL,
         'SEED', SYSTIMESTAMP, 'SEED', SYSTIMESTAMP FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_REPORT_STATUS WHERE REPORT_YEAR = 2021 AND ILCR_MILL_ID = 833);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 833, c.ID, 'D', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE
    FROM (SELECT '1' ID FROM DUAL UNION ALL SELECT '2' FROM DUAL UNION ALL SELECT '3' FROM DUAL
          UNION ALL SELECT '4' FROM DUAL UNION ALL SELECT '5' FROM DUAL UNION ALL SELECT '6' FROM DUAL
          UNION ALL SELECT '7' FROM DUAL UNION ALL SELECT '8' FROM DUAL UNION ALL SELECT '9' FROM DUAL
          UNION ALL SELECT '10' FROM DUAL) c
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 833 AND r.ILCR_CATEGORY_ID = c.ID);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 833, '11', 'D', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 833 AND r.ILCR_CATEGORY_ID = '11');
INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID)
  SELECT 9468, 2021, 833, '11', 'Null Status Block', 8801, 5, 'N', NULL, 0, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.BASIC_SILVICULTURE_REPORT WHERE BASIC_SILVICULTURE_REPORT_ID = 9468);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5924, NULL, 9468, 24, NULL, 5000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5924);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID)
  SELECT 5925, NULL, 9468, 23, NULL, 4000, NULL, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_COST_REPORT_DETAIL WHERE ILCR_COST_REPORT_DETAIL_ID = 5925);
-- ================================================================================================
-- Mill 834 -- Sch11 Set To Draft Empty Milling (MILL_NUMBER 1834). 1-10 at D, silviculture at S.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID)
  SELECT 834, 'Sch11 Set To Draft Empty Milling', 1834, 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.MILL WHERE MILL_ID = 834);
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID)
  SELECT 834, 'ACT', 'SEED' FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_STATUS_XREF WHERE ILCR_MILL_STATUS_XREF_ID = 834);
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE,
                                         MILL_SILVICULTUR_STATUS_CODE, REPORT_COMPLETED_IND, REVISION_COUNT,
                                         AUDITOR_MILL_ID, AUDITOR_USER_GUID, LICENSEE_MILL_ID,
                                         LICENSEE_USER_GUID, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID,
                                         UPDATE_TIMESTAMP)
  SELECT 2021, 834, 'D', 'S', 'N', 0, NULL, NULL, NULL, NULL,
         'SEED', SYSTIMESTAMP, 'SEED', SYSTIMESTAMP FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_MILL_REPORT_STATUS WHERE REPORT_YEAR = 2021 AND ILCR_MILL_ID = 834);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 834, c.ID, 'D', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE
    FROM (SELECT '1' ID FROM DUAL UNION ALL SELECT '2' FROM DUAL UNION ALL SELECT '3' FROM DUAL
          UNION ALL SELECT '4' FROM DUAL UNION ALL SELECT '5' FROM DUAL UNION ALL SELECT '6' FROM DUAL
          UNION ALL SELECT '7' FROM DUAL UNION ALL SELECT '8' FROM DUAL UNION ALL SELECT '9' FROM DUAL
          UNION ALL SELECT '10' FROM DUAL) c
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 834 AND r.ILCR_CATEGORY_ID = c.ID);
INSERT INTO THE.ILCR_REPORT_CATEGORY (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CATEGORY_STATE_CODE,
                                      REPORTABLE_DETAIL_IND, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP,
                                      UPDATE_USERID, UPDATE_TIMESTAMP)
  SELECT 2021, 834, '11', 'A', 'Y', 0, 'SEED', SYSDATE, 'SEED', SYSDATE FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM THE.ILCR_REPORT_CATEGORY r
                      WHERE r.REPORT_YEAR = 2021 AND r.ILCR_MILL_ID = 834 AND r.ILCR_CATEGORY_ID = '11');
-- Zero locations: the one Schedule 11 check is vacuously MET.
