-- Story 4.4 seed EXTENSION (never edit V1-V9). Schedule 3 sub-page (item 124 Other Acceptable /
-- item 38 Included Unacceptable) fixtures. Detail ids 55xx (free). Cost items 124/38 registered for
-- hygiene (no FK in the test snapshot, per V5). Mills:
--   574 GET-list (seeded 2 OA groups + 1 unaccept + Annual Rents) | 575 empty (lifecycle/validation/404)
--   552 non-Draft ('S') → write 409.
INSERT INTO THE.ILCR_REPORT_COST_ITEM (ILCR_REPORT_COST_ITEM_ID, ITEM_NAME, ILCR_CATEGORY_ID, ILCR_SUBCATEGORY_ID, ENTRY_USERID) VALUES (124, 'Other Acceptable Costs', '3', '1', 'SEED');
INSERT INTO THE.ILCR_REPORT_COST_ITEM (ILCR_REPORT_COST_ITEM_ID, ITEM_NAME, ILCR_CATEGORY_ID, ILCR_SUBCATEGORY_ID, ENTRY_USERID) VALUES (38,  'Included Unacceptable Costs', '3', '1', 'SEED');

-- ---- Mill 574: ACT/Draft, cat-3 summary 1050. Seeded read fixtures for the GET-list tests ----
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID) VALUES (574, 'Sch3 SubPage Read Mill', 574, 'SEED');
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID) VALUES (574, 'ACT', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2021, 574, 'D', 'SEED');
INSERT INTO THE.ILCR_REPORT_SUMMARY (ILCR_REPORT_SUMMARY_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, ENTRY_USERID) VALUES (1050, 2021, 574, '3', 'SEED');
-- Other Acceptable group 1 ("Consulting"): TOT 800 / PO&P 300 -> crown 500.
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, COMMENTS, ENTRY_USERID) VALUES (5501, 1050, 124, NULL, 800, 'Consulting', 'SCH3_2_TOT_GRP1', 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, COMMENTS, ENTRY_USERID) VALUES (5502, 1050, 124, NULL, 300, 'Consulting', 'SCH3_2_POP_GRP1', 'SEED');
-- Other Acceptable group 2 ("Travel"): TOT 600 / PO&P 200 -> crown 400.
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, COMMENTS, ENTRY_USERID) VALUES (5503, 1050, 124, NULL, 600, 'Travel', 'SCH3_2_TOT_GRP2', 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, COMMENTS, ENTRY_USERID) VALUES (5504, 1050, 124, NULL, 200, 'Travel', 'SCH3_2_POP_GRP2', 'SEED');
-- One Included Unacceptable row ("Penalty") total 250; and Annual Rents (item 29) Harvest 777.
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (5505, 1050, 38, NULL, 250, 'Penalty', 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (5506, 1050, 29, NULL, 777, NULL, 'SEED');

-- ---- Mill 575: ACT/Draft, cat-3 summary 1051. Empty sub-pages (lifecycle / validation / 404) ----
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID) VALUES (575, 'Sch3 SubPage Write Mill', 575, 'SEED');
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID) VALUES (575, 'ACT', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2021, 575, 'D', 'SEED');
INSERT INTO THE.ILCR_REPORT_SUMMARY (ILCR_REPORT_SUMMARY_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, ENTRY_USERID) VALUES (1051, 2021, 575, '3', 'SEED');

-- ---- Mill 552: ACT/Submitted ('S'), cat-3 summary 1052. Non-Draft -> sub-page writes 409 ----
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID) VALUES (552, 'Sch3 SubPage NonDraft Mill', 552, 'SEED');
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID) VALUES (552, 'ACT', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2021, 552, 'S', 'SEED');
INSERT INTO THE.ILCR_REPORT_SUMMARY (ILCR_REPORT_SUMMARY_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, ENTRY_USERID) VALUES (1052, 2021, 552, '3', 'SEED');

COMMIT;
