-- Minimal THE snapshot for the UC-SCH1-001 (Schedule 1) slice. TEST-SCOPE ONLY.
-- The app executes NO runtime DDL (AD-2); this exists solely so acceptance *IT tests run against a
-- real Oracle dialect (Testcontainers oracle-free). Only the 8 tables the slice touches, with only
-- the columns the slice's queries/seed need. Later stories EXTEND this snapshot, never fork it.
-- Connected as user THE (see AbstractOracleIT), so THE.<table> resolves as the current schema.

CREATE TABLE THE.MILL (
  MILL_ID          NUMBER(10)    PRIMARY KEY,
  MILL_NAME        VARCHAR2(100),
  MILL_NUMBER      NUMBER(15),
  ENTRY_USERID     VARCHAR2(30),
  ENTRY_TIMESTAMP  TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE THE.ILCR_MILL_STATUS_XREF (
  ILCR_MILL_STATUS_XREF_ID NUMBER(10) PRIMARY KEY,
  ILCR_MILL_STATUS_CODE    VARCHAR2(3),
  REVISION_COUNT           NUMBER(10) DEFAULT 0,
  ENTRY_USERID             VARCHAR2(30),
  ENTRY_TIMESTAMP          TIMESTAMP DEFAULT SYSTIMESTAMP,
  UPDATE_USERID            VARCHAR2(30),
  UPDATE_TIMESTAMP         TIMESTAMP
);

CREATE TABLE THE.ILCR_REPORTING_PERIOD (
  REPORT_YEAR                NUMBER(10) PRIMARY KEY,
  REPORT_OFFICIAL_START_DATE DATE,
  REPORT_OFFICIAL_END_DATE   DATE,
  REVISION_COUNT             NUMBER(10) DEFAULT 0,
  ENTRY_USERID               VARCHAR2(30),
  ENTRY_TIMESTAMP            TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE THE.ILCR_MILL_REPORT_STATUS_CODE (
  ILCR_MILL_REPORT_STATUS_CODE VARCHAR2(1) PRIMARY KEY,
  DESCRIPTION                  VARCHAR2(120)
);

CREATE TABLE THE.ILCR_MILL_REPORT_STATUS (
  REPORT_YEAR                  NUMBER(10),
  ILCR_MILL_ID                 NUMBER(10),
  ILCR_MILL_REPORT_STATUS_CODE VARCHAR2(1),
  MILL_SILVICULTUR_STATUS_CODE VARCHAR2(1),
  REPORT_COMPLETED_IND         VARCHAR2(1),
  REVISION_COUNT               NUMBER(10) DEFAULT 0,
  ENTRY_USERID                 VARCHAR2(30),
  ENTRY_TIMESTAMP              TIMESTAMP DEFAULT SYSTIMESTAMP,
  UPDATE_USERID                VARCHAR2(30),
  UPDATE_TIMESTAMP             TIMESTAMP,
  CONSTRAINT PK_ILCR_MILL_REPORT_STATUS PRIMARY KEY (REPORT_YEAR, ILCR_MILL_ID)
);

CREATE TABLE THE.ILCR_REPORT_COST_ITEM (
  ILCR_REPORT_COST_ITEM_ID NUMBER(10) PRIMARY KEY,
  ITEM_NAME                VARCHAR2(120),
  LUMP_SUM_IND             VARCHAR2(1),
  ILCR_CATEGORY_ID         VARCHAR2(3),
  ILCR_SUBCATEGORY_ID      VARCHAR2(3),
  REVISION_COUNT           NUMBER(10) DEFAULT 0,
  ENTRY_USERID             VARCHAR2(30),
  ENTRY_TIMESTAMP          TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE THE.ILCR_REPORT_SUMMARY (
  ILCR_REPORT_SUMMARY_ID NUMBER(10) PRIMARY KEY,
  REPORT_YEAR            NUMBER(10),
  ILCR_MILL_ID          NUMBER(10),
  ILCR_CATEGORY_ID      VARCHAR2(3),
  LOCATION              VARCHAR2(120),
  CROWN_VOLUME          NUMBER(15),
  COMMENTS              VARCHAR2(2000),
  REVISION_COUNT        NUMBER(10) DEFAULT 0,
  ENTRY_USERID          VARCHAR2(30),
  ENTRY_TIMESTAMP       TIMESTAMP DEFAULT SYSTIMESTAMP,
  UPDATE_USERID         VARCHAR2(30),
  UPDATE_TIMESTAMP      TIMESTAMP
);

CREATE TABLE THE.ILCR_COST_REPORT_DETAIL (
  ILCR_COST_REPORT_DETAIL_ID NUMBER(10) PRIMARY KEY,
  ILCR_REPORT_SUMMARY_ID     NUMBER(10),
  ILCR_REPORT_COST_ITEM_ID   NUMBER(10),
  VOLUME                     NUMBER(18,4),
  COST                       NUMBER(15),
  ITEM_DESCRIPTION           VARCHAR2(30),
  COMMENTS                   VARCHAR2(2000),
  REVISION_COUNT             NUMBER(10) DEFAULT 0,
  ENTRY_USERID               VARCHAR2(30),
  ENTRY_TIMESTAMP            TIMESTAMP DEFAULT SYSTIMESTAMP,
  UPDATE_USERID              VARCHAR2(30),
  UPDATE_TIMESTAMP           TIMESTAMP
);
