-- Story 9.2 (UC-SCH9-001 write side) seed: Schedule 9 WRITE + Check Status fixtures. TEST-SCOPE ONLY.
-- Seeds into the THE.CONTRACTUAL_WORK_REPORT table and the CONTRACTUAL_WORK_REPORT_ID FK column on the
-- shared ILCR_COST_REPORT_DETAIL that V20260813 (the 9.1 read seed) created; never edits that seed.
--
-- TIMESTAMP VERSION (db/README.md escape hatch): the next free timestamp after V20260813. Re-scan
-- before pushing; on collision bump THIS migration, never a merged one.
--
-- Delivery-faithfulness gates (Story 9.2 T1, confirmed against the seeded image):
--   (i)  CONTRACTUAL_WORK_REPORT's four audit columns are NOT NULL with NO defaults (V20260813), so
--        the write path must stamp all four -- an omission fails here as it would in delivery. The
--        cost line's audit columns already exist on ILCR_COST_REPORT_DETAIL (V1: ENTRY_TIMESTAMP
--        DEFAULT SYSTIMESTAMP, UPDATE_TIMESTAMP), so gate (ii)'s ALTER is unnecessary -- the columns
--        are present; the writes stamp them explicitly regardless.
--   (ii) Both PKs are drawn from the shared delivery sequences the write repo calls at runtime:
--        CONTRACTUAL_WORK_REPORT_ID <- ILCR_REPORT_COMMON_SEQ (START 9500), ILCR_COST_REPORT_DETAIL_ID
--        <- ILCR_COST_REPORT_DETAIL_SEQ (START 9000). Both created by earlier seeds (V11/V4). Fixture
--        ids sit BELOW both starts so a runtime-drawn id can never collide with a seeded one.
--
-- ID ranges (registered in db/README.md): CONTRACTUAL_WORK_REPORT_ID 9120-9149 (in Schedule 9's
-- 9101-9199 band, clear of the read seed's 9101-9103/9110/9190/9191), ILCR_COST_REPORT_DETAIL_ID
-- 8485-8499 (the free remainder of Schedule 9's 8481-8499 band; 8481-8484/8490/8491 are the read
-- seed's).
--
-- Isolation model (the Schedule 5 7.2 lesson): the shared container makes cleanup-free isolation
-- context-based, a context is (mill, YEAR), and each write suite owns its own mill so a @PreAuthorize
-- or Draft-gate regression cannot mutate another suite's fixture.

-- Reference codes the write path force-selection-validates (FLD-005). M3/OT units, A/O sources and BZ1
-- are already seeded (V20260812/V20260813); add the two the conditional-description tests need:
-- unit 'O' (Other -> enables Unit Other Description) and source 'S' (Subcontract -> enables Source
-- Other Description, alongside 'O'). Legacy Constant.UNIT_CODES.O / CONTRACTUAL_SOURCE_CODES.S.
INSERT INTO THE.ILCR_UNIT_CODE (ILCR_UNIT_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
  VALUES ('O', 'Other', DATE '2000-01-01', NULL, SYSTIMESTAMP);
INSERT INTO THE.ILCR_CONTRACTUAL_SOURCE_CODE VALUES ('S', 'Subcontract');

-- ================================================================================================
-- Mill 700 -- the write playground (Schedule9WriteIT). ACT + Draft, one destructive concern per year:
--   2016  no records                 -> addRecord (S01 single; S02 multiple-in-session)
--   2017  record 9120                -> the edit-in-place target (S07)
--   2018  record 9121                -> the delete target (S10)
--   2019  record 9122, REVISION_COUNT 3 -> the AR11 stale-vs-valid token tests
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID) VALUES (700, 'Sch9 Write Milling', 700, 'SEED');
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID) VALUES (700, 'ACT', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2016, 700, 'D', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2017, 700, 'D', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2018, 700, 'D', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2019, 700, 'D', 'SEED');

-- 2017: the edit target. item 108 (Cattleguard), unit M3, source A (non-enabling), BEC BZ1, units 10.0,
-- cost 5000, side slope NULL (item 108 does not enable it). REVISION_COUNT 0. Distinct cost so a
-- mis-keyed cost-line update is detectable.
INSERT INTO THE.CONTRACTUAL_WORK_REPORT (CONTRACTUAL_WORK_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CONTRACTOR_ID, SIDE_SLOPE_PCT, PERFORMED_UNIT, ILCR_UNIT_CODE, UNIT_DESCRIPTION, ILCR_CONTRACTUAL_SOURCE_CODE, SOURCE_DESCRIPTION, BEC_ZONE_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (9120, 2017, 700, '9', 'CTR-EDIT', NULL, 10.0, 'M3', NULL, 'A', NULL, 'BZ1', 'Edit target.', 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CONTRACTUAL_WORK_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, COST, REVISION_COUNT, ENTRY_USERID) VALUES (8485, 9120, 108, 5000, 0, 'SEED');

-- 2018: the delete target. item 109 (Pipeline Crossing).
INSERT INTO THE.CONTRACTUAL_WORK_REPORT (CONTRACTUAL_WORK_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CONTRACTOR_ID, SIDE_SLOPE_PCT, PERFORMED_UNIT, ILCR_UNIT_CODE, UNIT_DESCRIPTION, ILCR_CONTRACTUAL_SOURCE_CODE, SOURCE_DESCRIPTION, BEC_ZONE_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (9121, 2018, 700, '9', 'CTR-DEL', NULL, 20.0, 'M3', NULL, 'A', NULL, 'BZ1', 'Delete target.', 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CONTRACTUAL_WORK_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, COST, REVISION_COUNT, ENTRY_USERID) VALUES (8486, 9121, 109, 3000, 0, 'SEED');

-- 2019: the optimistic-lock target. REVISION_COUNT 3 so a test hard-coding 0 fails rather than passes.
INSERT INTO THE.CONTRACTUAL_WORK_REPORT (CONTRACTUAL_WORK_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CONTRACTOR_ID, SIDE_SLOPE_PCT, PERFORMED_UNIT, ILCR_UNIT_CODE, UNIT_DESCRIPTION, ILCR_CONTRACTUAL_SOURCE_CODE, SOURCE_DESCRIPTION, BEC_ZONE_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (9122, 2019, 700, '9', 'CTR-LOCK', NULL, 30.0, 'M3', NULL, 'A', NULL, 'BZ1', 'Lock target.', 3, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CONTRACTUAL_WORK_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, COST, REVISION_COUNT, ENTRY_USERID) VALUES (8487, 9122, 110, 4000, 0, 'SEED');

-- ================================================================================================
-- Mill 701 -- 1-10 track 'S' (non-Draft) -> the write-gate 409 (AC1). One record whose untouched
-- fingerprint is the nothing-persisted proof for all three mutations.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID) VALUES (701, 'Sch9 Locked Milling', 701, 'SEED');
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID) VALUES (701, 'ACT', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2021, 701, 'S', 'SEED');
INSERT INTO THE.CONTRACTUAL_WORK_REPORT (CONTRACTUAL_WORK_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CONTRACTOR_ID, SIDE_SLOPE_PCT, PERFORMED_UNIT, ILCR_UNIT_CODE, UNIT_DESCRIPTION, ILCR_CONTRACTUAL_SOURCE_CODE, SOURCE_DESCRIPTION, BEC_ZONE_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (9130, 2021, 701, '9', 'CTR-LCK', NULL, 40.0, 'M3', NULL, 'A', NULL, 'BZ1', 'Submitted, not editable.', 2, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CONTRACTUAL_WORK_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, COST, REVISION_COUNT, ENTRY_USERID) VALUES (8488, 9130, 108, 8000, 0, 'SEED');

-- ================================================================================================
-- Mill 702 -- Check Status ALL MET (S09). Two records, every one of the eight fields satisfied ->
-- requirementsMet:true, ONE scheduleRequirementsMetMsg (SUC-002), no error lines.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID) VALUES (702, 'Sch9 Complete Milling', 702, 'SEED');
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID) VALUES (702, 'ACT', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2021, 702, 'D', 'SEED');
INSERT INTO THE.CONTRACTUAL_WORK_REPORT (CONTRACTUAL_WORK_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CONTRACTOR_ID, SIDE_SLOPE_PCT, PERFORMED_UNIT, ILCR_UNIT_CODE, UNIT_DESCRIPTION, ILCR_CONTRACTUAL_SOURCE_CODE, SOURCE_DESCRIPTION, BEC_ZONE_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (9140, 2021, 702, '9', 'CTR-OK1', NULL, 15.0, 'M3', NULL, 'A', NULL, 'BZ1', NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CONTRACTUAL_WORK_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, COST, REVISION_COUNT, ENTRY_USERID) VALUES (8492, 9140, 108, 5000, 0, 'SEED');
-- 9141: item 111 (road deactivation) with a VALID side slope (50) -> the enabled-and-in-range branch.
INSERT INTO THE.CONTRACTUAL_WORK_REPORT (CONTRACTUAL_WORK_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CONTRACTOR_ID, SIDE_SLOPE_PCT, PERFORMED_UNIT, ILCR_UNIT_CODE, UNIT_DESCRIPTION, ILCR_CONTRACTUAL_SOURCE_CODE, SOURCE_DESCRIPTION, BEC_ZONE_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (9141, 2021, 702, '9', 'CTR-OK2', 50, 25.0, 'M3', NULL, 'A', NULL, 'BZ1', NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CONTRACTUAL_WORK_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, COST, REVISION_COUNT, ENTRY_USERID) VALUES (8493, 9141, 111, 6000, 0, 'SEED');

-- ================================================================================================
-- Mill 703 -- Check Status ISSUES (S09). Records in served (id) order, each isolating one branch:
--   9142  blank units + blank cost   -> Number of Units + Cost$ "Value Required" (the Save-vs-Check
--                                       gap: both SAVE but Check flags them). Everything else valid.
--   9143  item 111, SIDE_SLOPE_PCT 100 -> Side Slope % "Entered value must be between 0 and 99." (100
--                                       SAVEs at <=100 but the Check bound is 99). Everything else valid.
--   9144  CONTRACTOR_ID NULL          -> Company ID "Value Required" (a required-select omission).
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID) VALUES (703, 'Sch9 Incomplete Milling', 703, 'SEED');
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID) VALUES (703, 'ACT', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2021, 703, 'D', 'SEED');
INSERT INTO THE.CONTRACTUAL_WORK_REPORT (CONTRACTUAL_WORK_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CONTRACTOR_ID, SIDE_SLOPE_PCT, PERFORMED_UNIT, ILCR_UNIT_CODE, UNIT_DESCRIPTION, ILCR_CONTRACTUAL_SOURCE_CODE, SOURCE_DESCRIPTION, BEC_ZONE_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (9142, 2021, 703, '9', 'CTR-BLK', NULL, NULL, 'M3', NULL, 'A', NULL, 'BZ1', NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CONTRACTUAL_WORK_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, COST, REVISION_COUNT, ENTRY_USERID) VALUES (8494, 9142, 108, NULL, 0, 'SEED');
INSERT INTO THE.CONTRACTUAL_WORK_REPORT (CONTRACTUAL_WORK_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CONTRACTOR_ID, SIDE_SLOPE_PCT, PERFORMED_UNIT, ILCR_UNIT_CODE, UNIT_DESCRIPTION, ILCR_CONTRACTUAL_SOURCE_CODE, SOURCE_DESCRIPTION, BEC_ZONE_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (9143, 2021, 703, '9', 'CTR-SS', 100, 12.0, 'M3', NULL, 'A', NULL, 'BZ1', NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CONTRACTUAL_WORK_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, COST, REVISION_COUNT, ENTRY_USERID) VALUES (8495, 9143, 112, 7000, 0, 'SEED');
INSERT INTO THE.CONTRACTUAL_WORK_REPORT (CONTRACTUAL_WORK_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CONTRACTOR_ID, SIDE_SLOPE_PCT, PERFORMED_UNIT, ILCR_UNIT_CODE, UNIT_DESCRIPTION, ILCR_CONTRACTUAL_SOURCE_CODE, SOURCE_DESCRIPTION, BEC_ZONE_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (9144, 2021, 703, '9', NULL, NULL, 18.0, 'M3', NULL, 'A', NULL, 'BZ1', NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CONTRACTUAL_WORK_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, COST, REVISION_COUNT, ENTRY_USERID) VALUES (8496, 9144, 108, 9000, 0, 'SEED');

-- ================================================================================================
-- Mill 704 -- Check Status with ZERO records -> vacuously MET (requirementsMet:true, SUC-002 banner,
-- no error lines), NOT a 404. A valid, ACTIVE Draft mill/year that simply stores nothing.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID) VALUES (704, 'Sch9 Empty Milling', 704, 'SEED');
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID) VALUES (704, 'ACT', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2021, 704, 'D', 'SEED');

-- ================================================================================================
-- Mill 705 -- Schedule9WriteValidationIT. Draft 2021 (add attempts: rejections mutate nothing; the
-- boundary-accept adds persist). 2022 kept free for a second add stream. No seeded records: the
-- validation tests POST bodies and assert the 400 (FLD-001..005) or the boundary 200.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID) VALUES (705, 'Sch9 Validation Milling', 705, 'SEED');
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID) VALUES (705, 'ACT', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2021, 705, 'D', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2022, 705, 'D', 'SEED');

-- ================================================================================================
-- Mill 706 -- owned SOLELY by Schedule9WriteAuthorizationIT. Track 'S' DELIBERATELY: the "authorized"
-- proof needs authorization to PASS and then the Draft gate to stop the write, so an authorized caller
-- gets 409 (proof @PreAuthorize let it through) while an unauthorized caller gets 403 -- and nothing is
-- written either way.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID) VALUES (706, 'Sch9 Authz Milling', 706, 'SEED');
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID) VALUES (706, 'ACT', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2021, 706, 'S', 'SEED');
INSERT INTO THE.CONTRACTUAL_WORK_REPORT (CONTRACTUAL_WORK_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CONTRACTOR_ID, SIDE_SLOPE_PCT, PERFORMED_UNIT, ILCR_UNIT_CODE, UNIT_DESCRIPTION, ILCR_CONTRACTUAL_SOURCE_CODE, SOURCE_DESCRIPTION, BEC_ZONE_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (9131, 2021, 706, '9', 'CTR-AUTH', NULL, 5.0, 'M3', NULL, 'A', NULL, 'BZ1', 'Authz target.', 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CONTRACTUAL_WORK_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, COST, REVISION_COUNT, ENTRY_USERID) VALUES (8489, 9131, 108, 1000, 0, 'SEED');

COMMIT;
