-- Story 7.4 (UC-SCH5-001 sub-pages) seed: the itemized Other Camp (62) / Other Access (68) expense
-- rows and the contexts that exercise them. TEST-SCOPE ONLY. Seeds into the THE.CAMP_REPORT table
-- and the CAMP_REPORT_ID FK column that V34 created; never edits either.
--
-- ================================================================================================
-- TIMESTAMP VERSION, per db/README.md:26-28 and the V20260807 precedent. The integer convention has
-- now collided four times (schedules 2, 11, 6, and V34's near-miss); 20260812 orders after
-- 20260807, so this applies immediately after the Story 7.2 fixtures it sits beside, and no future
-- merge can force a renumber of this file or of anyone else's.
-- ================================================================================================
--
-- ------------------------------------------------------------------------------------------------
-- SNAPSHOT WIDENING (Task 1 gate (i)) -- the one DDL statement here, and it is a FIDELITY fix.
--
-- Delivery declares ITEM_DESCRIPTION as VARCHAR2(120) with CHAR_USED = 'B' (byte semantics on an
-- AL32UTF8 database). The V1 snapshot declares VARCHAR2(30), which is BYTE semantics too by Oracle's
-- default. That gap makes a green IT prove less than it appears to: a 30-character description
-- containing any multi-byte character is ~90 bytes, which delivery accepts and a 30-BYTE column
-- rejects with ORA-12899 -- so the local suite would fail on input production accepts, or (worse,
-- once someone "fixes" it by using ASCII everywhere) silently stop covering the case.
--
-- Widening to match delivery also makes one assertion honest: @MaxByteLength(120) behind
-- @Size(max = 30) can NEVER fire, because a 30-CHARACTER string carries at most 90 UTF-8 bytes
-- (thirty 3-byte BMP characters; a 4-byte character is a surrogate pair and costs two of the thirty,
-- so it is less byte-dense, not more). Schedule5SubPageValidationIT therefore asserts that a
-- 30-character multibyte description is ACCEPTED, which is only meaningful against a column wider
-- than 30 bytes -- i.e. only after this widening.
--
-- Safe by construction: these migrations run against a throwaway Testcontainer only and are never
-- applied to the shared dev/prod THE schema (db/README.md:3-7, AD-2 -- no runtime DDL).
-- ------------------------------------------------------------------------------------------------
ALTER TABLE THE.ILCR_COST_REPORT_DETAIL MODIFY (ITEM_DESCRIPTION VARCHAR2(120));

-- ------------------------------------------------------------------------------------------------
-- ID ranges. A NEW block, claimed after scanning every seed migration on disk: the highest
-- ILCR_COST_REPORT_DETAIL_ID in use anywhere is 8438 (V34's read fixtures). This story takes
--   CAMP_REPORT_ID              8700-8719
--   ILCR_COST_REPORT_DETAIL_ID  8720-8799
-- both clear of Schedule 5 write's 8200-8229/8230-8299, Schedule 6's 8301-8399, Schedule 5 read's
-- 8401-8410/8411-8438 and Schedule 8's >= 8500, and both BELOW the sequence starts
-- (ILCR_REPORT_COMMON_SEQ 9500, ILCR_COST_REPORT_DETAIL_SEQ 9000) so ids the app draws at runtime
-- cannot collide with a fixture. Mills 690-693 are likewise new: seeded mill ids stop at 676 and do
-- not resume until 1001. Registered in db/README.md.
--
-- Isolation model (the V21/V32 lesson, restated by V20260807): a context is (mill, YEAR), so every
-- DESTRUCTIVE concern claims its own year on mill 690 and NEVER reuses Story 7.2's mills 670-676.
-- Tests that only assert rejections mutate nothing and may share a year -- their per-row fingerprint
-- is what proves nothing persisted.
--
-- No cost item is inserted: items 62, 68, 141 and 142 are all already registered by V34/V31, and
-- cost-item ids are shared master data (db/README.md:66-68).
-- ------------------------------------------------------------------------------------------------

-- ================================================================================================
-- Mill 690 -- the sub-page write playground (Schedule5SubPageIT). ACT + Draft 2016-2023:
--   2016  camp 8700, three item-62 rows + two item-68 rows -> the reconcile round trip
--   2017  camp 8701, two item-62 rows                      -> immediate row DELETE
--   2018  camp 8702, no rows                               -> insert-from-empty, and empty-clears
--   2019  camp 8703, one item-62 row with EVERY cost NULL  -> 7.1 deviation (h)/(L): camp side
--                                                             serves 0, access side serves null
--   2020  camp 8704 + camp 8705                            -> the foreign-row 404 pair (a row of
--                                                             8705 offered to 8704)
--   2021  camp 8706, one item-62 + one item-68 row         -> the cross-ITEM 404 (deviation (O)):
--                                                             an item-68 row id offered to the camp
--                                                             page must 404, not cross-write
--   2022  camp 8707, backdated ENTRY_* (2020-01-01)        -> the ENTRY_*-unchanged-on-UPDATE proof.
--                                                             Backdated deliberately: the audit
--                                                             columns are DATE (gate (i)), so two
--                                                             writes inside one second are
--                                                             indistinguishable and a same-day
--                                                             baseline could not falsify a re-stamp.
--   2023  camp 8708, one item-62 row cost 9999999          -> rejection probes only; mutates nothing
--   2028  camp 8718, one item-62 row with desc AND cost    -> the UPDATE-to-NULL proof (a cleared
--                                                             field is cleared, not kept)
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID) VALUES (690, 'Sch5 SubPage Milling', 690, 'SEED');
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID) VALUES (690, 'ACT', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2016, 690, 'D', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2017, 690, 'D', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2018, 690, 'D', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2019, 690, 'D', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2020, 690, 'D', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2021, 690, 'D', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2022, 690, 'D', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2023, 690, 'D', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2024, 690, 'D', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2025, 690, 'D', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2026, 690, 'D', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2027, 690, 'D', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2028, 690, 'D', 'SEED');

-- 2016: the reconcile round trip. Camp volume 120000 is the item-141/142 stamp, so the CAMP footer
-- volume must be 3 x 120000 = 360000 while the ACCESS footer volume stays 120000 -- deviation (C)
-- made observable by seeding a DIFFERENT row count on each side.
INSERT INTO THE.CAMP_REPORT (CAMP_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CAMP_NAME, DISTANCE_TO_OPERATING_AREA, CAMP_SIZE_CAPACITY, ASSOCIATED_CAMP_VOLUME, ISOLATED_CAMP_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8700, 2016, 690, '5', 'Reconcile Camp', 42.50, 60, 120000, 'Y', NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, REVISION_COUNT, ENTRY_USERID) VALUES (8720, 8700, 141, 120000, NULL, 0, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, REVISION_COUNT, ENTRY_USERID) VALUES (8721, 8700, 142, 120000, NULL, 0, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, REVISION_COUNT, ENTRY_USERID) VALUES (8722, 8700, 62, NULL, 10000, 'Generator Fuel', 0, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, REVISION_COUNT, ENTRY_USERID) VALUES (8723, 8700, 62, NULL,  2500, 'Propane', 0, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, REVISION_COUNT, ENTRY_USERID) VALUES (8724, 8700, 62, NULL,   500, NULL, 0, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, REVISION_COUNT, ENTRY_USERID) VALUES (8725, 8700, 68, NULL,  7000, 'Bridge Rental', 0, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, REVISION_COUNT, ENTRY_USERID) VALUES (8726, 8700, 68, NULL,  3000, 'Culvert Hire', 0, 'SEED');

-- 2017: the immediate-DELETE target.
INSERT INTO THE.CAMP_REPORT (CAMP_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CAMP_NAME, DISTANCE_TO_OPERATING_AREA, CAMP_SIZE_CAPACITY, ASSOCIATED_CAMP_VOLUME, ISOLATED_CAMP_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8701, 2017, 690, '5', 'Delete Row Camp', NULL, NULL, 80000, 'N', NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, REVISION_COUNT, ENTRY_USERID) VALUES (8727, 8701, 141, 80000, NULL, 0, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, REVISION_COUNT, ENTRY_USERID) VALUES (8728, 8701, 62, NULL, 1000, 'Keep Me', 0, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, REVISION_COUNT, ENTRY_USERID) VALUES (8729, 8701, 62, NULL, 2000, 'Delete Me', 0, 'SEED');

-- 2018: no sub-page rows at all -- the DELIVERY-REAL shape (gate (iv): zero camp-parented detail
-- rows exist), so insert-from-empty is the path every real camp will take first.
INSERT INTO THE.CAMP_REPORT (CAMP_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CAMP_NAME, DISTANCE_TO_OPERATING_AREA, CAMP_SIZE_CAPACITY, ASSOCIATED_CAMP_VOLUME, ISOLATED_CAMP_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8702, 2018, 690, '5', 'Empty Camp', NULL, NULL, 50000, 'N', NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, REVISION_COUNT, ENTRY_USERID) VALUES (8730, 8702, 141, 50000, NULL, 0, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, REVISION_COUNT, ENTRY_USERID) VALUES (8731, 8702, 142, 50000, NULL, 0, 'SEED');

-- 2019: 7.1 deviation (h)/(L) made reachable. ONE item-62 row with a NULL cost, one item-68 row with
-- a NULL cost, and NON-NULL item-141/142 volumes. The camp side must serve cost 0 (because
-- CoreUtil.sumDescriptionCostVolumeType flags on the stamped VOLUME as well as the cost) and the
-- access side must serve null (sumDescriptionCostVolumeTypeCostOnly flags on cost alone). Seeding
-- BOTH sides identically is the point: the asymmetry must come from the code, not from the data.
INSERT INTO THE.CAMP_REPORT (CAMP_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CAMP_NAME, DISTANCE_TO_OPERATING_AREA, CAMP_SIZE_CAPACITY, ASSOCIATED_CAMP_VOLUME, ISOLATED_CAMP_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8703, 2019, 690, '5', 'Zero Not Null Camp', NULL, NULL, 60000, 'N', NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, REVISION_COUNT, ENTRY_USERID) VALUES (8732, 8703, 141, 60000, NULL, 0, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, REVISION_COUNT, ENTRY_USERID) VALUES (8733, 8703, 142, 60000, NULL, 0, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, REVISION_COUNT, ENTRY_USERID) VALUES (8734, 8703, 62, NULL, NULL, 'Cost Free Camp Row', 0, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, REVISION_COUNT, ENTRY_USERID) VALUES (8735, 8703, 68, NULL, NULL, 'Cost Free Access Row', 0, 'SEED');

-- 2020: the foreign-row 404 pair. 8705's row offered to 8704 must 404 and leave BOTH camps intact.
INSERT INTO THE.CAMP_REPORT (CAMP_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CAMP_NAME, DISTANCE_TO_OPERATING_AREA, CAMP_SIZE_CAPACITY, ASSOCIATED_CAMP_VOLUME, ISOLATED_CAMP_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8704, 2020, 690, '5', 'Foreign Target Camp', NULL, NULL, 70000, 'N', NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.CAMP_REPORT (CAMP_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CAMP_NAME, DISTANCE_TO_OPERATING_AREA, CAMP_SIZE_CAPACITY, ASSOCIATED_CAMP_VOLUME, ISOLATED_CAMP_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8705, 2020, 690, '5', 'Foreign Donor Camp', NULL, NULL, 70000, 'N', NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, REVISION_COUNT, ENTRY_USERID) VALUES (8736, 8704, 62, NULL, 100, 'Target Row', 0, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, REVISION_COUNT, ENTRY_USERID) VALUES (8737, 8705, 62, NULL, 200, 'Donor Row', 0, 'SEED');

-- 2021: the cross-ITEM 404 (deviation (O)). 8739 is an item-68 row; offering its id to the item-62
-- page must 404 rather than overwrite it, which is exactly what legacy WOULD have done -- its update
-- loop matches a detail id against the camp's entire detail collection with no item check
-- (Schedule5DAO.java:585-595).
INSERT INTO THE.CAMP_REPORT (CAMP_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CAMP_NAME, DISTANCE_TO_OPERATING_AREA, CAMP_SIZE_CAPACITY, ASSOCIATED_CAMP_VOLUME, ISOLATED_CAMP_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8706, 2021, 690, '5', 'Cross Item Camp', NULL, NULL, 90000, 'N', NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, REVISION_COUNT, ENTRY_USERID) VALUES (8738, 8706, 62, NULL, 300, 'Camp Side Row', 0, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, REVISION_COUNT, ENTRY_USERID) VALUES (8739, 8706, 68, NULL, 400, 'Access Side Row', 0, 'SEED');

-- 2022: the ENTRY_*-unchanged proof. ENTRY_TIMESTAMP is backdated to 2020-01-01 so an UPDATE that
-- wrongly re-stamped it would move the value by five years -- detectable despite DATE's one-second
-- granularity. ENTRY_USERID is likewise a value the app can never write ('LEGACYUSER').
INSERT INTO THE.CAMP_REPORT (CAMP_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CAMP_NAME, DISTANCE_TO_OPERATING_AREA, CAMP_SIZE_CAPACITY, ASSOCIATED_CAMP_VOLUME, ISOLATED_CAMP_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8707, 2022, 690, '5', 'Audit Camp', NULL, NULL, 40000, 'N', NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8740, 8707, 62, NULL, 5000, 'Audit Row', 0, 'LEGACYUSER', DATE '2020-01-01', 'LEGACYUSER', DATE '2020-01-01');

-- 2023: rejection probes only -- out-of-range costs, over-long descriptions, fractional costs. The
-- seeded row's fingerprint (cost 9999999, description 'Boundary Row') is the nothing-persisted
-- proof, so NO test here may mutate this year.
INSERT INTO THE.CAMP_REPORT (CAMP_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CAMP_NAME, DISTANCE_TO_OPERATING_AREA, CAMP_SIZE_CAPACITY, ASSOCIATED_CAMP_VOLUME, ISOLATED_CAMP_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8708, 2023, 690, '5', 'Rejection Camp', NULL, NULL, 30000, 'N', NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, REVISION_COUNT, ENTRY_USERID) VALUES (8741, 8708, 141, 30000, NULL, 0, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, REVISION_COUNT, ENTRY_USERID) VALUES (8742, 8708, 62, NULL, 9999999, 'Boundary Row', 0, 'SEED');

-- 2024: the CAMP-FAMILY delete target (BR-09/AC5 -- deleting a camp must take its item-62/68 rows
-- with it). It gets its OWN camp and year rather than reusing 2020's donor/target pair: a family
-- delete destroys the very rows those two tests assert are still intact, which would make this
-- suite order-dependent (the trap Story 7.2 hit twice).
INSERT INTO THE.CAMP_REPORT (CAMP_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CAMP_NAME, DISTANCE_TO_OPERATING_AREA, CAMP_SIZE_CAPACITY, ASSOCIATED_CAMP_VOLUME, ISOLATED_CAMP_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8714, 2024, 690, '5', 'Family Delete Camp', NULL, NULL, 25000, 'N', NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, REVISION_COUNT, ENTRY_USERID) VALUES (8750, 8714, 141, 25000, NULL, 0, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, REVISION_COUNT, ENTRY_USERID) VALUES (8751, 8714, 62, NULL, 800, 'Family Camp Row', 0, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, REVISION_COUNT, ENTRY_USERID) VALUES (8752, 8714, 68, NULL, 900, 'Family Access Row', 0, 'SEED');

-- 2025: the INSERT audit-column target. Its own camp/year so that 2018's insert-from-empty test
-- genuinely starts from empty whatever order JUnit picks -- both tests replace the WHOLE list, so
-- sharing a camp would leave each one's precondition depending on the other's timing.
INSERT INTO THE.CAMP_REPORT (CAMP_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CAMP_NAME, DISTANCE_TO_OPERATING_AREA, CAMP_SIZE_CAPACITY, ASSOCIATED_CAMP_VOLUME, ISOLATED_CAMP_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8715, 2025, 690, '5', 'Audit Insert Camp', NULL, NULL, 35000, 'N', NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, REVISION_COUNT, ENTRY_USERID) VALUES (8753, 8715, 141, 35000, NULL, 0, 'SEED');

-- 2026: the insert+update+delete-in-one-call target. A MIRROR of 2016's camp 8700 (three item-62
-- rows, two item-68 rows, the same 120000 stamp) because 2016 is asserted against by the READ tests
-- and the footer-shape tests -- a reconcile that leaves two rows behind would break their
-- preconditions depending on JUnit's method order.
INSERT INTO THE.CAMP_REPORT (CAMP_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CAMP_NAME, DISTANCE_TO_OPERATING_AREA, CAMP_SIZE_CAPACITY, ASSOCIATED_CAMP_VOLUME, ISOLATED_CAMP_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8716, 2026, 690, '5', 'Reconcile Target Camp', 42.50, 60, 120000, 'Y', NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, REVISION_COUNT, ENTRY_USERID) VALUES (8754, 8716, 141, 120000, NULL, 0, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, REVISION_COUNT, ENTRY_USERID) VALUES (8755, 8716, 142, 120000, NULL, 0, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, REVISION_COUNT, ENTRY_USERID) VALUES (8756, 8716, 62, NULL, 10000, 'Generator Fuel', 0, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, REVISION_COUNT, ENTRY_USERID) VALUES (8757, 8716, 62, NULL,  2500, 'Propane', 0, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, REVISION_COUNT, ENTRY_USERID) VALUES (8758, 8716, 62, NULL,   500, NULL, 0, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, REVISION_COUNT, ENTRY_USERID) VALUES (8759, 8716, 68, NULL,  7000, 'Bridge Rental', 0, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, REVISION_COUNT, ENTRY_USERID) VALUES (8760, 8716, 68, NULL,  3000, 'Culvert Hire', 0, 'SEED');

-- 2027: owned by Schedule5SubPageValidationIT's ACCEPTANCE cases, which must COMMIT to prove
-- acceptance and so cannot use the fingerprint camp (8708/2023) its rejection cases rely on. Its own
-- camp/year rather than borrowing 2018's: that camp belongs to Schedule5SubPageIT, and failsafe runs
-- both classes against the SAME container, so sharing it would couple two suites.
INSERT INTO THE.CAMP_REPORT (CAMP_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CAMP_NAME, DISTANCE_TO_OPERATING_AREA, CAMP_SIZE_CAPACITY, ASSOCIATED_CAMP_VOLUME, ISOLATED_CAMP_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8717, 2027, 690, '5', 'Validation Camp', NULL, NULL, 45000, 'N', NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, REVISION_COUNT, ENTRY_USERID) VALUES (8761, 8717, 141, 45000, NULL, 0, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, REVISION_COUNT, ENTRY_USERID) VALUES (8762, 8717, 142, 45000, NULL, 0, 'SEED');

-- 2028: the UPDATE-to-NULL target (review patch, 2026-08-12). One row seeded with BOTH a description
-- and a cost, so an update sending {description: null, cost: null} proves a cleared field is written
-- NULL rather than silently kept (the NVL regression every other update fixture, all non-null,
-- could not catch). Its own camp/year: the update MUTATES, so it cannot share the fingerprint camp.
INSERT INTO THE.CAMP_REPORT (CAMP_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CAMP_NAME, DISTANCE_TO_OPERATING_AREA, CAMP_SIZE_CAPACITY, ASSOCIATED_CAMP_VOLUME, ISOLATED_CAMP_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8718, 2028, 690, '5', 'Clear Fields Camp', NULL, NULL, 30000, 'N', NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, REVISION_COUNT, ENTRY_USERID) VALUES (8763, 8718, 141, 30000, NULL, 0, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, REVISION_COUNT, ENTRY_USERID) VALUES (8764, 8718, 62, NULL, 4000, 'Clear Me', 0, 'SEED');

-- ================================================================================================
-- Mill 691 -- NON-Draft (Submitted). The write-gate 409 target for every sub-page verb.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID) VALUES (691, 'Sch5 SubPage Submitted', 691, 'SEED');
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID) VALUES (691, 'ACT', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2016, 691, 'S', 'SEED');
INSERT INTO THE.CAMP_REPORT (CAMP_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CAMP_NAME, DISTANCE_TO_OPERATING_AREA, CAMP_SIZE_CAPACITY, ASSOCIATED_CAMP_VOLUME, ISOLATED_CAMP_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8709, 2016, 691, '5', 'Submitted Camp', NULL, NULL, 20000, 'N', NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, REVISION_COUNT, ENTRY_USERID) VALUES (8743, 8709, 62, NULL, 600, 'Read Only Row', 0, 'SEED');

-- ================================================================================================
-- Mill 692 -- Check Status against REAL sub-page rows (Schedule5CheckStatusIT extension). The four
-- sub-list conditions have only ever been exercised against fixtures whose rows this story now
-- makes writable, so they are re-proved here from rows a licensee could actually have created.
--   8710  a blank-description item-62 row + a null-cost item-62 row  -> both camp conditions fire
--   8711  a blank-description item-68 row + a null-cost item-68 row  -> both access conditions fire
--   8712  a SINGLE-SPACE description                                 -> PASSES (isEmpty, not
--                                                                       isBlank -- already shipped)
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID) VALUES (692, 'Sch5 SubPage CheckStatus', 692, 'SEED');
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID) VALUES (692, 'ACT', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2016, 692, 'D', 'SEED');
INSERT INTO THE.CAMP_REPORT (CAMP_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CAMP_NAME, DISTANCE_TO_OPERATING_AREA, CAMP_SIZE_CAPACITY, ASSOCIATED_CAMP_VOLUME, ISOLATED_CAMP_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8710, 2016, 692, '5', 'Camp List Issues', 10.00, 5, 10000, 'N', NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, REVISION_COUNT, ENTRY_USERID) VALUES (8744, 8710, 62, NULL, 100, NULL, 0, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, REVISION_COUNT, ENTRY_USERID) VALUES (8745, 8710, 62, NULL, NULL, 'Has Description', 0, 'SEED');
INSERT INTO THE.CAMP_REPORT (CAMP_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CAMP_NAME, DISTANCE_TO_OPERATING_AREA, CAMP_SIZE_CAPACITY, ASSOCIATED_CAMP_VOLUME, ISOLATED_CAMP_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8711, 2016, 692, '5', 'Access List Issues', 10.00, 5, 10000, 'N', NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, REVISION_COUNT, ENTRY_USERID) VALUES (8746, 8711, 68, NULL, 100, NULL, 0, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, REVISION_COUNT, ENTRY_USERID) VALUES (8747, 8711, 68, NULL, NULL, 'Has Description', 0, 'SEED');
INSERT INTO THE.CAMP_REPORT (CAMP_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CAMP_NAME, DISTANCE_TO_OPERATING_AREA, CAMP_SIZE_CAPACITY, ASSOCIATED_CAMP_VOLUME, ISOLATED_CAMP_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8712, 2016, 692, '5', 'Single Space Camp', 10.00, 5, 10000, 'N', NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, REVISION_COUNT, ENTRY_USERID) VALUES (8748, 8712, 62, NULL, 100, ' ', 0, 'SEED');

-- ================================================================================================
-- Mill 693 -- owned SOLELY by Schedule5SubPageAuthorizationIT (the 8.2/12.2 lesson: an authorization
-- suite that shares a mill with a functional one starts failing for the wrong reason).
--
-- Its track is deliberately 'S', not 'D'. The "authorized" proof needs authorization to PASS and
-- then something ELSE to stop the write, otherwise it would have to mutate real state to show that
-- 403 was not returned. With a non-Draft track an authorized caller gets 409 from the Draft gate:
-- proof that @PreAuthorize let it through, with nothing written either way.
-- ================================================================================================
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID) VALUES (693, 'Sch5 SubPage Authz', 693, 'SEED');
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID) VALUES (693, 'ACT', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2016, 693, 'S', 'SEED');
INSERT INTO THE.CAMP_REPORT (CAMP_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, CAMP_NAME, DISTANCE_TO_OPERATING_AREA, CAMP_SIZE_CAPACITY, ASSOCIATED_CAMP_VOLUME, ISOLATED_CAMP_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8713, 2016, 693, '5', 'Authz Camp', NULL, NULL, 15000, 'N', NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, CAMP_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, REVISION_COUNT, ENTRY_USERID) VALUES (8749, 8713, 62, NULL, 700, 'Authz Row', 0, 'SEED');
