-- Schedule 6 corrections fixtures. Follows V32's conventions: 82xx PKs would collide here (this
-- task adds no road-record rows, only code-table rows), so no id block is claimed.
--
-- Code-table rows for the code-list endpoints (Task 1). Y9/Y9A are in-window for 2021; X9/X9A are
-- EXPIRED before 2021 and exist to prove the year filter actually excludes something. The IT
-- asserts containment, never exact list equality: the seeded image carries real TSA/TSB rows too.
INSERT INTO THE.TSA_NUMBER_CODE
    (TSA_NUMBER, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('Y9', 'Fixture Timber Supply Area', DATE '1990-01-01', DATE '9999-12-31', SYSTIMESTAMP);

INSERT INTO THE.TSA_NUMBER_CODE
    (TSA_NUMBER, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('X9', 'Fixture Expired TSA', DATE '1990-01-01', DATE '2010-12-31', SYSTIMESTAMP);

INSERT INTO THE.TSB_NUMBER_CODE
    (TSB_NUMBER_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('Y9A', 'Fixture Supply Block A', DATE '1990-01-01', DATE '9999-12-31', SYSTIMESTAMP);

INSERT INTO THE.TSB_NUMBER_CODE
    (TSB_NUMBER_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('X9A', 'Fixture Expired Block', DATE '1990-01-01', DATE '2010-12-31', SYSTIMESTAMP);

-- Task 3 (DELETE) fixtures. Mills 667-669 claimed fresh (661-666 are V32's; no cat-6 rows are added
-- to any existing fixture mill/year, since the check-status and Schedule6DocumentIT suites pin exact
-- record counts there). ROAD_MAINTENANCE_REPORT_ID 8370-8373, ILCR_COST_REPORT_DETAIL_ID 8380-8382
-- (free: V31/V32 claim up to 8362/8362 respectively). Mirrors the V32 "make a mill active" shape:
-- MILL + ILCR_MILL_STATUS_XREF ('ACT') + ILCR_MILL_REPORT_STATUS ('D' for 2021).

-- ============ Mill 667 / 2021 — SOLE record, non-blank COMMENTS ============
-- Deleting 8370 must re-insert a bare placeholder carrying its comment, or the schedule-level
-- general comment is destroyed with it (Schedule6DAO.java:297-309 — the BR-09 delete-side guard).
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID) VALUES (667, 'Sch6 Delete Sole Comment Milling', 667, 'SEED');
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID) VALUES (667, 'ACT', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2021, 667, 'D', 'SEED');
INSERT INTO THE.ROAD_MAINTENANCE_REPORT (ROAD_MAINTENANCE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, TSA_NUMBER, TSB_NUMBER_CODE, TFL_NUMBER_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8370, 2021, 667, '6', '01', '01B', NULL, 'Comment that must survive the delete', 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ROAD_MAINTENANCE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, COMMENTS, ENTRY_USERID)
  VALUES (8380, 8370, 69, 1000, 40000, 'row comment', 'SEED');

-- ============ Mill 668 / 2021 — SOLE record, BLANK (NULL) COMMENTS ============
-- Deleting 8371 must leave NOTHING behind: legacy re-inserts only when the deleted row's comment
-- was non-blank (Schedule6DAO.java:297); a placeholder here would resurrect an empty comment.
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID) VALUES (668, 'Sch6 Delete Sole Blank Milling', 668, 'SEED');
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID) VALUES (668, 'ACT', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2021, 668, 'D', 'SEED');
INSERT INTO THE.ROAD_MAINTENANCE_REPORT (ROAD_MAINTENANCE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, TSA_NUMBER, TSB_NUMBER_CODE, TFL_NUMBER_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8371, 2021, 668, '6', '01', '01B', NULL, NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ROAD_MAINTENANCE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, COMMENTS, ENTRY_USERID)
  VALUES (8381, 8371, 69, 500, 20000, 'no general comment row', 'SEED');

-- ============ Mill 669 / 2021 — TWO records sharing the replicated comment ============
-- Deleting one (8372, WITH an item-69 detail -> proves the child delete precedes the master delete,
-- ORA-02292 otherwise) must leave the other (8373, delivery-real shape: no detail) standing, still
-- carrying the comment, and NO placeholder inserted -- deleting a NON-sole record never touches the
-- BR-09 re-insert branch.
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID) VALUES (669, 'Sch6 Delete Non-Sole Milling', 669, 'SEED');
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID) VALUES (669, 'ACT', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2021, 669, 'D', 'SEED');
INSERT INTO THE.ROAD_MAINTENANCE_REPORT (ROAD_MAINTENANCE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, TSA_NUMBER, TSB_NUMBER_CODE, TFL_NUMBER_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8372, 2021, 669, '6', '01', '01B', NULL, 'Replicated comment.', 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ROAD_MAINTENANCE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, COMMENTS, ENTRY_USERID)
  VALUES (8382, 8372, 69, 300, 15000, 'Replication row 1', 'SEED');
INSERT INTO THE.ROAD_MAINTENANCE_REPORT (ROAD_MAINTENANCE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, TSA_NUMBER, TSB_NUMBER_CODE, TFL_NUMBER_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8373, 2021, 669, '6', NULL, NULL, '18', 'Replicated comment.', 0, 'SEED', SYSDATE, 'SEED', SYSDATE);

COMMIT;
