-- Story 24.2 (UC-CNT-001) Content Editing fixtures. THE.ILCR_ROLE is not modelled by any other slice,
-- so it is created here (last-running fixture) with the exact delivery shape (verified read-only
-- against DEV): PK ILCR_ROLE_NAME VARCHAR2(10), rich-text MESSAGE_TEXT VARCHAR2(4000), and the NOT NULL
-- audit quartet + REVISION_COUNT. Three role rows so the read/save + Home render exercise real data.
CREATE TABLE THE.ILCR_ROLE (
  ILCR_ROLE_NAME   VARCHAR2(10) PRIMARY KEY,
  MESSAGE_TEXT     VARCHAR2(4000),
  REVISION_COUNT   NUMBER(10)   NOT NULL,
  ENTRY_USERID     VARCHAR2(30) NOT NULL,
  ENTRY_TIMESTAMP  DATE         NOT NULL,
  UPDATE_USERID    VARCHAR2(30) NOT NULL,
  UPDATE_TIMESTAMP DATE         NOT NULL
);
INSERT INTO THE.ILCR_ROLE
  (ILCR_ROLE_NAME, MESSAGE_TEXT, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES ('LICENSEE', '<p>Licensee welcome.</p>', 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_ROLE
  (ILCR_ROLE_NAME, MESSAGE_TEXT, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES ('AUDITOR', '<p>Auditor welcome.</p>', 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_ROLE
  (ILCR_ROLE_NAME, MESSAGE_TEXT, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES ('ADMIN', '<p>Administrator welcome.</p>', 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
