-- Story 20.8 print — combined-order + nested-list geometry fixture. Adds a Schedule 8 (Tree to
-- Truck) page to mill 517/2021, the mill the combined Print Schedules IT (allSchedules on 517)
-- already renders every other in-scope section from. This pins TWO things the single-schedule 576
-- fixture cannot:
--   1. BR-08 position — with 517 now carrying Schedule 8 data, the combined PDF proves Schedule 8
--      sorts between Schedule 7B and Schedule 9 (PrintScheduleIT#allSchedules_rendersEveryInScopeSection).
--   2. The deep three-level geometry — the ONE construct with no precedent in the sibling templates:
--      a page with 2+ samples, one of which has 3 additions AND 3 deductions, so the additions inner
--      <list> stretches and floats the deductions block down inside the fixed-height samples list cell.
-- Code tables (SC1/R1/BZ1/TSA5/B, skid ST1, cost types CT1/CT2) and category-8 cost items
-- (82/100 additions, 101/107 deductions) are already seeded by V22. 517's MILL + 2021 report-status
-- rows already exist (V2 + the other print fixtures), so only the Tree-to-Truck hierarchy is added.
-- Tree-to-Truck PK ids 885x/886x/887x are unused in the TREE_TO_TRUCK_* tables (V22/V23 use
-- 850x/851x/86xx/870x/88[0-1]x).

INSERT INTO THE.TREE_TO_TRUCK_REPORT (TREE_TO_TRUCK_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, ILCR_SUPPORT_CENTRE_CODE, ILCR_FOREST_REGION_CODE, BEC_ZONE_CODE, TSA_NUMBER, TSB_NUMBER_CODE, HARVEST_LICENSE_NUMBER, DIVISION_LOCATION, CONTACT_NAME, CONTACT_PHONE_NUMBER, COMMENTS, REVISION_COUNT, ENTRY_USERID)
  VALUES (8850, 2021, 517, '8', 'SC1', 'R1', 'BZ1', 'TSA5', 'B', 'L517', 'Combined Div', 'Combined Contact', '2505550000', 'Combined-order + geometry page', 0, 'SEED');

-- Sample 1 — the deep case: 50/50 = 100%, harvested 1000, original 20.00, 3 additions + 3 deductions
-- => additionsTotal 10.00, deductionsTotal 3.50, final 26.50.
INSERT INTO THE.TREE_TO_TRUCK_DETAIL_REPORT (TREE_TO_TRUCK_DETAIL_REPORT_ID, TREE_TO_TRUCK_REPORT_ID, CONTRACTOR_ID, CUT_BLOCK, GROUND_BASE_PCT, GRAPPLE_PCT, SKYLINE_PCT, HIGHLEAD_PCT, HELICOPTER_PCT, OTHER_SKIDDING_PCT, ILCR_SKID_TYPE_CODE, CONIFEROUS_VOLUME, DECIDUOUS_VOLUME, ORIGINAL_TREE_TO_TRUCK_RATE, WATER_DUMP_DESTINATION_IND, UPHILL_DIRECTION_IND, REVISION_COUNT, ENTRY_USERID)
  VALUES (8860, 8850, 'C517A', 'CBA', 50, 50, 0, 0, 0, 0, 'ST1', 600, 400, 20.00, 'N', 'Y', 0, 'SEED');
INSERT INTO THE.TREE_TO_TRUCK_RATE_DETAIL (TREE_TO_TRUCK_RATE_DETAIL_ID, TREE_TO_TRUCK_DETAIL_REPORT_ID, ILCR_RATE_COST_TYPE_CODE, ILCR_REPORT_COST_ITEM_ID, ITEM_DESCRIPTION, COSTING_RATE, REVISION_COUNT, ENTRY_USERID)
  VALUES (8870, 8860, 'CT1', 82, 'Add One', 5.00, 0, 'SEED');
INSERT INTO THE.TREE_TO_TRUCK_RATE_DETAIL (TREE_TO_TRUCK_RATE_DETAIL_ID, TREE_TO_TRUCK_DETAIL_REPORT_ID, ILCR_RATE_COST_TYPE_CODE, ILCR_REPORT_COST_ITEM_ID, ITEM_DESCRIPTION, COSTING_RATE, REVISION_COUNT, ENTRY_USERID)
  VALUES (8871, 8860, 'CT2', 100, 'Add Two', 3.00, 0, 'SEED');
INSERT INTO THE.TREE_TO_TRUCK_RATE_DETAIL (TREE_TO_TRUCK_RATE_DETAIL_ID, TREE_TO_TRUCK_DETAIL_REPORT_ID, ILCR_RATE_COST_TYPE_CODE, ILCR_REPORT_COST_ITEM_ID, ITEM_DESCRIPTION, COSTING_RATE, REVISION_COUNT, ENTRY_USERID)
  VALUES (8872, 8860, 'CT1', 82, 'Add Three', 2.00, 0, 'SEED');
INSERT INTO THE.TREE_TO_TRUCK_RATE_DETAIL (TREE_TO_TRUCK_RATE_DETAIL_ID, TREE_TO_TRUCK_DETAIL_REPORT_ID, ILCR_RATE_COST_TYPE_CODE, ILCR_REPORT_COST_ITEM_ID, ITEM_DESCRIPTION, COSTING_RATE, REVISION_COUNT, ENTRY_USERID)
  VALUES (8873, 8860, 'CT2', 101, 'Ded One', 1.00, 0, 'SEED');
INSERT INTO THE.TREE_TO_TRUCK_RATE_DETAIL (TREE_TO_TRUCK_RATE_DETAIL_ID, TREE_TO_TRUCK_DETAIL_REPORT_ID, ILCR_RATE_COST_TYPE_CODE, ILCR_REPORT_COST_ITEM_ID, ITEM_DESCRIPTION, COSTING_RATE, REVISION_COUNT, ENTRY_USERID)
  VALUES (8874, 8860, 'CT1', 107, 'Ded Two', 2.00, 0, 'SEED');
INSERT INTO THE.TREE_TO_TRUCK_RATE_DETAIL (TREE_TO_TRUCK_RATE_DETAIL_ID, TREE_TO_TRUCK_DETAIL_REPORT_ID, ILCR_RATE_COST_TYPE_CODE, ILCR_REPORT_COST_ITEM_ID, ITEM_DESCRIPTION, COSTING_RATE, REVISION_COUNT, ENTRY_USERID)
  VALUES (8875, 8860, 'CT2', 101, 'Ded Three', 0.50, 0, 'SEED');

-- Sample 2 — a second sample on the SAME page (proves the 2+ samples reflow): highlead 100 = 100%,
-- harvested 500, original 15.00, one addition + one deduction => final 18.00.
INSERT INTO THE.TREE_TO_TRUCK_DETAIL_REPORT (TREE_TO_TRUCK_DETAIL_REPORT_ID, TREE_TO_TRUCK_REPORT_ID, CONTRACTOR_ID, CUT_BLOCK, GROUND_BASE_PCT, GRAPPLE_PCT, SKYLINE_PCT, HIGHLEAD_PCT, HELICOPTER_PCT, OTHER_SKIDDING_PCT, ILCR_SKID_TYPE_CODE, CONIFEROUS_VOLUME, DECIDUOUS_VOLUME, ORIGINAL_TREE_TO_TRUCK_RATE, WATER_DUMP_DESTINATION_IND, UPHILL_DIRECTION_IND, REVISION_COUNT, ENTRY_USERID)
  VALUES (8861, 8850, 'C517B', 'CBB', 0, 0, 0, 100, 0, 0, 'ST1', 500, 0, 15.00, 'Y', 'N', 0, 'SEED');
INSERT INTO THE.TREE_TO_TRUCK_RATE_DETAIL (TREE_TO_TRUCK_RATE_DETAIL_ID, TREE_TO_TRUCK_DETAIL_REPORT_ID, ILCR_RATE_COST_TYPE_CODE, ILCR_REPORT_COST_ITEM_ID, ITEM_DESCRIPTION, COSTING_RATE, REVISION_COUNT, ENTRY_USERID)
  VALUES (8876, 8861, 'CT2', 100, 'Add Solo', 4.00, 0, 'SEED');
INSERT INTO THE.TREE_TO_TRUCK_RATE_DETAIL (TREE_TO_TRUCK_RATE_DETAIL_ID, TREE_TO_TRUCK_DETAIL_REPORT_ID, ILCR_RATE_COST_TYPE_CODE, ILCR_REPORT_COST_ITEM_ID, ITEM_DESCRIPTION, COSTING_RATE, REVISION_COUNT, ENTRY_USERID)
  VALUES (8877, 8861, 'CT1', 107, 'Ded Solo', 1.00, 0, 'SEED');

COMMIT;
