-- Story 25.1 (UC-SCH11-001) seed: Schedule 11 (Basic Silviculture) locations. TEST-SCOPE ONLY.
-- V20 claimed 2026-07-28 (V1-V9 on this tree; in-review branches claim V5-V15; Flyway allows gaps).
-- Mills 610-613 claimed fresh (514-532/540 on main, 52x/102x burned by in-review branches).
-- Read-only reuse: mill 514/2021 (silvi code NULL -> trackStatus:null), mill 516/2021 (CLS -> 409).
-- NEVER mutated here. NO runtime DDL exists (AD-2) - all DDL below is test-scope snapshot extension.

-- Extend the V1 snapshot (extend-never-fork): the delivery ILCR_COST_REPORT_DETAIL carries a
-- BASIC_SILVICULTURE_REPORT_ID NUMBER(10) NULL column (NO FK constraint in delivery - AC9 finding)
-- that the V1 test-scope table lacks.
-- RE-VERIFIED 2026-08-13 against all_constraints on THE: this column is the ONLY per-report column on
-- ILCR_COST_REPORT_DETAIL with no FK. The other eight FK'd columns are listed in
-- R__cost_detail_bridge_culvert_fks.sql, where the same "no FK" claim for BRIDGE_REPORT_ID and
-- CULVERT_REPORT_ID turned out to be false and cost a
-- production defect. The claim is CORRECT here — leave it, and keep Schedule 11's delete order safe on
-- schema grounds rather than assuming the pattern generalises.
ALTER TABLE THE.ILCR_COST_REPORT_DETAIL ADD BASIC_SILVICULTURE_REPORT_ID NUMBER(10);

-- Delivery-faithful test-scope shape (AC9-verified against nr-mof-oracle-schema 2026-07-28):
-- NOT NULLs mirror delivery on the domain columns (REFORESTED_NET_AREA IS NOT NULL - the "null NAR"
-- derivation branch is unit-test-only); audit columns follow the V1 snapshot convention.
-- BSRPT_BSRPT_UK_UK mirrors the delivery uniqueness the legacy maps to SILVICULTURE_UNIQUE_BIOGEOCODE
-- (25.2 will exercise it; harmless for reads).
CREATE TABLE THE.BASIC_SILVICULTURE_REPORT (
  BASIC_SILVICULTURE_REPORT_ID   NUMBER(10)     PRIMARY KEY,
  REPORT_YEAR                    NUMBER(4)      NOT NULL,
  ILCR_MILL_ID                   NUMBER(10)     NOT NULL,
  ILCR_CATEGORY_ID               VARCHAR2(5)    NOT NULL,
  LOCATION                       VARCHAR2(30)   NOT NULL,
  BECBIOGEOCLIMATIC_CATALOGUE_ID NUMBER(10)     NOT NULL,
  REFORESTED_NET_AREA            NUMBER(10,2)   NOT NULL,
  ENHANCED_IND                   VARCHAR2(1)    NOT NULL,
  COMMENTS                       VARCHAR2(3500),
  REVISION_COUNT                 NUMBER(5)      DEFAULT 0 NOT NULL,
  ENTRY_USERID                   VARCHAR2(30),
  ENTRY_TIMESTAMP                TIMESTAMP DEFAULT SYSTIMESTAMP,
  UPDATE_USERID                  VARCHAR2(30),
  UPDATE_TIMESTAMP               TIMESTAMP,
  CONSTRAINT BSRPT_BSRPT_UK_UK UNIQUE
    (REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, BECBIOGEOCLIMATIC_CATALOGUE_ID, LOCATION)
);

-- Only the columns the Schedule 11 read touches (V1 snapshot philosophy). Delivery nullability:
-- zone/subzone NOT NULL, variant/phase NULL (real data: 38 of 40 used rows have NULL phase - the
-- legacy null->'' concat in getBiogeoSubZoneVariantPase is the common case, not the edge).
CREATE TABLE THE.BIOGEOCLIMATIC_CATALOGUE (
  BIOGEOCLIMATIC_CATALOGUE_ID NUMBER(10)  PRIMARY KEY,
  BEC_ZONE_CODE               VARCHAR2(4) NOT NULL,
  SUBZONE                     VARCHAR2(3) NOT NULL,
  VARIANT                     VARCHAR2(1),
  PHASE                       VARCHAR2(1)
);

-- becLabel expectations (zone+subzone+variant+phase, nulls -> ''):
--   8801 -> 'ICHdw1' (phase null) | 8802 -> 'CWHvm' (variant+phase null) | 8803 -> 'ESSFwc4a' (full)
INSERT INTO THE.BIOGEOCLIMATIC_CATALOGUE (BIOGEOCLIMATIC_CATALOGUE_ID, BEC_ZONE_CODE, SUBZONE, VARIANT, PHASE) VALUES (8801, 'ICH', 'dw', '1', NULL);
INSERT INTO THE.BIOGEOCLIMATIC_CATALOGUE (BIOGEOCLIMATIC_CATALOGUE_ID, BEC_ZONE_CODE, SUBZONE, VARIANT, PHASE) VALUES (8802, 'CWH', 'vm', NULL, NULL);
INSERT INTO THE.BIOGEOCLIMATIC_CATALOGUE (BIOGEOCLIMATIC_CATALOGUE_ID, BEC_ZONE_CODE, SUBZONE, VARIANT, PHASE) VALUES (8803, 'ESSF', 'wc', '4', 'a');

-- Schedule 11 cost items (delivery-verified names/category: 23='Planned', 24='Actual', cat '11'
-- subcat '1' - Constant.REPORT_COST_ITEMS.Schedule11_1_*). Absent from V2 (it seeds cat-1 items only).
INSERT INTO THE.ILCR_REPORT_COST_ITEM (ILCR_REPORT_COST_ITEM_ID, ITEM_NAME, ILCR_CATEGORY_ID, ILCR_SUBCATEGORY_ID, ENTRY_USERID) VALUES (23, 'Planned', '11', '1', 'SEED');
INSERT INTO THE.ILCR_REPORT_COST_ITEM (ILCR_REPORT_COST_ITEM_ID, ITEM_NAME, ILCR_CATEGORY_ID, ILCR_SUBCATEGORY_ID, ENTRY_USERID) VALUES (24, 'Actual', '11', '1', 'SEED');

-- ============ Fixture (a): mill 610 - silviculture Draft, every derivation branch ============
-- Silvi track 'D' + SUBMITTER -> editable:true; 1-10 track also 'D' (the S10 cross-track proof is
-- mill 612). Expected document (Schedule11DocumentIT asserts these exact numbers):
--   9101: totalCost 35000 (=25000+10000), costPerNetArea 290.4564 (=35000/120.5, scale 4 HALF_UP)
--   9102: totalCost 4500 (actual only; null+x=x), costPerNetArea 135.1351 (=4500/33.3)
--   9103: totalCost 7000 (planned only), costPerNetArea 140.0 (=7000/50; stripTrailingZeros min scale 1)
--   9104: totalCost null (NO cost rows - the real-data dominant case), costPerNetArea null
--   footer: netArea 214.1 (=120.5+33.3+50+10.25=214.05, scale 1 HALF_UP - proves footer rounding),
--           actualCost 29500, plannedCost 17000, totalCost 46500,
--           costPerNetArea 217.1882 (=46500/214.1, scale 4 HALF_UP)
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID) VALUES (610, 'Silviculture Draft Milling', 610, 'SEED');
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID) VALUES (610, 'ACT', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, MILL_SILVICULTUR_STATUS_CODE, ENTRY_USERID) VALUES (2021, 610, 'D', 'D', 'SEED');

INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID) VALUES (9101, 2021, 610, '11', 'Kootenay Lake East', 8801, 120.5, 'N', NULL, 0, 'SEED');
INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID) VALUES (9102, 2021, 610, '11', 'Slocan Valley', 8802, 33.3, 'Y', 'Enhanced site', 3, 'SEED');
INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID) VALUES (9103, 2021, 610, '11', 'Arrow Lakes North', 8801, 50, 'N', NULL, 0, 'SEED');
INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID) VALUES (9104, 2021, 610, '11', 'Duncan Dam Flats', 8803, 10.25, 'N', 'No costs yet', 0, 'SEED');

-- Cost children (ILCR_REPORT_SUMMARY_ID NULL - list schedules have no summary; item 24=Actual, 23=Planned).
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (6001, NULL, 9101, 24, NULL, 25000, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (6002, NULL, 9101, 23, NULL, 10000, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (6003, NULL, 9102, 24, NULL, 4500, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (6004, NULL, 9103, 23, NULL, 7000, NULL, 'SEED');
-- Out-of-scope item attached to 9101: the 23/24 filter must EXCLUDE it (its 99999 must appear in
-- no total). Item 19 ('Other', category 1) exists from V2.
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (6005, NULL, 9101, 19, NULL, 99999, NULL, 'SEED');

-- ============ Fixture (b): mill 611 - silviculture track 'S' -> editable:false (S20) ============
-- trackStatus 'S'; one location so the 200 body is non-trivial while editable is false.
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID) VALUES (611, 'Silviculture Submitted Mill', 611, 'SEED');
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID) VALUES (611, 'ACT', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, MILL_SILVICULTUR_STATUS_CODE, ENTRY_USERID) VALUES (2021, 611, 'D', 'S', 'SEED');
INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID) VALUES (9105, 2021, 611, '11', 'Submitted Block', 8801, 20, 'N', NULL, 0, 'SEED');

-- ==== Fixture (c): mill 612 - 1-10 track 'S' (Submitted) but silviculture 'D' -> editable:true ====
-- The S10/AC6 track-independence proof: a Submitted 1-10 track changes NOTHING on Schedule 11.
-- 9106: totalCost 1500 (=1000+500), costPerNetArea 300.0 (=1500/5); footer: netArea 5.0,
-- actualCost 1000, plannedCost 500, totalCost 1500, costPerNetArea 300.0.
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID) VALUES (612, 'Cross Track Milling', 612, 'SEED');
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID) VALUES (612, 'ACT', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, MILL_SILVICULTUR_STATUS_CODE, ENTRY_USERID) VALUES (2021, 612, 'S', 'D', 'SEED');
INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID) VALUES (9106, 2021, 612, '11', 'Independence Ridge', 8803, 5, 'N', NULL, 1, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (6006, NULL, 9106, 24, NULL, 1000, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (6007, NULL, 9106, 23, NULL, 500, NULL, 'SEED');

-- ============ Fixture (d): mill 613 - valid, active, silvi 'D', ZERO locations (AC2) ============
-- 200 with locations:[] and NULL (never 0) footer totals; editable:true (Draft + SUBMITTER).
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID) VALUES (613, 'Empty Silviculture Mill', 613, 'SEED');
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID) VALUES (613, 'ACT', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, MILL_SILVICULTUR_STATUS_CODE, ENTRY_USERID) VALUES (2021, 613, 'D', 'D', 'SEED');

-- Fixture (e) 404: unseeded pair (millId 999999) - no rows needed.
-- Fixture (f) 409: mill 516/2021 (CLS, V2) reused READ-ONLY.
-- trackStatus-null case: mill 514/2021 (V2 omits MILL_SILVICULTUR_STATUS_CODE -> NULL) reused READ-ONLY.

COMMIT;
