-- Story 25.2 (UC-SCH11-001) seed: Schedule 11 WRITE + check-status fixtures. TEST-SCOPE ONLY.
-- V21 claimed 2026-07-29 (V1-V9 + V20 on this tree; next free). Mills 614-617 claimed fresh
-- (25.1 used 610-613; never mutate those). BSR ids 9201-9206, cost-detail ids 6101-6107
-- (25.1 used 9101-9106 / 6001-6007). NO runtime DDL exists (AD-2) - the CREATE SEQUENCE below is a
-- test-scope snapshot extension (the delivery ILCR_REPORT_COMMON_SEQ is confirmed present, 25.2
-- Task 1; the V1 snapshot lacks it because no prior story inserts a BASIC_SILVICULTURE_REPORT /
-- ILCR_REPORT_SUMMARY row - schedule1 only bumps an existing summary).

-- BSR PK generator (delivery: THE.ILCR_REPORT_COMMON_SEQ). V11 (Schedule 2) already creates this
-- sequence START WITH 9000, so a bare CREATE here is ORA-00955; drop/recreate instead to restart it
-- at 9500 — high enough that sequence-generated ids for newly-added locations never collide with
-- the explicit fixture ids below (9201-9206) or V20's (9101-9106). Safe: migrations run at
-- container init, before any IT draws NEXTVAL, and sequence consumers need no continuity.
-- ILCR_COST_REPORT_DETAIL_SEQ already exists (V4, START WITH 9000) - reused for new cost children;
-- explicit cost ids here (6101-6107) stay below it.
DROP SEQUENCE THE.ILCR_REPORT_COMMON_SEQ;
CREATE SEQUENCE THE.ILCR_REPORT_COMMON_SEQ START WITH 9500 INCREMENT BY 1;

-- ============ Fixture (a): mill 614 - silviculture Draft write playground ============
-- Silvi 'D' + 1-10 'D' -> writable. 9201 (both costs) is the edit / stale-revision / duplicate-key
-- source; 9202 (one cost) is the delete + cost-cascade target.
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID) VALUES (614, 'Silviculture Write Milling', 614, 'SEED');
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID) VALUES (614, 'ACT', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, MILL_SILVICULTUR_STATUS_CODE, ENTRY_USERID) VALUES (2021, 614, 'D', 'D', 'SEED');

INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID) VALUES (9201, 2021, 614, '11', 'Existing Ridge', 8801, 100, 'N', NULL, 0, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (6101, NULL, 9201, 24, NULL, 5000, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (6102, NULL, 9201, 23, NULL, 4000, NULL, 'SEED');

INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID) VALUES (9202, 2021, 614, '11', 'Delete Me', 8802, 50, 'N', NULL, 0, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (6103, NULL, 9202, 24, NULL, 3000, NULL, 'SEED');
-- Out-of-scope item on the delete target (mirrors V20's item-19-on-a-BSR real-data case): the
-- delete cascade must remove the WHOLE cost family, not just 23/24 — else this row is orphaned.
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (6108, NULL, 9202, 19, NULL, 750, NULL, 'SEED');

-- ============ Fixture (b): mill 615 - silviculture 'S' (non-Draft) -> write-gate 409 ============
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID) VALUES (615, 'Silviculture Locked Milling', 615, 'SEED');
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID) VALUES (615, 'ACT', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, MILL_SILVICULTUR_STATUS_CODE, ENTRY_USERID) VALUES (2021, 615, 'D', 'S', 'SEED');
INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID) VALUES (9203, 2021, 615, '11', 'Locked Block', 8801, 10, 'N', NULL, 0, 'SEED');

-- ============ Fixture (c): mill 616 - silviculture Draft, check-status ALL MET (S04) ============
-- One location with BOTH costs -> requirementsMet true (+ SUC-003).
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID) VALUES (616, 'Silviculture Complete Milling', 616, 'SEED');
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID) VALUES (616, 'ACT', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, MILL_SILVICULTUR_STATUS_CODE, ENTRY_USERID) VALUES (2021, 616, 'D', 'D', 'SEED');
INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID) VALUES (9204, 2021, 616, '11', 'Complete Block', 8803, 30, 'N', NULL, 0, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (6104, NULL, 9204, 24, NULL, 2000, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (6105, NULL, 9204, 23, NULL, 1000, NULL, 'SEED');

-- ==== Fixture (d): mill 617 - silviculture Draft, check-status MISSING flags (S05/S06) ====
-- 9205 has ONLY planned (actual missing -> FLD-004 'Actual cost'); 9206 has ONLY actual (planned
-- missing -> FLD-004 'Planned cost'). Both errors, in BASIC_SILVICULTURE_REPORT_ID order.
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID) VALUES (617, 'Silviculture Incomplete Milling', 617, 'SEED');
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID) VALUES (617, 'ACT', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, MILL_SILVICULTUR_STATUS_CODE, ENTRY_USERID) VALUES (2021, 617, 'D', 'D', 'SEED');
INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID) VALUES (9205, 2021, 617, '11', 'Missing Actual', 8801, 20, 'N', NULL, 0, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (6106, NULL, 9205, 23, NULL, 800, NULL, 'SEED');
INSERT INTO THE.BASIC_SILVICULTURE_REPORT (BASIC_SILVICULTURE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION, BECBIOGEOCLIMATIC_CATALOGUE_ID, REFORESTED_NET_AREA, ENHANCED_IND, COMMENTS, REVISION_COUNT, ENTRY_USERID) VALUES (9206, 2021, 617, '11', 'Missing Planned', 8802, 25, 'N', NULL, 0, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BASIC_SILVICULTURE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (6107, NULL, 9206, 24, NULL, 900, NULL, 'SEED');

-- Reused READ-ONLY for check-status vacuous-met: mill 613/2021 (V20, Draft, ZERO locations).
-- Invalid-biogeo (S16/AC6 400): BEC id 8899 is absent from BIOGEOCLIMATIC_CATALOGUE (V20 seeds
-- 8801-8803 only). Duplicate-key (409): add to 614 with biogeo 8801 + location 'Existing Ridge'.

COMMIT;
