-- =====================================================================================================
-- V27 — Schedule 7A (Bridge Costs, Epic 12 / UC-SCH7A-001) test-scope snapshot + read/check-status
-- fixtures. EXTENDS V1-V26; never edits them. NO runtime DDL exists (AD-2) — this is a test-scope
-- snapshot extension only; the delivery THE schema already carries BRIDGE_REPORT, the five bridge
-- *_CODE tables, and the shared sequences.
--
-- A bridge = one THE.BRIDGE_REPORT row keyed (ILCR_MILL_ID, REPORT_YEAR, ILCR_CATEGORY_ID='7'); its
-- ten costs = THE.ILCR_COST_REPORT_DETAIL rows keyed by BRIDGE_REPORT_ID + one of the fixed Schedule 7
-- cost items (70,71,72,73,74,75,76,79,80,81), ILCR_REPORT_SUMMARY_ID NULL (list schedule).
--
-- Reuses V2 context mills @ 2021: 514 = ACT + 1-10 track 'D' (Draft, editable); 517 = ACT + 'S'
-- (Submitted, editable:false). Bridge ids 7601-7699, cost-detail ids 7701-7799 (both below the
-- ILCR_REPORT_COMMON_SEQ start 9500 / ILCR_COST_REPORT_DETAIL_SEQ start 9000, so the write-path
-- NEXTVAL ids can never collide). ILCR_REPORT_COMMON_SEQ + ILCR_COST_REPORT_DETAIL_SEQ already exist
-- (V21 / V4) — not re-created here.
-- =====================================================================================================

-- Per-report FK column on the shared cost-detail table (NO FK constraint in delivery, matching the
-- schedule4/schedule11 per-report columns).
ALTER TABLE THE.ILCR_COST_REPORT_DETAIL ADD BRIDGE_REPORT_ID NUMBER(10);

-- The bridge parent table (legacy model/BridgeReport.java:40-130).
CREATE TABLE THE.BRIDGE_REPORT (
  BRIDGE_REPORT_ID               NUMBER(10)   PRIMARY KEY,
  REPORT_YEAR                    NUMBER(10),
  ILCR_MILL_ID                   NUMBER(10),
  ILCR_CATEGORY_ID               VARCHAR2(3),
  LOCATION_NAME                  VARCHAR2(30),
  BUILT_DATE                     DATE,
  EXPECTED_BRIDGE_LIFE_SPAN      NUMBER(3),
  HEIGHT                         NUMBER(5,1),
  LENGTH                         NUMBER(5,1),
  DECK_WIDTH                     NUMBER(5,1),
  DISTANCE_FROM_STORAGE          NUMBER(4),
  ILCR_BRIDGE_CNSTRCTN_TYPE_CODE VARCHAR2(10),
  ILCR_BRIDGE_SUPERSTRUCTR_CODE  VARCHAR2(10),
  ILCR_DECK_CODE                 VARCHAR2(10),
  ILCR_BRIDGE_ABUTMENT_TYPE_CODE VARCHAR2(10),
  ILCR_BRIDGE_LOAD_RATING_CODE   VARCHAR2(10),
  COMMENTS                       VARCHAR2(4000),
  REVISION_COUNT                 NUMBER(10)   DEFAULT 0,
  ENTRY_USERID                   VARCHAR2(30),
  ENTRY_TIMESTAMP                TIMESTAMP    DEFAULT SYSTIMESTAMP,
  UPDATE_USERID                  VARCHAR2(30),
  UPDATE_TIMESTAMP               TIMESTAMP
);

-- The five bridge code tables (single-column code PK + DESCRIPTION — the schedule8 *_CODE pattern).
CREATE TABLE THE.ILCR_BRIDGE_CNSTRCTN_TYPE_CODE (ILCR_BRIDGE_CNSTRCTN_TYPE_CODE VARCHAR2(10) PRIMARY KEY, DESCRIPTION VARCHAR2(120));
CREATE TABLE THE.ILCR_BRIDGE_SUPERSTRUCTR_CODE  (ILCR_BRIDGE_SUPERSTRUCTR_CODE  VARCHAR2(10) PRIMARY KEY, DESCRIPTION VARCHAR2(120));
CREATE TABLE THE.ILCR_DECK_CODE                 (ILCR_DECK_CODE                 VARCHAR2(10) PRIMARY KEY, DESCRIPTION VARCHAR2(120));
CREATE TABLE THE.ILCR_BRIDGE_ABUTMENT_TYPE_CODE (ILCR_BRIDGE_ABUTMENT_TYPE_CODE VARCHAR2(10) PRIMARY KEY, DESCRIPTION VARCHAR2(120));
CREATE TABLE THE.ILCR_BRIDGE_LOAD_RATING_CODE   (ILCR_BRIDGE_LOAD_RATING_CODE   VARCHAR2(10) PRIMARY KEY, DESCRIPTION VARCHAR2(120));

INSERT INTO THE.ILCR_BRIDGE_CNSTRCTN_TYPE_CODE VALUES ('N', 'New');
INSERT INTO THE.ILCR_BRIDGE_CNSTRCTN_TYPE_CODE VALUES ('U', 'Used');

INSERT INTO THE.ILCR_BRIDGE_SUPERSTRUCTR_CODE VALUES ('STL', 'Steel');
INSERT INTO THE.ILCR_BRIDGE_SUPERSTRUCTR_CODE VALUES ('CONC', 'Concrete');
INSERT INTO THE.ILCR_BRIDGE_SUPERSTRUCTR_CODE VALUES ('WD', 'Wood');

INSERT INTO THE.ILCR_DECK_CODE VALUES ('WD', 'Wood');
INSERT INTO THE.ILCR_DECK_CODE VALUES ('STL', 'Steel');

INSERT INTO THE.ILCR_BRIDGE_ABUTMENT_TYPE_CODE VALUES ('CONC', 'Concrete');
INSERT INTO THE.ILCR_BRIDGE_ABUTMENT_TYPE_CODE VALUES ('TIMB', 'Timber');

INSERT INTO THE.ILCR_BRIDGE_LOAD_RATING_CODE VALUES ('L100', 'L-100');
INSERT INTO THE.ILCR_BRIDGE_LOAD_RATING_CODE VALUES ('L75', 'L-75');

-- Register the ten Schedule 7 cost items (category '7') — defined once here (not registered before).
INSERT INTO THE.ILCR_REPORT_COST_ITEM (ILCR_REPORT_COST_ITEM_ID, ITEM_NAME, ILCR_CATEGORY_ID, ILCR_SUBCATEGORY_ID, ENTRY_USERID) VALUES (70, 'Site Plan and General Arrangement', '7', '1', 'SEED');
INSERT INTO THE.ILCR_REPORT_COST_ITEM (ILCR_REPORT_COST_ITEM_ID, ITEM_NAME, ILCR_CATEGORY_ID, ILCR_SUBCATEGORY_ID, ENTRY_USERID) VALUES (71, 'Approach works', '7', '1', 'SEED');
INSERT INTO THE.ILCR_REPORT_COST_ITEM (ILCR_REPORT_COST_ITEM_ID, ITEM_NAME, ILCR_CATEGORY_ID, ILCR_SUBCATEGORY_ID, ENTRY_USERID) VALUES (72, 'Certification After install', '7', '1', 'SEED');
INSERT INTO THE.ILCR_REPORT_COST_ITEM (ILCR_REPORT_COST_ITEM_ID, ITEM_NAME, ILCR_CATEGORY_ID, ILCR_SUBCATEGORY_ID, ENTRY_USERID) VALUES (73, 'Other Costs', '7', '2', 'SEED');
INSERT INTO THE.ILCR_REPORT_COST_ITEM (ILCR_REPORT_COST_ITEM_ID, ITEM_NAME, ILCR_CATEGORY_ID, ILCR_SUBCATEGORY_ID, ENTRY_USERID) VALUES (74, 'Abutments Material cost', '7', '3', 'SEED');
INSERT INTO THE.ILCR_REPORT_COST_ITEM (ILCR_REPORT_COST_ITEM_ID, ITEM_NAME, ILCR_CATEGORY_ID, ILCR_SUBCATEGORY_ID, ENTRY_USERID) VALUES (75, 'Abutments Delivery cost', '7', '3', 'SEED');
INSERT INTO THE.ILCR_REPORT_COST_ITEM (ILCR_REPORT_COST_ITEM_ID, ITEM_NAME, ILCR_CATEGORY_ID, ILCR_SUBCATEGORY_ID, ENTRY_USERID) VALUES (76, 'Abutments Installation cost', '7', '3', 'SEED');
INSERT INTO THE.ILCR_REPORT_COST_ITEM (ILCR_REPORT_COST_ITEM_ID, ITEM_NAME, ILCR_CATEGORY_ID, ILCR_SUBCATEGORY_ID, ENTRY_USERID) VALUES (79, 'Superstructure Material Cost', '7', '5', 'SEED');
INSERT INTO THE.ILCR_REPORT_COST_ITEM (ILCR_REPORT_COST_ITEM_ID, ITEM_NAME, ILCR_CATEGORY_ID, ILCR_SUBCATEGORY_ID, ENTRY_USERID) VALUES (80, 'Superstructure Delivery Cost', '7', '5', 'SEED');
INSERT INTO THE.ILCR_REPORT_COST_ITEM (ILCR_REPORT_COST_ITEM_ID, ITEM_NAME, ILCR_CATEGORY_ID, ILCR_SUBCATEGORY_ID, ENTRY_USERID) VALUES (81, 'Superstructure Installation Cost', '7', '5', 'SEED');

-- ---------------------------------------------------------------------------------------------------
-- 514 / 2021 (Draft) — three bridges.
--   7601 "North Fork Bridge"  (complete): totalMaterial 8000, totalDeliver 800, totalInstall 1200,
--        grandTotal 12000 (1000 + 8000 + 800 + 1200 + 700 + 200 + 100).
--   7602 "South Creek Bridge" (complete, 'U'/CONC/STL/TIMB/L75): totalMaterial 5000, totalDeliver 500,
--        totalInstall 800, grandTotal 8800 (2000 + 5000 + 500 + 800 + 300 + 150 + 50).
--   7603 "Old Mill Crossing"  (INCOMPLETE — missing afterInstall(72) + other(73) costs): drives the
--        Check Status S29 flags; totalMaterial 3800, totalDeliver 380, totalInstall 620, grandTotal
--        5400 (500 + 3800 + 380 + 620 + 100).
-- ---------------------------------------------------------------------------------------------------
INSERT INTO THE.BRIDGE_REPORT (BRIDGE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION_NAME, BUILT_DATE, EXPECTED_BRIDGE_LIFE_SPAN, HEIGHT, LENGTH, DECK_WIDTH, DISTANCE_FROM_STORAGE, ILCR_BRIDGE_CNSTRCTN_TYPE_CODE, ILCR_BRIDGE_SUPERSTRUCTR_CODE, ILCR_DECK_CODE, ILCR_BRIDGE_ABUTMENT_TYPE_CODE, ILCR_BRIDGE_LOAD_RATING_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID)
  VALUES (7601, 2021, 514, '7', 'North Fork Bridge', DATE '2020-06-01', 50, 5.0, 20.0, 4.0, 12, 'N', 'STL', 'WD', 'CONC', 'L100', 'First span', 0, 'SEED');
INSERT INTO THE.BRIDGE_REPORT (BRIDGE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION_NAME, BUILT_DATE, EXPECTED_BRIDGE_LIFE_SPAN, HEIGHT, LENGTH, DECK_WIDTH, DISTANCE_FROM_STORAGE, ILCR_BRIDGE_CNSTRCTN_TYPE_CODE, ILCR_BRIDGE_SUPERSTRUCTR_CODE, ILCR_DECK_CODE, ILCR_BRIDGE_ABUTMENT_TYPE_CODE, ILCR_BRIDGE_LOAD_RATING_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID)
  VALUES (7602, 2021, 514, '7', 'South Creek Bridge', DATE '2019-11-01', 40, 3.5, 15.5, 3.0, 8, 'U', 'CONC', 'STL', 'TIMB', 'L75', NULL, 0, 'SEED');
INSERT INTO THE.BRIDGE_REPORT (BRIDGE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION_NAME, BUILT_DATE, EXPECTED_BRIDGE_LIFE_SPAN, HEIGHT, LENGTH, DECK_WIDTH, DISTANCE_FROM_STORAGE, ILCR_BRIDGE_CNSTRCTN_TYPE_CODE, ILCR_BRIDGE_SUPERSTRUCTR_CODE, ILCR_DECK_CODE, ILCR_BRIDGE_ABUTMENT_TYPE_CODE, ILCR_BRIDGE_LOAD_RATING_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID)
  VALUES (7603, 2021, 514, '7', 'Old Mill Crossing', DATE '2018-03-01', 30, 2.5, 10.0, 2.5, 5, 'U', 'WD', 'WD', 'TIMB', 'L75', NULL, 0, 'SEED');

-- 7601 costs (all ten present).
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7701, NULL, 7601, 70, NULL, 1000, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7702, NULL, 7601, 71, NULL, 700, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7703, NULL, 7601, 72, NULL, 200, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7704, NULL, 7601, 73, NULL, 100, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7705, NULL, 7601, 74, NULL, 3000, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7706, NULL, 7601, 75, NULL, 300, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7707, NULL, 7601, 76, NULL, 400, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7708, NULL, 7601, 79, NULL, 5000, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7709, NULL, 7601, 80, NULL, 500, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7710, NULL, 7601, 81, NULL, 800, NULL, 'SEED');

-- 7602 costs (all ten present).
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7711, NULL, 7602, 70, NULL, 2000, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7712, NULL, 7602, 71, NULL, 300, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7713, NULL, 7602, 72, NULL, 150, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7714, NULL, 7602, 73, NULL, 50, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7715, NULL, 7602, 74, NULL, 1000, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7716, NULL, 7602, 75, NULL, 100, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7717, NULL, 7602, 76, NULL, 200, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7718, NULL, 7602, 79, NULL, 4000, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7719, NULL, 7602, 80, NULL, 400, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7720, NULL, 7602, 81, NULL, 600, NULL, 'SEED');

-- 7603 costs (EIGHT — afterInstall(72) and other(73) deliberately absent for the S29 check-status test).
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7721, NULL, 7603, 70, NULL, 500, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7722, NULL, 7603, 71, NULL, 100, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7723, NULL, 7603, 74, NULL, 800, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7724, NULL, 7603, 75, NULL, 80, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7725, NULL, 7603, 76, NULL, 120, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7726, NULL, 7603, 79, NULL, 3000, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7727, NULL, 7603, 80, NULL, 300, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7728, NULL, 7603, 81, NULL, 500, NULL, 'SEED');

-- ---------------------------------------------------------------------------------------------------
-- 517 / 2021 (Submitted 'S') — one complete bridge. Read serves editable:false; Check Status (not
-- Draft-gated) runs and reports all-met.
--   7651 "Harbour Overpass": grandTotal 6125 (1500 + (2500+900) + (250+90) + (350+110) + 250 + 100 + 75).
-- ---------------------------------------------------------------------------------------------------
INSERT INTO THE.BRIDGE_REPORT (BRIDGE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, LOCATION_NAME, BUILT_DATE, EXPECTED_BRIDGE_LIFE_SPAN, HEIGHT, LENGTH, DECK_WIDTH, DISTANCE_FROM_STORAGE, ILCR_BRIDGE_CNSTRCTN_TYPE_CODE, ILCR_BRIDGE_SUPERSTRUCTR_CODE, ILCR_DECK_CODE, ILCR_BRIDGE_ABUTMENT_TYPE_CODE, ILCR_BRIDGE_LOAD_RATING_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID)
  VALUES (7651, 2021, 517, '7', 'Harbour Overpass', DATE '2020-09-01', 60, 6.0, 25.0, 5.0, 15, 'N', 'STL', 'STL', 'CONC', 'L100', NULL, 0, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7751, NULL, 7651, 70, NULL, 1500, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7752, NULL, 7651, 71, NULL, 250, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7753, NULL, 7651, 72, NULL, 100, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7754, NULL, 7651, 73, NULL, 75, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7755, NULL, 7651, 74, NULL, 900, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7756, NULL, 7651, 75, NULL, 90, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7757, NULL, 7651, 76, NULL, 110, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7758, NULL, 7651, 79, NULL, 2500, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7759, NULL, 7651, 80, NULL, 250, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, BRIDGE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (7760, NULL, 7651, 81, NULL, 350, NULL, 'SEED');
