-- Story 8.2 (UC-SCH6-001) seed: Schedule 6 WRITE + check-status fixtures. TEST-SCOPE ONLY.
-- V32 claimed (renumbered from V31 at PR review 2026-08-05, when main's own V30 forced this story's
-- pair up to V31/V32 — this file must stay immediately after the V31 snapshot it seeds into).
-- Mills 661-666 claimed fresh (8.1 read fixtures use 514/517/660 + the V2 mills 515/516 — never
-- mutate those). Master ids 8321-8340 + 8357-8358, detail ids 8341-8356 + 8359-8360 — inside the
-- free 83xx gap above V31's (masters 8301-8306, details 8305-8313) and below the sequence starts
-- (ILCR_COST_REPORT_DETAIL_SEQ 9000, ILCR_REPORT_COMMON_SEQ 9500), so sequence-drawn ids for
-- newly-added records never collide.
--
-- Isolation model (the V21 lesson, adapted): the shared container makes cleanup-free isolation
-- context-based, and a context is (mill, YEAR) — so the two mills that mutating tests hammer
-- (661 write playground, 665 lone-comment) carry MULTIPLE Draft years and each destructive test
-- method claims its own year. Check-status mills (663/664) are read-only by contract (the endpoint
-- mutates nothing) and share one year safely.
--
-- Delivery-faithfulness notes (Task 1, seeded real-data image 2026-08-04): every insert supplies
-- REVISION_COUNT + both audit pairs where the local DDL demands them (ROAD_MAINTENANCE_REPORT's
-- five are NOT NULL, no defaults — V31 DDL is delivery-faithful). Delivery also has the composite
-- FK RM_RPT_ILCR_RCAT_FK -> ILCR_REPORT_CATEGORY (report initialization pre-creates cat-6 rows for
-- ALL 118 delivery mill/years, so app inserts can never trip it); the V1 test snapshot has no such
-- FK, matching V31's review-approved shape — not added here.

-- ============ Mill 661 — write playground (WriteIT): Draft years 2019-2024 ============
-- One seeded record per year (TSA 01 + TSB 01B -> RMG 15; volume 1000 / cost 50000, REVISION_COUNT
-- 0) so every year offers an edit target and a stable rejection fingerprint; adds create rows via
-- the API on top.
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID) VALUES (661, 'Sch6 Write Milling', 661, 'SEED');
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID) VALUES (661, 'ACT', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2019, 661, 'D', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2020, 661, 'D', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2021, 661, 'D', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2022, 661, 'D', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2023, 661, 'D', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2024, 661, 'D', 'SEED');

INSERT INTO THE.ROAD_MAINTENANCE_REPORT (ROAD_MAINTENANCE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, TSA_NUMBER, TSB_NUMBER_CODE, TFL_NUMBER_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8334, 2019, 661, '6', '01', '01B', NULL, NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ROAD_MAINTENANCE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, COMMENTS, ENTRY_USERID)
  VALUES (8351, 8334, 69, 1000, 50000, 'Seeded 2019 record', 'SEED');
INSERT INTO THE.ROAD_MAINTENANCE_REPORT (ROAD_MAINTENANCE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, TSA_NUMBER, TSB_NUMBER_CODE, TFL_NUMBER_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8335, 2020, 661, '6', '01', '01B', NULL, NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ROAD_MAINTENANCE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, COMMENTS, ENTRY_USERID)
  VALUES (8352, 8335, 69, 1000, 50000, 'Seeded 2020 record', 'SEED');
INSERT INTO THE.ROAD_MAINTENANCE_REPORT (ROAD_MAINTENANCE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, TSA_NUMBER, TSB_NUMBER_CODE, TFL_NUMBER_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8336, 2021, 661, '6', '01', '01B', NULL, NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ROAD_MAINTENANCE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, COMMENTS, ENTRY_USERID)
  VALUES (8353, 8336, 69, 1000, 50000, 'Seeded 2021 record', 'SEED');
-- The 2022 edit/switch target deliberately has NO item-69 detail: the delivery-real shape (8.1
-- Task 1 — real cat-6 rows have zero details), so the edit path's detail upsert INSERT branch is
-- exercised by the IT exactly as it would be on real data.
INSERT INTO THE.ROAD_MAINTENANCE_REPORT (ROAD_MAINTENANCE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, TSA_NUMBER, TSB_NUMBER_CODE, TFL_NUMBER_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8337, 2022, 661, '6', '01', '01B', NULL, NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ROAD_MAINTENANCE_REPORT (ROAD_MAINTENANCE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, TSA_NUMBER, TSB_NUMBER_CODE, TFL_NUMBER_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8338, 2023, 661, '6', '01', '01B', NULL, NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ROAD_MAINTENANCE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, COMMENTS, ENTRY_USERID)
  VALUES (8355, 8338, 69, 1000, 50000, 'Seeded 2023 record', 'SEED');
INSERT INTO THE.ROAD_MAINTENANCE_REPORT (ROAD_MAINTENANCE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, TSA_NUMBER, TSB_NUMBER_CODE, TFL_NUMBER_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8339, 2024, 661, '6', '01', '01B', NULL, NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ROAD_MAINTENANCE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, COMMENTS, ENTRY_USERID)
  VALUES (8356, 8339, 69, 1000, 50000, 'Seeded 2024 record', 'SEED');

-- ============ Mill 662 — 1-10 track 'S' (non-Draft) -> write-gate 409 (AC4) ============
-- One record so the PUT/POST/general-comments 409s have a real target whose untouched
-- REVISION_COUNT/row-count is the nothing-persisted proof.
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID) VALUES (662, 'Sch6 Locked Milling', 662, 'SEED');
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID) VALUES (662, 'ACT', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2021, 662, 'S', 'SEED');
INSERT INTO THE.ROAD_MAINTENANCE_REPORT (ROAD_MAINTENANCE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, TSA_NUMBER, TSB_NUMBER_CODE, TFL_NUMBER_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8321, 2021, 662, '6', '03', '03B', NULL, 'Locked comment.', 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ROAD_MAINTENANCE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, COMMENTS, ENTRY_USERID)
  VALUES (8341, 8321, 69, 2000, 40000, 'Locked record', 'SEED');

-- ============ Mill 663 — check-status ALL MET (SUC-003 only, no per-record results) ============
-- Two complete records: TSA 01+01B with cost, TFL 18 with cost -> outcome MET, the single
-- scheduleRequirementsMetMsg banner, records: [] (the legacy pass branch never enters the loop).
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID) VALUES (663, 'Sch6 Complete Milling', 663, 'SEED');
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID) VALUES (663, 'ACT', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2021, 663, 'D', 'SEED');
INSERT INTO THE.ROAD_MAINTENANCE_REPORT (ROAD_MAINTENANCE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, TSA_NUMBER, TSB_NUMBER_CODE, TFL_NUMBER_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8322, 2021, 663, '6', '01', '01B', NULL, 'Complete comment.', 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ROAD_MAINTENANCE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, COMMENTS, ENTRY_USERID)
  VALUES (8342, 8322, 69, 1000, 50000, 'Complete TSA record', 'SEED');
INSERT INTO THE.ROAD_MAINTENANCE_REPORT (ROAD_MAINTENANCE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, TSA_NUMBER, TSB_NUMBER_CODE, TFL_NUMBER_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8323, 2021, 663, '6', NULL, NULL, '18', 'Complete comment.', 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ROAD_MAINTENANCE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, COMMENTS, ENTRY_USERID)
  VALUES (8343, 8323, 69, 400, 30000, 'Complete TFL record', 'SEED');

-- ============ Mill 664 — check-status MISSING flags (S09/S11/S20/S21 + quirks) ============
-- Row order by ROAD_MAINTENANCE_REPORT_ID; the leading placeholder (8324) is EXCLUDED (deviation
-- (d)) so the visible rowCounters start at 1 with 8325 — the ordinal semantics under test:
--   8324 placeholder (all-NULL classification, comment only)  -> excluded, shifts nothing.
--   8325 TSA 01+01B, cost 25000        -> rowCounter 1, met -> "All requirements for 1 ..." (S20)
--   8326 TSA 03+03B, detail cost NULL  -> rowCounter 2, "Road : 2 - TSA or TFL (Cost $) ..." (S09)
--   8327 TSA 05, no TSB, cost 10000    -> rowCounter 3, "Road : 3 - Supply Block ..." (S11)
--   8328 TSA 07, no TSB, NO detail     -> rowCounter 4, BOTH lines (S21)
--   8329 TFL 18, detail cost 0         -> rowCounter 5, met (cost==0 is MET - the D2 quirk)
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID) VALUES (664, 'Sch6 Incomplete Milling', 664, 'SEED');
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID) VALUES (664, 'ACT', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2021, 664, 'D', 'SEED');
INSERT INTO THE.ROAD_MAINTENANCE_REPORT (ROAD_MAINTENANCE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, TSA_NUMBER, TSB_NUMBER_CODE, TFL_NUMBER_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8324, 2021, 664, '6', NULL, NULL, NULL, 'Incomplete-mill comment.', 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ROAD_MAINTENANCE_REPORT (ROAD_MAINTENANCE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, TSA_NUMBER, TSB_NUMBER_CODE, TFL_NUMBER_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8325, 2021, 664, '6', '01', '01B', NULL, 'Incomplete-mill comment.', 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ROAD_MAINTENANCE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, COMMENTS, ENTRY_USERID)
  VALUES (8344, 8325, 69, 800, 25000, 'Complete row', 'SEED');
INSERT INTO THE.ROAD_MAINTENANCE_REPORT (ROAD_MAINTENANCE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, TSA_NUMBER, TSB_NUMBER_CODE, TFL_NUMBER_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8326, 2021, 664, '6', '03', '03B', NULL, 'Incomplete-mill comment.', 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ROAD_MAINTENANCE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, COMMENTS, ENTRY_USERID)
  VALUES (8345, 8326, 69, 500, NULL, 'Cost left blank', 'SEED');
INSERT INTO THE.ROAD_MAINTENANCE_REPORT (ROAD_MAINTENANCE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, TSA_NUMBER, TSB_NUMBER_CODE, TFL_NUMBER_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8327, 2021, 664, '6', '05', NULL, NULL, 'Incomplete-mill comment.', 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ROAD_MAINTENANCE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, COMMENTS, ENTRY_USERID)
  VALUES (8346, 8327, 69, 300, 10000, 'No supply block', 'SEED');
INSERT INTO THE.ROAD_MAINTENANCE_REPORT (ROAD_MAINTENANCE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, TSA_NUMBER, TSB_NUMBER_CODE, TFL_NUMBER_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8328, 2021, 664, '6', '07', NULL, NULL, 'Incomplete-mill comment.', 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ROAD_MAINTENANCE_REPORT (ROAD_MAINTENANCE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, TSA_NUMBER, TSB_NUMBER_CODE, TFL_NUMBER_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8329, 2021, 664, '6', NULL, NULL, '18', 'Incomplete-mill comment.', 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ROAD_MAINTENANCE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, COMMENTS, ENTRY_USERID)
  VALUES (8348, 8329, 69, 200, 0, 'Zero cost is present', 'SEED');

-- ============ Mill 665 — lone-comment / BR-09 write concerns: Draft years 2019-2024 ============
-- Per-year states:
--   2019, 2020, 2024 — EMPTY (the zero-rows + non-blank -> insert-placeholder branch).
--   2021 — placeholder 8330 only (the placeholder-only + blank -> delete branch).
--   2022 — placeholder 8331 only (the addRecord placeholder-REUSE branch: id + ENTRY_* survive).
--   2023 — two real records 8332/8333 sharing a replicated comment (the update-every-row branch).
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID) VALUES (665, 'Sch6 Lone Comment Milling', 665, 'SEED');
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID) VALUES (665, 'ACT', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2019, 665, 'D', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2020, 665, 'D', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2021, 665, 'D', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2022, 665, 'D', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2023, 665, 'D', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2024, 665, 'D', 'SEED');

INSERT INTO THE.ROAD_MAINTENANCE_REPORT (ROAD_MAINTENANCE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, TSA_NUMBER, TSB_NUMBER_CODE, TFL_NUMBER_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8330, 2021, 665, '6', NULL, NULL, NULL, 'Lone comment to clear.', 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ROAD_MAINTENANCE_REPORT (ROAD_MAINTENANCE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, TSA_NUMBER, TSB_NUMBER_CODE, TFL_NUMBER_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8331, 2022, 665, '6', NULL, NULL, NULL, 'Lone comment to reuse.', 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ROAD_MAINTENANCE_REPORT (ROAD_MAINTENANCE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, TSA_NUMBER, TSB_NUMBER_CODE, TFL_NUMBER_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8332, 2023, 665, '6', '01', '01B', NULL, 'Replicated comment.', 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ROAD_MAINTENANCE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, COMMENTS, ENTRY_USERID)
  VALUES (8349, 8332, 69, 100, 1000, 'Replication row 1', 'SEED');
INSERT INTO THE.ROAD_MAINTENANCE_REPORT (ROAD_MAINTENANCE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, TSA_NUMBER, TSB_NUMBER_CODE, TFL_NUMBER_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8333, 2023, 665, '6', NULL, NULL, '18', 'Replicated comment.', 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ROAD_MAINTENANCE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, COMMENTS, ENTRY_USERID)
  VALUES (8350, 8333, 69, 200, 2000, 'Replication row 2', 'SEED');

-- ============ Code-review 2026-08-04 additions: contexts that were being shared ============
-- Three tests were reaching into contexts another suite owns, so a regression in one would surface
-- as a confusing failure in another (order-dependently). Each now gets its own context.

-- 661/2018 + placeholder 8340: the WriteIT placeholder-id-404 probe. Was PUTting 8324 in mill
-- 664/2021 — a context V32 declares read-only and Schedule6CheckStatusIT fingerprints — so a
-- regression in the placeholder guard would have converted a check-status fixture row into a real
-- record and broken that suite's ordinals instead of failing locally.
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2018, 661, 'D', 'SEED');
INSERT INTO THE.ROAD_MAINTENANCE_REPORT (ROAD_MAINTENANCE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, TSA_NUMBER, TSB_NUMBER_CODE, TFL_NUMBER_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8340, 2018, 661, '6', NULL, NULL, NULL, 'Placeholder for the 404 probe.', 0, 'SEED', SYSDATE, 'SEED', SYSDATE);

-- 661/2017 + record 8361 WITH detail 8362: the detail-upsert UPDATE-IN-PLACE proof. Needs its own
-- year because it mutates, and every other 661 year is already claimed by one destructive test (2023
-- holds only rejection tests, which mutate nothing — putting an edit there would break the very
-- one-destructive-test-per-year contract this review is enforcing).
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2017, 661, 'D', 'SEED');
INSERT INTO THE.ROAD_MAINTENANCE_REPORT (ROAD_MAINTENANCE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, TSA_NUMBER, TSB_NUMBER_CODE, TFL_NUMBER_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8361, 2017, 661, '6', '01', '01B', NULL, NULL, 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ROAD_MAINTENANCE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, COMMENTS, ENTRY_USERID)
  VALUES (8362, 8361, 69, 1000, 50000, 'Seeded 2017 record', 'SEED');

-- 665/2018 + record 8357: the BR-09 replication proof on ADD (a new record must carry the CURRENT
-- general comment). Needs a context whose master COMMENTS is NON-NULL and whose comment no other
-- test rewrites — every 661 row is seeded COMMENTS NULL, and 665/2023's comment is rewritten by the
-- replication test, so nothing could prove the insert-side binding before.
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2018, 665, 'D', 'SEED');
INSERT INTO THE.ROAD_MAINTENANCE_REPORT (ROAD_MAINTENANCE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, TSA_NUMBER, TSB_NUMBER_CODE, TFL_NUMBER_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8357, 2018, 665, '6', '01', '01B', NULL, 'Carried general comment.', 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ROAD_MAINTENANCE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, COMMENTS, ENTRY_USERID)
  VALUES (8359, 8357, 69, 100, 1000, 'Carrier row', 'SEED');

-- Mill 666 — owned solely by Schedule6WriteAuthorizationIT. Its three would-be writes previously
-- fired at 661/2021, the year optimisticLockPerRecord owns, so an @PreAuthorize regression would
-- have mutated that test's lock target.
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID) VALUES (666, 'Sch6 Authz Milling', 666, 'SEED');
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID) VALUES (666, 'ACT', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2021, 666, 'D', 'SEED');
INSERT INTO THE.ROAD_MAINTENANCE_REPORT (ROAD_MAINTENANCE_REPORT_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, TSA_NUMBER, TSB_NUMBER_CODE, TFL_NUMBER_CODE, COMMENTS, REVISION_COUNT, ENTRY_USERID, ENTRY_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
  VALUES (8358, 2021, 666, '6', '01', '01B', NULL, 'Authz probe target.', 0, 'SEED', SYSDATE, 'SEED', SYSDATE);
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ROAD_MAINTENANCE_REPORT_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, COMMENTS, ENTRY_USERID)
  VALUES (8360, 8358, 69, 100, 1000, 'Authz row', 'SEED');

-- Reused READ-ONLY: mill 515/2021 (V2 — ACT + Draft, zero cat-6 rows) for the check-status
-- zero-records vacuous pass; mill 660/2021 (V31 — lone-comment read fixture) for the check-status
-- lone-comment vacuous pass (deviation (d)); mill 516/2021 (CLS) for the 409 context guard; an
-- unknown mill for the 404 guard. None of them is mutated by 8.2 tests.

COMMIT;
