-- Story 1.2 seed EXTENSION (never edit V1/V2). Gives the 514/2021 Schedule 1 document assertable
-- content: CROWN_VOLUME/COMMENTS on the category-1 summaries (V2 seeded neither), and detail rows
-- pinned to the wire-contract example so IT and contract agree.

-- V2 set CROWN_VOLUME only on the category-3 summary (1003); set it on the category-1 summaries here.
UPDATE THE.ILCR_REPORT_SUMMARY SET CROWN_VOLUME = 12345, COMMENTS = 'Seed comment for 514/2021' WHERE ILCR_REPORT_SUMMARY_ID = 1001;
UPDATE THE.ILCR_REPORT_SUMMARY SET CROWN_VOLUME = 6789,  COMMENTS = 'Seed comment for 517/2021' WHERE ILCR_REPORT_SUMMARY_ID = 1017;

-- Detail rows for summary 1001 (mill 514 / 2021 / cat 1).
-- code 12 Standing Tree: VOLUME 1000 / COST 50000 -> perUnit 50.0
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (5001, 1001, 12, 1000, 50000, NULL, 'SEED');
-- code 1 Silviculture Actual: a silviculture-block member
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (5002, 1001, 1, 500, 20000, NULL, 'SEED');
-- item 19 shared-volume row (null description carries the shared Other-Costs volume 8000)
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (5003, 1001, 19, 8000, NULL, NULL, 'SEED');
-- item 19 itemized rows (non-null description): two rows, COST 12000 each -> subtotal 24000, count 2, perUnit 3.0
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (5004, 1001, 19, NULL, 12000, 'Row A', 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (5005, 1001, 19, NULL, 12000, 'Row B', 'SEED');

-- One detail row on summary 1017 (mill 517, non-Draft) so the non-Draft assembly path has real data.
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (5017, 1017, 12, 2000, 40000, NULL, 'SEED');

COMMIT;
