-- Story 2.3 seed EXTENSION (never edit V1-V4). Adds the Schedule 3 source data that Schedule 1's
-- BR-03 Crown Timber pre-fill and BR-04 admin-cost pulls read, plus an all-volumes-empty fixture so
-- the pre-fill path is testable.
--
-- D1 (resolved): the Schedule 3 Crown Timber volume is the VOLUME of the ILCR_COST_REPORT_DETAIL row
-- with ILCR_REPORT_COST_ITEM_ID = 119 under the category-3 summary (legacy-faithful) — NOT the
-- dead ILCR_REPORT_SUMMARY.CROWN_VOLUME column. We seed a DISTINCT value (54321) from the cat-1
-- summary CROWN_VOLUME (12345, set in V3) so tests prove the pre-fill source is the item-119 detail.
-- [PARITY-VERIFY: confirm against the delivery DB before production.]

-- Schedule 3 cost items the Story 2.3 reads reference (category '3'). No FK in the test snapshot, but
-- registered for hygiene/traceability.
INSERT INTO THE.ILCR_REPORT_COST_ITEM (ILCR_REPORT_COST_ITEM_ID, ITEM_NAME, ILCR_CATEGORY_ID, ILCR_SUBCATEGORY_ID, ENTRY_USERID) VALUES (37,  'Silviculture Admin Costs (Harvest)', '3', '1', 'SEED');
INSERT INTO THE.ILCR_REPORT_COST_ITEM (ILCR_REPORT_COST_ITEM_ID, ITEM_NAME, ILCR_CATEGORY_ID, ILCR_SUBCATEGORY_ID, ENTRY_USERID) VALUES (115, 'Subtotal Actual Costs (Harvest)', '3', '1', 'SEED');
INSERT INTO THE.ILCR_REPORT_COST_ITEM (ILCR_REPORT_COST_ITEM_ID, ITEM_NAME, ILCR_CATEGORY_ID, ILCR_SUBCATEGORY_ID, ENTRY_USERID) VALUES (135, 'Subtotal Actual Costs (PO&P)', '3', '1', 'SEED');
INSERT INTO THE.ILCR_REPORT_COST_ITEM (ILCR_REPORT_COST_ITEM_ID, ITEM_NAME, ILCR_CATEGORY_ID, ILCR_SUBCATEGORY_ID, ENTRY_USERID) VALUES (119, 'Crown Timber', '3', '1', 'SEED');

-- 514/2021: give the EXISTING category-3 summary (1003) its Schedule 3 source rows.
--   Crown Timber (item 119) VOLUME = 54321 (BR-03 source; distinct from cat-1 CROWN_VOLUME 12345).
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (5031, 1003, 119, 54321, NULL, NULL, 'SEED');
--   BR-04 Forest Management Admin Cost = crownCost of Subtotal Actual Costs = cost(115) - cost(135).
--     115 (harvest) 900000, 135 (pop) 300000 -> 600000.
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (5032, 1003, 115, NULL, 900000, NULL, 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (5033, 1003, 135, NULL, 300000, NULL, 'SEED');
--   BR-04 Less Silviculture Admin Cost = crownCost of Silviculture Admin (PO&P forced 0) = cost(37).
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (5034, 1003, 37, NULL, 150000, NULL, 'SEED');

-- Mill 522 - AAA Prefill: ACT, Draft, has a category-1 summary with NO detail rows (all Schedule 1
-- volume fields empty) and a category-3 summary carrying a Crown Timber (item 119) volume = 7777.
-- GET on this fixture must trigger the BR-03 pre-fill + WRN-001 (AC1).
INSERT INTO THE.MILL (MILL_ID, MILL_NAME, MILL_NUMBER, ENTRY_USERID) VALUES (522, 'Prefill Milling', 522, 'SEED');
INSERT INTO THE.ILCR_MILL_STATUS_XREF (ILCR_MILL_STATUS_XREF_ID, ILCR_MILL_STATUS_CODE, ENTRY_USERID) VALUES (522, 'ACT', 'SEED');
INSERT INTO THE.ILCR_MILL_REPORT_STATUS (REPORT_YEAR, ILCR_MILL_ID, ILCR_MILL_REPORT_STATUS_CODE, ENTRY_USERID) VALUES (2021, 522, 'D', 'SEED');
INSERT INTO THE.ILCR_REPORT_SUMMARY (ILCR_REPORT_SUMMARY_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, ENTRY_USERID) VALUES (1022, 2021, 522, '1', 'SEED');
INSERT INTO THE.ILCR_REPORT_SUMMARY (ILCR_REPORT_SUMMARY_ID, REPORT_YEAR, ILCR_MILL_ID, ILCR_CATEGORY_ID, ENTRY_USERID) VALUES (1024, 2021, 522, '3', 'SEED');
INSERT INTO THE.ILCR_COST_REPORT_DETAIL (ILCR_COST_REPORT_DETAIL_ID, ILCR_REPORT_SUMMARY_ID, ILCR_REPORT_COST_ITEM_ID, VOLUME, COST, ITEM_DESCRIPTION, ENTRY_USERID) VALUES (5040, 1024, 119, 7777, NULL, NULL, 'SEED');

COMMIT;
