# Re-grounded from _bmad-output/implementation-artifacts/tests/UC-SCH6-001/gherkin/UC-SCH6-001-S12.feature
# (legacy JSF/PrimeFaces). S12 refuses an "Add Report" that names no TSA/TFL area type, then accepts
# the record once one is chosen.
#
# THIS SLICE CLOSES SPEC-2, AND THAT IS ITS MOST IMPORTANT OUTPUT.
# The source Gherkin does not carry the error text at all — it reads "Then the system displays the
# error [UNKNOWN — exact required-field message text not confirmed in source]", because the recovery
# work looked for a custom literal and legacy had none: the JSF framework supplied the required-field
# message at runtime from `UIInput`, so there was nothing in `messages.properties` or `faces-config.xml`
# to read. Rather than fabricate one, it was flagged.
#
# The rebuilt app does NOT inherit a framework default — it declares the message itself:
#
#     areaTypeRequired: 'TSA or TFL: Value is required.'
#         src/components/schedule6/validation.ts:61
#
# and that module's own header states those literals are transcribed "verbatim from the backend bundle
# (messages.properties) so an advisory message is byte-identical to the server's rejection for the same
# field". So the text asserted below is taken from the RUNNING APP, which is exactly what SPEC-2 said
# would have to happen. **It is NOT confirmed against legacy** — nobody can confirm it against legacy,
# because the legacy string was generated by a framework that is gone. BA/QA are asked in defects.md
# to accept it as the ILCR wording, and that is the one open question this slice leaves behind.
#
# WHEN THE ERROR APPEARS — the same re-grounding the whole S12-S16 block shares (defects.md VER-5).
# Legacy validated per field over ajax; here nothing validates on blur (`onBlur` runs `commitRate`,
# which validates only to decide whether to move the $ / m³ cell and then throws the errors away,
# index.tsx:533-542). The message is set by `handleAdd`, so it appears on **Add Report**.
#
# "AND THE RECORD IS NOT ADDED" IS PROVED TWICE OVER, and the two halves are different claims:
#   * the spy asserts ZERO mutating requests — this refusal is decided on the client, so `handleAdd`
#     returns before the POST is even built (index.tsx:682-686). Note the contrast with S05, whose
#     invalid TFL number costs exactly ONE request because only the server knows the RMG table;
#   * the anchor is then read back, because a spy proves no request was SENT while only a read proves
#     nothing was STORED.
#
# WHY TWO SCENARIOS AND TWO ANCHORS. The legacy file's second scenario continues from the first
# ("Given the system has displayed the required-field error"); scenarios here are independent, so the
# correction arm re-creates the error itself before fixing it — the structure S05 already uses. The arms
# cannot share a cell: the reject arm writes nothing and rides the shared VALIDATE-ONLY anchor
# (22050/2024), while the correction arm SAVES and so needed its own (24050/2024, minted for it) — a
# writer cannot share a (mill, year) under `fullyParallel`.
#
# NOT COVERED HERE (see coverage.md): a blank TFL number on the TFL branch, which is refused by the
# same client gate but with the TFL message, belongs to S05's family. The numeric field rejections are
# S13-S16 in `amount-validation.feature`.

@sch6 @UC-SCH6-001 @required-field
Feature: Report Road Management Costs (Schedule 6) — a road record must name an area type
  As a mill reporter
  I want a submission with no Timber Supply Area or TFL chosen to be refused
  So that every stored road record is classified

  @p1 @S12
  Scenario: Submitting with no area type selected is refused and nothing is stored
    Given the Schedule 6 anchor "validate-only" is an editable Draft with no road records
    # Registered even though this arm must store NOTHING — the S05 precedent. If the app ever regressed
    # and stored the refused entry, a comment-less row would be invisible to cleanup and would strand
    # the SHARED validate-only anchor, turning one real failure into every other validation slice
    # failing for the wrong reason.
    And I will record a road maintenance record commented "E2E S12 rejected blank area type"
    And I have selected that mill and reporting year on the Home page
    And I am watching for Schedule 6 writes
    When I open Schedule 6
    And I open the Add Road Maintenance report panel
    Then the Add panel is shown with its fields blank
    And no area type is selected in the Add panel
    When I enter valid amounts with no area type selected
    And I submit the Add panel
    Then I should see the error "TSA or TFL: Value is required."
    And no Schedule 6 write was attempted
    And no road record was stored on that anchor
    And the Schedule 6 record list shows no records

  @p1 @S12
  Scenario: Choosing an area type lets the record save
    Given the Schedule 6 anchor "area-type-correction" is an editable Draft with no road records
    And I will record a road maintenance record commented "E2E S12 corrected area type record"
    And I have selected that mill and reporting year on the Home page
    When I open Schedule 6
    And I open the Add Road Maintenance report panel
    And I enter valid amounts with no area type selected
    And I submit the Add panel
    Then I should see the error "TSA or TFL: Value is required."
    When I select the area type and supply block
    And I submit the Add panel
    Then I should see the message "Data saved successfully"
    And the corrected road record is persisted
