/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmissionsRouteImport } from './routes/submissions'
import { Route as Schedule4RouteImport } from './routes/schedule-4'
import { Route as Schedule2RouteImport } from './routes/schedule-2'
import { Route as Schedule1RouteImport } from './routes/schedule-1'
import { Route as MillAssociationsRouteImport } from './routes/mill-associations'
import { Route as IndexRouteImport } from './routes/index'

const SubmissionsRoute = SubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const Schedule4Route = Schedule4RouteImport.update({
  id: '/schedule-4',
  path: '/schedule-4',
  getParentRoute: () => rootRouteImport,
} as any)
const Schedule2Route = Schedule2RouteImport.update({
  id: '/schedule-2',
  path: '/schedule-2',
  getParentRoute: () => rootRouteImport,
} as any)
const Schedule1Route = Schedule1RouteImport.update({
  id: '/schedule-1',
  path: '/schedule-1',
  getParentRoute: () => rootRouteImport,
} as any)
const MillAssociationsRoute = MillAssociationsRouteImport.update({
  id: '/mill-associations',
  path: '/mill-associations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mill-associations': typeof MillAssociationsRoute
  '/schedule-1': typeof Schedule1Route
  '/schedule-2': typeof Schedule2Route
  '/schedule-4': typeof Schedule4Route
  '/submissions': typeof SubmissionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mill-associations': typeof MillAssociationsRoute
  '/schedule-1': typeof Schedule1Route
  '/schedule-2': typeof Schedule2Route
  '/schedule-4': typeof Schedule4Route
  '/submissions': typeof SubmissionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mill-associations': typeof MillAssociationsRoute
  '/schedule-1': typeof Schedule1Route
  '/schedule-2': typeof Schedule2Route
  '/schedule-4': typeof Schedule4Route
  '/submissions': typeof SubmissionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mill-associations'
    | '/schedule-1'
    | '/schedule-2'
    | '/schedule-4'
    | '/submissions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mill-associations'
    | '/schedule-1'
    | '/schedule-2'
    | '/schedule-4'
    | '/submissions'
  id:
    | '__root__'
    | '/'
    | '/mill-associations'
    | '/schedule-1'
    | '/schedule-2'
    | '/schedule-4'
    | '/submissions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MillAssociationsRoute: typeof MillAssociationsRoute
  Schedule1Route: typeof Schedule1Route
  Schedule2Route: typeof Schedule2Route
  Schedule4Route: typeof Schedule4Route
  SubmissionsRoute: typeof SubmissionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submissions': {
      id: '/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof SubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule-4': {
      id: '/schedule-4'
      path: '/schedule-4'
      fullPath: '/schedule-4'
      preLoaderRoute: typeof Schedule4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule-2': {
      id: '/schedule-2'
      path: '/schedule-2'
      fullPath: '/schedule-2'
      preLoaderRoute: typeof Schedule2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule-1': {
      id: '/schedule-1'
      path: '/schedule-1'
      fullPath: '/schedule-1'
      preLoaderRoute: typeof Schedule1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mill-associations': {
      id: '/mill-associations'
      path: '/mill-associations'
      fullPath: '/mill-associations'
      preLoaderRoute: typeof MillAssociationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MillAssociationsRoute: MillAssociationsRoute,
  Schedule1Route: Schedule1Route,
  Schedule2Route: Schedule2Route,
  Schedule4Route: Schedule4Route,
  SubmissionsRoute: SubmissionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
